In [1]:
import numpy as np
import pandas as pd
import pandasql
import sqlite3

pd.set_option("display.max_columns", None) 
pd.set_option("display.max_colwidth", 1000) #huruf dlm column
pd.set_option("display.max_rows", 100)
pd.set_option("display.precision", 2) #2 titik perpuluhan


#sheet_name='SourceCM'
#sheet_name = 'cb os by mkt seg 2'

#import
date = 'Aug22'
date2='20220831'
sheet_name = 'SourceCM'

#export
date1='2022-08'


FXCurrency = pd.read_excel(r'T:\MIB Risk Management\Credit Risk Analytics - Historical\02_Data_Source\01_Corporate_Financing\01_Portfolio\\'+date2+'\GB Monthly Loan Outstanding '+date+'.xlsx', sheet_name = 'SourceCM')

In [2]:
description = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\Python\User defined\description.xlsx", sheet_name='description')

In [5]:
FXCurrency.columns = FXCurrency.columns.str.upper()
FXCurrency.columns = FXCurrency.columns.str.strip()
FXCurrency.columns = FXCurrency.columns.str.replace(" ", "_")

#FXCurrency.M_FINANCING_TYPE_CD = FXCurrency.M_FINANCING_TYPE_CD.str.upper()
#FXCurrency.M_FINANCING_TYPE_CD = FXCurrency.M_FINANCING_TYPE_CD.str.strip()

#FXCurrency.ISO_CURRENCY_CD = FXCurrency.ISO_CURRENCY_CD.str.upper()
#FXCurrency.ISO_CURRENCY_CD = FXCurrency.ISO_CURRENCY_CD.str.strip()

#FXCurrency.COMMON_COA_ID = FXCurrency.COMMON_COA_ID.astype(int)

In [14]:
FXCurrencya = FXCurrency.iloc[np.where((FXCurrency.COMMON_COA_ID==12000)&(FXCurrency.M_FINANCING_TYPE_CD=='I')&(FXCurrency.ISO_CURRENCY_CD !='MYR'))]

FXCurrency1 = FXCurrencya[['M_CUS_NO','NAME','CB_GROUP_NAME','ISO_CURRENCY_CD','FACILITY_2','CUR_BOOK_BAL_SUM','M_BNM_BALANCE_SUM']]

FXCurrency2 = FXCurrency1.groupby(['M_CUS_NO','NAME','CB_GROUP_NAME','ISO_CURRENCY_CD','FACILITY_2'])[['CUR_BOOK_BAL_SUM','M_BNM_BALANCE_SUM']].sum().reset_index()

FXCurrency2.sort_values(by=['M_BNM_BALANCE_SUM'],ascending=[False],inplace=True)

FXCurrency2['FX'] = FXCurrency2['M_BNM_BALANCE_SUM']/FXCurrency2['CUR_BOOK_BAL_SUM']

FCY = FXCurrency2.merge(FXCurrencya[['M_CUS_NO','M_NEW_ID_NUMBER','M_MSIC_CODE']].drop_duplicates('M_CUS_NO'), on='M_CUS_NO', how='left')

FCY['ACOUNT_CLASSIFICATION'] = 'NA'
FCY['BRR'] = 'NA'


FCY.M_MSIC_CODE = FCY.M_MSIC_CODE.map(str)
FCY.M_MSIC_CODE = FCY.M_MSIC_CODE.str.strip()
FCY.M_MSIC_CODE = FCY.M_MSIC_CODE.str.upper()


description.columns = description.columns.str.strip()
description.columns = description.columns.str.replace(" ", "_")
description.columns = description.columns.str.upper()


description.ISC_NOB = description.ISC_NOB.map(str)
description.ISC_NOB = description.ISC_NOB.str.strip()
description.ISC_NOB = description.ISC_NOB.str.upper()


FCYb = FCY.merge(description[['ISC_NOB','ISC_PARENT2','INDUSTRIAL_SECTOR_CODE_(ISC_DESC)2']].drop_duplicates().rename(columns = {'ISC_NOB':'M_MSIC_CODE'}), on='M_MSIC_CODE', how='left')


FCYa = FCYb.rename(columns={'M_CUS_NO':'GCIF_NO',\
                          'M_NEW_ID_NUMBER':'BRIC',\
                          'NAME':'CUSTOMER_NAME',\
                          'CB_GROUP_NAME':'CUSTOMER_GROUP',\
                          'ISO_CURRENCY_CD':'FINANCING_CURRENCY',\
                          'CUR_BOOK_BAL_SUM':'FCY',\
                          'M_BNM_BALANCE_SUM':'RM',\
                          'FACILITY_2':'FINANCING_TYPE',\
                          'M_MSIC_CODE':'INDUSTRIAL_SECTOR_CODE',\
                          'ISC_PARENT2':'INDUSTRIAL_SECTOR',\
                          'INDUSTRIAL_SECTOR_CODE_(ISC_DESC)2':'INDUSTRIAL_SECTOR_DESCRIPTION'})


FCY1 = FCYa[['GCIF_NO','BRIC','CUSTOMER_NAME','CUSTOMER_GROUP','FINANCING_CURRENCY','FCY','RM','FX','ACOUNT_CLASSIFICATION','FINANCING_TYPE','INDUSTRIAL_SECTOR_CODE','INDUSTRIAL_SECTOR','INDUSTRIAL_SECTOR_DESCRIPTION','BRR']].sort_values(by=['RM','INDUSTRIAL_SECTOR'],ascending=[False,True])


FCY2 = FCY1.sort_values(by=['CUSTOMER_GROUP'],ascending=[False])

In [18]:
date1='2022-08'
FCY2.to_excel(r'T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\06_BNM Request\\'+date1+'\FCY '+date1+'(python).xlsx', sheet_name='FX', index=False)

In [19]:
FCY2.shape

(49, 14)

In [13]:
FXCurrencya.iloc[np.where(FXCurrencya.NAME.str.contains('SHARJAH'))]

,AS_OF_DATE,M_CUS_NO,NAME,DESCRIPTION,STATE_DESC,BRANCH_CODE,CUST_CLASS_CD,NATURE_OF_BUSINESS,ECONOMIC_SECTOR_CD,M_NPL_DATE,M_SUB_MARKET_SEGMENT_CD,M_MARKET_SEGMENT_CD,NPL_FLG,M_PARTIAL_WOFF_FLG,DESCRIPTION.1,M_CUSTOMER_TYPE,M_FULL_WRITEOFF_FLG,M_FINANCING_TYPE_CD,ISO_CURRENCY_CD,M_ACCOUNT_NO,M_NEW_NPL_FLG,M_INTEREST_CODE,M_SOURCE_PROD_TYPE_CD,FACILITY,FACILITY_2,M_BNM_BALANCE_SUM,AUTHORISED_LIMIT_SUM,M_APPROVED_LIMIT_SUM,CUR_BOOK_BAL_SUM,MATURITY_DATE,ORIGINATION_DATE,M_MSIC_CODE,DESCRIPTION.2,ISC,AVG_BOOK_BAL_SUM,COMMON_COA_ID,ISSUE_DATE,M_STOCK_CODE,M_FOLDER_NAME,M_NEW_ID_NUMBER,CB_GROUP_NAME,AO/AM,AD,DIR,SD,BIZ_SEG
25544,2022-08-31,2.77e+07,SHARJAH ELECTRICITY WATER AND GAS AUTHOR,IBS KUALA LUMPUR MAIN,FED. TERRITORY,6401.0,305.0,NaN,9999,01/01/1900,5.0,2.0,N,N,Foreign Currency Loan,204.0,N,I,USD,764016800776,NaN,10.0,H5,TL_FC,TL,1.21e+08,0.0,2.70e+07,2.70e+07,2025-12-22,2020-12-22,3510XB,Electr.Pwr.Gen.-Nat.GasFiredPwr.Plant,"Electricity, Gas, Steam and Air Conditioning Supply",2.70e+07,12000.0,2020-12-22,NaN,NaN,2020DU0001,GOVERNMENT OF UNITED ARAB EMIRATES,TBD,TBD,TBD,TBD,DUBAI
25545,2022-08-31,2.77e+07,SHARJAH ELECTRICITY WATER AND GAS AUTHOR,IBS KUALA LUMPUR MAIN,FED. TERRITORY,6401.0,305.0,NaN,9999,01/01/1900,5.0,2.0,N,N,Foreign Currency Loan,204.0,N,I,USD,764016800783,NaN,10.0,H5,TL_FC,TL,1.34e+07,0.0,3.00e+06,3.00e+06,2026-01-12,2021-01-12,3510XB,Electr.Pwr.Gen.-Nat.GasFiredPwr.Plant,"Electricity, Gas, Steam and Air Conditioning Supply",3.00e+06,12000.0,2021-01-12,NaN,NaN,2020DU0001,GOVERNMENT OF UNITED ARAB EMIRATES,TBD,TBD,TBD,TBD,DUBAI

In [17]:
FCY1.iloc[np.where(FCY1.CUSTOMER_NAME.str.contains('SHARJAH'))]

,GCIF_NO,BRIC,CUSTOMER_NAME,CUSTOMER_GROUP,FINANCING_CURRENCY,FCY,RM,FX,ACOUNT_CLASSIFICATION,FINANCING_TYPE,INDUSTRIAL_SECTOR_CODE,INDUSTRIAL_SECTOR,INDUSTRIAL_SECTOR_DESCRIPTION,BRR
13,2.77e+07,2020DU0001,SHARJAH ELECTRICITY WATER AND GAS AUTHOR,GOVERNMENT OF UNITED ARAB EMIRATES,USD,3.00e+07,1.34e+08,4.48,NA,TL,3510XB,"ELECTRICITY, GAS, STEAM AND AIR CONDITIONING SUPPLY",ELECTRICITY POWER GENERATION - NATURAL GAS FIRED POWER PLANT,NA

In [3]:
FXCurrencya.head(1)

,AS_OF_DATE,M_CUS_NO,NAME,DESCRIPTION,STATE_DESC,BRANCH_CODE,CUST_CLASS_CD,NATURE_OF_BUSINESS,ECONOMIC_SECTOR_CD,M_NPL_DATE,M_SUB_MARKET_SEGMENT_CD,M_MARKET_SEGMENT_CD,NPL_FLG,M_PARTIAL_WOFF_FLG,DESCRIPTION.1,M_CUSTOMER_TYPE,M_FULL_WRITEOFF_FLG,M_FINANCING_TYPE_CD,ISO_CURRENCY_CD,M_ACCOUNT_NO,M_NEW_NPL_FLG,M_INTEREST_CODE,M_SOURCE_PROD_TYPE_CD,FACILITY,FACILITY_2,M_BNM_BALANCE_SUM,AUTHORISED_LIMIT_SUM,M_APPROVED_LIMIT_SUM,CUR_BOOK_BAL_SUM,MATURITY_DATE,ORIGINATION_DATE,M_MSIC_CODE,DESCRIPTION.2,ISC,AVG_BOOK_BAL_SUM,COMMON_COA_ID,ISSUE_DATE,M_STOCK_CODE,M_FOLDER_NAME,M_NEW_ID_NUMBER,CB_GROUP_NAME,AO/AM,AD,DIR,SD,BIZ_SEG
2653,2022-08-31,3706156,WHITE HORSE CERAMIC INDUSTRIES SDN BHD,NaN,NaN,NaN,121,3619,NaN,Null,5,2,NaN,NaN,Investments,202,NaN,I,USD,03TJBI000007,NaN,NaN,03,STRC_FC,STRC,6.71e+06,0.0,0.0,1.50e+06,2022-12-09,2022-06-10,23XXXC,Mfg.Of Otr. NonmetallicMineralProd. NEC,Manufacturing,1.50e+06,12000,2022-06-10,NaN,NaN,216824X,WHITE HORSE,SHJ,NZS,FMC,GST,JOH

In [10]:
FCY2

,GCIF_NO,BRIC,CUSTOMER_NAME,CUSTOMER_GROUP,FINANCING_CURRENCY,FCY,RM,FX,ACOUNT_CLASSIFICATION,FINANCING_TYPE,INDUSTRIAL_SECTOR_CODE,INDUSTRIAL_SECTOR,INDUSTRIAL_SECTOR_DESCRIPTION,BRR
47,6089413,236761P,ZETRO SERVICES SDN. BHD.,ZETRO,USD,0.00e+00,0.00e+00,NaN,NA,TB,7110X,"PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES",ARCHITECTURAL AND ENGINEERING ACTIVITIES AND RELATED TECHNICAL CONSULTANCY,NA
18,21775114,1042951D,YE CHIU NON-FERROUS METAL (M) SDN. BHD.,YE CHIU,USD,1.65e+07,7.38e+07,4.48,NA,TL,24209B,MANUFACTURING,MANUFACTURE OF OTHER NON-FERROUS METALS N.E.C.,NA
29,3706156,216824X,WHITE HORSE CERAMIC INDUSTRIES SDN BHD,WHITE HORSE,USD,4.50e+06,2.01e+07,4.48,NA,STRC,23XXXC,MANUFACTURING,MANUFACTURE OF OTHER NON-METALLIC MINERAL PRODUCTS N.E.C,NA
42,7358732,88160P,V.S INDUSTRY BERHAD,VS INDUSTRY,USD,1.06e+06,4.73e+06,4.48,NA,TB,22XXXG,MANUFACTURING,MANUFACTURE OF PLASTIC PRODUCTS,NA
30,7358732,88160P,V.S INDUSTRY BERHAD,VS INDUSTRY,USD,4.24e+06,1.90e+07,4.48,NA,TL,22XXXG,MANUFACTURING,MANUFACTURE OF PLASTIC PRODUCTS,NA
14,25167406,1240905H,SUMBER RIBU SDN. BHD.,VELESTO,USD,2.69e+07,1.20e+08,4.48,NA,STRC,64200,FINANCIAL AND INSURANCE/ TAKAFUL ACTIVITIES,ACTIVITIES OF HOLDING COMPANIES,NA
26,23580679,1152825H,UMW AEROSPACE SDN. BHD.,UMWH,USD,5.99e+06,2.68e+07,4.48,NA,TB,28299D,MANUFACTURING,"MANUFACTURE OF AIRCRAFT LAUNCHING GEAR, AIRCRAFT CARRIER CATAPULTS AND RELATED EQUIPMENT",NA
45,12153815,499486U,MARDEC PROCESSING SDN. BHD.,TS SYED MOKHTAR (MARDEC),USD,5.69e+05,2.55e+06,4.48,NA,TB,22XXXF,MANUFACTURING,MANUFACTURE OF OTHER RUBBER PRODUCTS N.E.C,NA
32,14824864,311703P,CTRM AERO COMPOSITES SDN. BHD.,TS SYED MOKHTAR (DRB HICOM),USD,3.68e+06,1.65e+07,4.48,NA,TB,30999A,MANUFACTURING,MANUFACTURE OF AIR AND SPACECRAFT AND RELATED MACHINERY,NA
37,7314359,200675U,TONG HEER ALUMINIUM INDUSTRIES SDN BHD,TONG HEER RESOURCES,USD,2.16e+06,9.68e+06,4.48,NA,TB,2599X,MANUFACTURING,MANUFACTURE OF OTHER FABRICATED METAL PRODUCTS N.E.C.,NA
44,20864429,702463P,SUNRISE ICON SDN BHD,TECK GUAN,USD,5.78e+05,2.59e+06,4.48,NA,TL,10402A,MANUFACTURING,INTEGRATED PLAYER FOR MANUFACTURE OF REFINED PALM OIL,NA
24,20864429,702463P,SUNRISE ICON SDN BHD,TECK GUAN,USD,7.50e+06,3.36e+07,4.48,NA,STRC,10402A,MANUFACTURING,INTEGRATED PLAYER FOR MANUFACTURE OF REFINED PALM OIL,NA
3,11852516,19698X,S P SETIA BERHAD,SP SETIA,GBP,7.94e+07,4.14e+08,5.21,NA,TL,41001B,CONSTRUCTION,"DEVELOPER - LANDED RESIDENTIAL UNITS (E.G. LINK, SEMI-D & DETACHED HOUSES) FOR SALE",NA
33,23780958,1002398D,SMC FOOD21 (MALAYSIA) SDN. BHD.,SMC FOOD,USD,3.66e+06,1.64e+07,4.48,NA,TB,107XX,MANUFACTURING,MANUFACTURE OF OTHER FOOD PRODUCTS,NA
43,12911187,593768K,ENRICH MIX SDN BHD,SMC FOOD,USD,8.90e+05,3.98e+06,4.48,NA,TB,1050X,MANUFACTURING,MANUFACTURE OF DAIRY PRODUCTS,NA
2,14615137,15631P,SIME DARBY PROPERTY BERHAD,SIME DARBY PROPERTY,GBP,8.82e+07,4.60e+08,5.21,NA,STRC,41001B,CONSTRUCTION,"DEVELOPER - LANDED RESIDENTIAL UNITS (E.G. LINK, SEMI-D & DETACHED HOUSES) FOR SALE",NA
7,15499781,647766V,SIME DARBY PLANTATION BERHAD,SIME DARBY PLANTATION,USD,6.50e+07,2.91e+08,4.48,NA,STRC,01261B,"AGRICULTURE, FORESTRY AND FISHING","GROWING OF OIL PALM WITH PLANTATION ESTATES OF 1,000 TO 10,000 HECTARES",NA
0,15499781,647766V,SIME DARBY PLANTATION BERHAD,SIME DARBY PLANTATION,USD,2.30e+08,1.03e+09,4.48,NA,TL,01261B,"AGRICULTURE, FORESTRY AND FISHING","GROWING OF OIL PALM WITH PLANTATION ESTATES OF 1,000 TO 10,000 HECTARES",NA
23,4203534,191854P,RAMATEX TEXTILES INDUSTRIAL SDN. BHD.,RAMATEX,USD,1.15e+07,5.14e+07,4.48,NA,TB,13XXX,MANUFACTURING,MANUFACTURE OF TEXTILES,NA
12,17393797,8338,QATAR ISLAMIC BANK Q.P.S.C,QATAR ISLAMIC BANK,USD,3.00e+07,1.34e+08,4.48,NA,TL,64192,FINANCIAL AND INSURANCE/ TAKAFUL ACTIVITIES,ISLAMIC BANKS,NA
11,19531303,918822X,PRESS METAL BINTULU SDN. BHD.,PRESS METAL,USD,3.23e+07,1.45e+08,4.48,NA,TB,24202,MANUFACTURING,PRODUCTION OF ALUMINIUM FROM ALUMINA,NA
4,24871000,1198171H,PRESS METAL ALUMINIUM HOLDINGS BERHAD,PRESS METAL,USD,8.68e+07,3.88e+08,4.48,NA,TL,24202,MANUFACTURING,PRODUCTION OF ALUMINIUM FROM ALUMINA,NA
16,7617531,8700M,TIONG HUAT RUBBER FACTORY SDN BHD,OIB/TIONG HUAT,USD,2.61e+07,1.17e+08,4.48,NA,TB,22XXXF,MANUFACTURING,MANUFACTURE OF OTHER RUBBER PRODUCTS N.E.C,NA
5,22276627,FI3MAFRQAQA,MASRAF AL RAYAN (Q.P.S.C.),MASRAF AL RAYAN (Q.P.S.C.),USD,8.00e+07,3.58e+08,4.48,NA,TL,66199,FINANCIAL AND INSURANCE/ TAKAFUL ACTIVITIES,ACTIVITIES AUXILIARY TO FINANCE N.E.C.,NA
10,16444783,587027T,KL-KEPONG OLEOMAS SDN BHD,KLK,USD,3.41e+07,1.52e+08,4.48,NA,TB,10402B,MANUFACTURING,NON-INTEGRATED PLAYER FOR MANUFACTURE OF REFINED PALM OIL,NA
34,25804659,00014460,"KAMPUCHEA FOOD CORPORATION CO., LTD.",JOHOR CORP,USD,3.05e+06,1.37e+07,4.48,NA,STRC,56103,ACCOMMODATION AND FOOD SERVICE ACTIVITIES,FAST-FOOD RESTAURANTS,NA
27,9902624,514587A,JB COCOA SDN BHD,JB FOODS,USD,5.00e+06,2.24e+07,4.48,NA,STRC,107XX,MANUFACTURING,MANUFACTURE OF OTHER FOOD PRODUCTS,NA
28,9902624,514587A,JB COCOA SDN BHD,JB FOODS,USD,4.57e+06,2.05e+07,4.48,NA,TL,107XX,MANUFACTURING,MANUFACTURE OF OTHER FOOD PRODUCTS,NA
20,9902624,514587A,JB COCOA SDN BHD,JB FOODS,USD,1.41e+07,6.32e+07,4.48,NA,TB,107XX,MANUFACTURING,MANUFACTURE OF OTHER FOOD PRODUCTS,NA
21,22797296,199602164M,WS ENGINEERING & FABRICATION PTE. LTD.,IGB,USD,1.41e+07,6.31e+07,4.48,NA,STRC,28299E,MANUFACTURING,MANUFACTURE OF OTHERS SPECIAL PURPOSE MACHINERY N.E.C.,NA
35,11810658,485777W,IFFCO (MALAYSIA) SDN. BHD.,IFFCO,USD,2.52e+06,1.13e+07,4.48,NA,TB,20XXX,MANUFACTURING,MANUFACTURE OF CHEMICALS AND CHEMICAL PRODUCTS,NA
39,9236567,133061V,HEXTAR CHEMICALS SDN BHD,HEXTAR,USD,1.85e+06,8.26e+06,4.48,NA,TB,20XXX,MANUFACTURING,MANUFACTURE OF CHEMICALS AND CHEMICAL PRODUCTS,NA
17,14113618,133057U,GUAN CHONG COCOA MANUFACTURER SDN BHD,GUAN CHONG,USD,1.65e+07,7.38e+07,4.48,NA,STRC,107XX,MANUFACTURING,MANUFACTURE OF OTHER FOOD PRODUCTS,NA
38,11450165,198093M,GCB COCOA MALAYSIA SDN BHD,GUAN CHONG,USD,1.98e+06,8.86e+06,4.48,NA,TB,107XX,MANUFACTURING,MANUFACTURE OF OTHER FOOD PRODUCTS,NA
22,11450165,198093M,GCB COCOA MALAYSIA SDN BHD,GUAN CHONG,USD,1.15e+07,5.15e+07,4.48,NA,STRC,107XX,MANUFACTURING,MANUFACTURE OF OTHER FOOD PRODUCTS,NA
41,11450165,198093M,GCB COCOA MALAYSIA SDN BHD,GUAN CHONG,USD,1.13e+06,5.08e+06,4.48,NA,TL,107XX,MANUFACTURING,MANUFACTURE OF OTHER FOOD PRODUCTS,NA
40,14113618,133057U,GUAN CHONG COCOA MANUFACTURER SDN BHD,GUAN CHONG,USD,1.80e+06,8.07e+06,4.48,NA,TB,107XX,MANUFACTURING,MANUFACTURE OF OTHER FOOD PRODUCTS,NA
25,21855848,100003045,PT FELDA INDO RUBBER,FELDA,USD,6.25e+06,2.80e+07,4.48,NA,STRC,22XXXF,MANUFACTURING,MANUFACTURE OF OTHER RUBBER PRODUCTS N.E.C,NA
1,19492758,420003M,TRURICH RESOURCES SDN BHD,FELDA,USD,2.01e+08,8.98e+08,4.48,NA,TL,01261A,"AGRICULTURE, FORESTRY AND FISHING","GROWING OF OIL PALM WITH PLANTATION ESTATES > 10,000 HECTARES",NA
19,19710441,920555W,FGV IFFCO TRADING SDN BHD,FELDA,USD,1.49e+07,6.67e+07,4.48,NA,TB,462XXA,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VEHICLES AND MOTORCYCLES,WHOLESALE OF PALM OIL,NA
8,4073287,25952H,FGV FERTILISER SDN. BHD.,FELDA,USD,5.66e+07,2.53e+08,4.48,NA,TB,3290X,MANUFACTURING,OTHER MANUFACTURING N.E.C.,NA
31,12932286,217120W,EVERGREEN FIBREBOARD BERHAD,EVERGREEN FIBREBOARD,USD,3.71e+06,1.66e+07,4.48,NA,TL,16XXX,MANUFACTURING,"MANUFACTURE OF WOOD AND PRODUCTS OF WOOD AND CORK, EXCEPT FURNITURE; MANUFACTURE OF ARTICLES OF STRAW AND PLAITING MATERIALS",NA
13,17418644,FI3CBDUAEAD,COMMERCIAL BANK OF DUBAI P.S.C.,COMMERCIAL BANK OF DUBAI,USD,3.00e+07,1.34e+08,4.48,NA,TL,64191,FINANCIAL AND INSURANCE/ TAKAFUL ACTIVITIES,COMMERCIAL BANKS,NA
15,21944325,1402C,PT BERKALA MAJU BERSAMA,CBIP,USD,2.65e+07,1.19e+08,4.48,NA,TL,01261B,"AGRICULTURE, FORESTRY AND FISHING","GROWING OF OIL PALM WITH PLANTATION ESTATES OF 1,000 TO 10,000 HECTARES",NA
9,20035807,FI3BBYNKWKW,"BOUBYAN BANK KSC, SAFAT, KUWAIT",BOUBYAN BANK K.S.C.,USD,5.00e+07,2.24e+08,4.48,NA,TL,66199,FINANCIAL AND INSURANCE/ TAKAFUL ACTIVITIES,ACTIVITIES AUXILIARY TO FINANCE N.E.C.,NA
6,20647650,610324716323,PT ICHTIAR GUSTI PUDI,AZRB,USD,7.62e+07,3.41e+08,4.48,NA,TL,01261B,"AGRICULTURE, FORESTRY AND FISHING","GROWING OF OIL PALM WITH PLANTATION ESTATES OF 1,000 TO 10,000 HECTARES",NA
36,20647650,610324716323,PT ICHTIAR GUSTI PUDI,AZRB,USD,2.50e+06,1.12e+07,4.48,NA,STRC,01261B,"AGRICULTURE, FORESTRY AND FISHING","GROWING OF OIL PALM WITH PLANTATION ESTATES OF 1,000 TO 10,000 HECTARES",NA
46,7555477,164093X,ANSHIN STEEL SERVICE CENTRE SDN BHD,ANN JOO,USD,4.39e+05,1.96e+06,4.48,NA,TB,2410XB,MANUFACTURING,MANUFACTURE OF STEEL,NA

In [19]:
working = pd.read_excel(r'T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\06_BNM Request\2022-06\working FCY Jun22.xlsx', header=7)
working.columns = working.columns.str.upper()
working.columns = working.columns.str.replace(" ","_")

In [22]:
test = working.merge(FCY1.rename(columns={'GCIF_NO':'M_CUS_NO'}), on='M_CUS_NO', how='outer', indicator=True)
test._merge.value_counts()

both          80
left_only      1
right_only     0
Name: _merge, dtype: int64

In [23]:
test.iloc[np.where(test._merge=='left_only')]

,M_CUS_NO,M_NEW_ID_NUMBER,NAME,_CB_GROUP_NAME,ISO_CURRENCY_CD,FACILITY_2,M_MSIC_CODE,SUM_OF_CUR_BOOK_BAL_SUM,SUM_OF_M_BNM_BALANCE_SUM,BRIC,CUSTOMER_NAME,CUSTOMER_GROUP,FINANCING_CURRENCY,FCY,RM,FX,ACOUNT_CLASSIFICATION,FINANCING_TYPE,INDUSTRIAL_SECTOR_CODE,INDUSTRIAL_SECTOR,INDUSTRIAL_SECTOR_DESCRIPTION,BRR,_merge
80,Grand Total,NaN,NaN,NaN,NaN,NaN,NaN,1.27e+09,5.75e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [20]:
working

,M_CUS_NO,M_NEW_ID_NUMBER,NAME,_CB_GROUP_NAME,ISO_CURRENCY_CD,FACILITY_2,M_MSIC_CODE,SUM_OF_CUR_BOOK_BAL_SUM,SUM_OF_M_BNM_BALANCE_SUM
0,15499781,647766V,SIME DARBY PLANTATION BERHAD,SIME DARBY PLANTATION,USD,STRC,01261B,3.50e+07,1.54e+08
1,15499781,647766V,SIME DARBY PLANTATION BERHAD,SIME DARBY PLANTATION,USD,TL,01261B,2.30e+08,1.01e+09
2,19492758,420003M,TRURICH RESOURCES SDN BHD,FELDA,USD,TL,01261A,1.98e+08,8.73e+08
3,14615137,15631P,SIME DARBY PROPERTY BERHAD,SIME DARBY PROPERTY,GBP,STRC,41001B,8.82e+07,4.72e+08
4,11852516,19698X,S P SETIA BERHAD,SP SETIA,GBP,TL,41001B,7.94e+07,4.25e+08
5,24871000,1198171H,PRESS METAL ALUMINIUM HOLDINGS BERHAD,PRESS METAL,USD,TL,24202,9.24e+07,4.07e+08
6,20647650,610324716323,PT ICHTIAR GUSTI PUDI,AZRB,USD,STRC,01261B,1.25e+07,5.51e+07
7,20647650,610324716323,PT ICHTIAR GUSTI PUDI,AZRB,USD,TL,01261B,7.62e+07,3.36e+08
8,22276627,FI3MAFRQAQA,MASRAF AL RAYAN (Q.P.S.C.),MASRAF AL RAYAN (Q.P.S.C.),USD,TL,66199,8.00e+07,3.53e+08
9,20035807,FI3BBYNKWKW,"BOUBYAN BANK KSC, SAFAT, KUWAIT",BOUBYAN BANK K.S.C.,USD,TL,66199,5.00e+07,2.20e+08
10,27697114,2020DU0001,SHARJAH ELECTRICITY WATER AND GAS AUTHOR,GOVERNMENT OF UNITED ARAB EMIRATES,USD,TL,3510XB,3.02e+07,1.33e+08
11,17393797,8338,QATAR ISLAMIC BANK DOHA,QATAR ISLAMIC BANK,USD,TL,64192,3.00e+07,1.32e+08
12,7617531,8700M,TIONG HUAT RUBBER FACTORY SDN BHD,OIB/TIONG HUAT,USD,TB,22XXXF,2.71e+07,1.20e+08
13,25167406,1240905H,SUMBER RIBU SDN. BHD.,VELESTO,USD,STRC,64200,2.69e+07,1.19e+08
14,21944325,1402C,PT BERKALA MAJU BERSAMA,CBIP,USD,TL,01261B,2.68e+07,1.18e+08
15,14113618,133057U,GUAN CHONG COCOA MANUFACTURER SDN BHD,GUAN CHONG,GBP,TB,107XX,9.74e+05,5.21e+06
16,14113618,133057U,GUAN CHONG COCOA MANUFACTURER SDN BHD,GUAN CHONG,USD,STRC,107XX,1.99e+07,8.78e+07
17,14113618,133057U,GUAN CHONG COCOA MANUFACTURER SDN BHD,GUAN CHONG,USD,TB,107XX,1.90e+06,8.37e+06
18,9902624,514587A,JB COCOA SDN BHD,JB FOODS,USD,STRC,107XX,5.00e+06,2.20e+07
19,9902624,514587A,JB COCOA SDN BHD,JB FOODS,USD,TB,107XX,1.30e+07,5.75e+07
20,9902624,514587A,JB COCOA SDN BHD,JB FOODS,USD,TL,107XX,4.69e+06,2.07e+07
21,4073287,25952H,FGV FERTILISER SDN. BHD.,FELDA,USD,TB,3290X,1.98e+07,8.72e+07
22,21775114,1042951D,YE CHIU NON-FERROUS METAL (M) SDN. BHD.,YE CHIU,USD,TL,24209B,1.67e+07,7.35e+07
23,11450165,198093M,GCB COCOA MALAYSIA SDN BHD,GUAN CHONG,USD,STRC,107XX,1.20e+07,5.28e+07
24,11450165,198093M,GCB COCOA MALAYSIA SDN BHD,GUAN CHONG,USD,TB,107XX,2.64e+06,1.16e+07
25,11450165,198093M,GCB COCOA MALAYSIA SDN BHD,GUAN CHONG,USD,TL,107XX,1.27e+06,5.59e+06
26,4203534,191854P,RAMATEX TEXTILES INDUSTRIAL SDN. BHD.,RAMATEX,USD,TB,13XXX,1.01e+07,4.44e+07
27,19710441,920555W,FGV IFFCO TRADING SDN BHD,FELDA,USD,TB,462XXA,9.74e+06,4.29e+07
28,22797296,199602164M,WS ENGINEERING & FABRICATION PTE. LTD.,IGB,USD,STRC,28299E,9.10e+06,4.01e+07
29,22797296,199602164M,WS ENGINEERING & FABRICATION PTE. LTD.,IGB,USD,TB,28299E,1.11e+05,4.91e+05
30,20864429,702463P,SUNRISE ICON SDN BHD,TECK GUAN,USD,STRC,10402A,7.49e+06,3.30e+07
31,20864429,702463P,SUNRISE ICON SDN BHD,TECK GUAN,USD,TL,10402A,8.28e+05,3.65e+06
32,7358732,88160P,V.S INDUSTRY BERHAD,VS INDUSTRY,USD,TB,22XXXG,2.12e+06,9.36e+06
33,7358732,88160P,V.S INDUSTRY BERHAD,VS INDUSTRY,USD,TL,22XXXG,4.50e+06,1.98e+07
34,21855848,100003045,PT FELDA INDO RUBBER,FELDA,USD,STRC,22XXXF,6.25e+06,2.75e+07
35,14824864,311703P,CTRM AERO COMPOSITES SDN. BHD.,TS SYED MOKHTAR (DRB HICOM),GBP,TB,30999A,5.30e+04,2.83e+05
36,14824864,311703P,CTRM AERO COMPOSITES SDN. BHD.,TS SYED MOKHTAR (DRB HICOM),USD,TB,30999A,5.38e+06,2.37e+07
37,3706156,216824X,WHITE HORSE CERAMIC INDUSTRIES SDN BHD,WHITE HORSE,USD,STRC,23XXXC,4.50e+06,1.98e+07
38,16086581,282006D,IDEMITSU SM (MALAYSIA) SDN BHD,PETRONAS,USD,TB,20XXX,4.31e+06,1.90e+07
39,12932286,217120W,EVERGREEN FIBREBOARD BERHAD,EVERGREEN FIBREBOARD,USD,TL,16XXX,3.94e+06,1.74e+07
40,3732193,57450X,KWANTAS OIL SDN. BHD.,KWANTAS,USD,TB,10402A,3.80e+06,1.67e+07
41,23780958,1002398D,SMC FOOD21 (MALAYSIA) SDN. BHD.,SMC FOOD,USD,TB,107XX,3.71e+06,1.63e+07
42,25804659,00014460,"KAMPUCHEA FOOD CORPORATION CO., LTD.",JOHOR CORP,USD,STRC,56103,3.20e+06,1.41e+07
43,23580679,1152825H,UMW AEROSPACE SDN. BHD.,UMWH,USD,TB,28299D,2.62e+06,1.15e+07
44,7314359,200675U,TONG HEER ALUMINIUM INDUSTRIES SDN BHD,TONG HEER RESOURCES,USD,TB,2599X,2.16e+06,9.53e+06
45,11810658,485777W,IFFCO (MALAYSIA) SDN BHD,IFFCO,USD,TB,20XXX,1.50e+06,6.63e+06
46,12911187,593768K,ENRICH MIX SDN BHD,SMC FOOD,USD,TB,1050X,1.37e+06,6.04e+06
47,9236567,133061V,HEXTAR CHEMICALS SDN BHD,HEXTAR,USD,TB,20XXX,7.88e+05,3.47e+06
48,12153815,499486U,MARDEC PROCESSING SDN. BHD.,TS SYED MOKHTAR (MARDEC),USD,TB,22XXXF,5.24e+05,2.31e+06
49,7555477,164093X,ANSHIN STEEL SERVICE CENTRE SDN BHD,ANN JOO,USD,TB,2410XB,4.39e+05,1.93e+06
50,Grand Total,NaN,NaN,NaN,NaN,NaN,NaN,1.27e+09,5.75e+09

In [146]:
FCYb.iloc[np.where(FCYb.M_MSIC_CODE.isna())]

,M_CUS_NO,NAME,CB_GROUP_NAME,ISO_CURRENCY_CD,FACILITY_2,CUR_BOOK_BAL_SUM,M_BNM_BALANCE_SUM_1,FX,M_NEW_ID_NUMBER,M_MSIC_CODE,INDUSTRY_SECTORIAL_CLASSFICATION_DESCRIPTION,ACOUNT_CLASSIFICATION,BRR,ISC_PARENT2,INDUSTRIAL_SECTOR_CODE_(ISC_DESC)2
4,24871000,PRESS METAL ALUMINIUM HOLDINGS BERHAD,PRESS METAL,USD,TL,9.24e+07,4.05e+08,4.38,1198171H,NaN,MANUFACTURING,NA,NA,"AGRICULTURE, FORESTRY AND FISHING",GROWING OF PADDY
5,22276627,MASRAF AL RAYAN (Q.P.S.C.),MASRAF AL RAYAN (Q.P.S.C.),USD,TL,8.00e+07,3.50e+08,4.38,FI3MAFRQAQA,NaN,FINANCIAL AND INSURANCE'/TAKAFUL ACTIVITIES,NA,NA,"AGRICULTURE, FORESTRY AND FISHING",GROWING OF PADDY
7,20035807,"BOUBYAN BANK KSC, SAFAT, KUWAIT",BOUBYAN BANK K.S.C.,USD,TL,5.00e+07,2.19e+08,4.38,FI3BBYNKWKW,NaN,FINANCIAL AND INSURANCE'/TAKAFUL ACTIVITIES,NA,NA,"AGRICULTURE, FORESTRY AND FISHING",GROWING OF PADDY
9,19531303,PRESS METAL BINTULU SDN. BHD.,PRESS METAL,USD,TB,4.15e+07,1.82e+08,4.38,918822X,NaN,MANUFACTURING,NA,NA,"AGRICULTURE, FORESTRY AND FISHING",GROWING OF PADDY
11,17393797,QATAR ISLAMIC BANK DOHA,QATAR ISLAMIC BANK,USD,TL,3.01e+07,1.32e+08,4.38,8338,NaN,FINANCIAL AND INSURANCE'/TAKAFUL ACTIVITIES,NA,NA,"AGRICULTURE, FORESTRY AND FISHING",GROWING OF PADDY
36,25804659,"KAMPUCHEA FOOD CORPORATION CO., LTD.",JOHOR CORP,USD,STRC,3.20e+06,1.40e+07,4.38,00014460,NaN,ACCOMMODATION AND FOOD SERVICE ACTIVITIES,NA,NA,"AGRICULTURE, FORESTRY AND FISHING",GROWING OF PADDY

In [5]:
a = FCY.iloc[np.where(FCY.NAME=='QATAR ISLAMIC BANK DOHA')]
a

,M_CUS_NO,NAME,CB_GROUP_NAME,ISO_CURRENCY_CD,FACILITY_2,CUR_BOOK_BAL_SUM,M_BNM_BALANCE_SUM_1,FX,M_NEW_ID_NUMBER,M_MSIC_CODE,INDUSTRY_SECTORIAL_CLASSFICATION_DESCRIPTION,ACOUNT_CLASSIFICATION,BRR
11,17393797,QATAR ISLAMIC BANK DOHA,QATAR ISLAMIC BANK,USD,TL,3.01e+07,1.32e+08,4.38,8338,64192,Financial and Insurance'/Takaful Activities,NA,NA

In [94]:
a = FXCurrency.iloc[np.where(FXCurrency.NAME=='MASRAF AL RAYAN (Q.P.S.C.)')]

In [13]:
FCY.iloc[np.where(FCY.M_MSIC_CODE=='66199')]

,M_CUS_NO,NAME,CB_GROUP_NAME,ISO_CURRENCY_CD,FACILITY_2,CUR_BOOK_BAL_SUM,M_BNM_BALANCE_SUM_1,FX,M_NEW_ID_NUMBER,M_MSIC_CODE,INDUSTRY_SECTORIAL_CLASSFICATION_DESCRIPTION,ACOUNT_CLASSIFICATION,BRR
5,22276627,MASRAF AL RAYAN (Q.P.S.C.),MASRAF AL RAYAN (Q.P.S.C.),USD,TL,8.00e+07,3.50e+08,4.38,FI3MAFRQAQA,66199,Financial and Insurance'/Takaful Activities,NA,NA
7,20035807,"BOUBYAN BANK KSC, SAFAT, KUWAIT",BOUBYAN BANK K.S.C.,USD,TL,5.00e+07,2.19e+08,4.38,FI3BBYNKWKW,66199,Financial and Insurance'/Takaful Activities,NA,NA

In [12]:
description.iloc[np.where(description.ISC_NOB=='66199')]

,ISC_NOB,ISC_PARENT,ISC_PARENT2,INDUSTRIAL_SECTOR_CODE_(ISC_DESC),INDUSTRIAL_SECTOR_CODE_(ISC_DESC)2
347,66199,11. FINANCIAL AND INSURANCE/ TAKAFUL ACTIVITIES,FINANCIAL AND INSURANCE/ TAKAFUL ACTIVITIES,Activities auxiliary to finance n.e.c.,ACTIVITIES AUXILIARY TO FINANCE N.E.C.