In [35]:
import numpy as np
import pandas as pd
import pandasql
import sqlite3

pd.set_option("display.max_columns", None) 
pd.set_option("display.max_colwidth", 1000) #huruf dlm column
pd.set_option("display.max_rows", 100)
pd.set_option("display.precision", 2) #2 titik perpuluhan

#D = 'Jun 2021'
#D1 = 'Jul 2021'
#D2 = 'Aug 2021'
#D3 = 'Sep 2021'
#D4 = 'Oct 2021'
#D5 = 'Nov 2021'
#D6 = 'Dec 2021'
#D7 = 'Jan 2022'
#D8 = 'Feb 2022'
#D9 = 'Mar 2022'
#D10 = 'Apr 2022'
#D11 = 'May 2022'
#D12 = 'Jun 2022'
D12 = 'Jun 2022' #tukar kat sini

BB12 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D12+"\MGS BB Template "+D12+".xlsx",sheet_name='FINAL_TEMPLATE', header=2)
BBHP12 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D12+"\MGS Template "+D12[:3]+"'"+D12[-2:]+"_BBHP.xlsx",sheet_name='FINAL_TEMPLATE', header=2)
SME12 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D12+"\MGS Template "+D12[:3]+"'"+D12[-2:]+"_SME.xlsx",sheet_name='FINAL_TEMPLATE', header=2)
GB12 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D12+"\MGSL_Template_FINAL_GB_"+D12[:3]+" "+D12[-2:]+".xlsm",sheet_name='FINAL_TEMPLATE', header=2)

#rpsia fikri track deposit skali
#RPSIA = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\17_Sustainability_ESG high risk sectors\20220331\RPSIA Fikri\RPSIA_Mar22.xlsx", sheet_name='Sheet1')
RPSIA = pd.read_excel(r"D:\Users\80005701\Documents\MGSL\RPSIA_202206(python).xlsx")

#cross cek rating
CB = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\18_Rating_CBBBRSME\BRR_CBBBRSME_202206(python).xlsx")

BB12.columns = BB12.columns.str.upper()
BB12.columns = BB12.columns.str.strip()
BB12.columns = BB12.columns.str.replace("\n","").str.replace(" ","_")

BBHP12.columns = BBHP12.columns.str.upper()
BBHP12.columns = BBHP12.columns.str.strip()
BBHP12.columns = BBHP12.columns.str.replace("\n","").str.replace(" ","_")

SME12.columns = SME12.columns.str.upper()
SME12.columns = SME12.columns.str.strip()
SME12.columns = SME12.columns.str.replace("\n","").str.replace(" ","_")

GB12.columns = GB12.columns.str.upper()
GB12.columns = GB12.columns.str.strip()
GB12.columns = GB12.columns.str.replace("\n","").str.replace(" ","_")




BB12['GROUP_NAME'] = ''
BB12_1=BB12[["COUNTRY_TYPE","COUNTRY/SECTOR","LOANS/FIS","TYPE_OF_MGSL","GCIF","NAME_OF_BORROWER/ISSUER","BRR(CURRENT)","ENTITY_(IMPORTANT:_MUST_KEY-IN)","STATUS_OF_ACCOUNT(IMPORTANT:_MUST_KEY-IN)","LIMIT_(RM_'MIL)","ACTUAL_OUTSTANDING_AS_AT_MONTH_END_(RM_'MIL)","STAGE_(IMPORTANT:_MUST_KEY-IN)","TYPE_OF_LIMIT_(1)(IMPORTANT:_MUST_KEY-IN)",'FACILITY_TYPE','GROUP_NAME']]

BBHP12_1=BBHP12[["COUNTRY_TYPE","COUNTRY/SECTOR","LOANS/FIS","TYPE_OF_MGSL","GCIF","NAME_OF_BORROWER/ISSUER","BRR(CURRENT)","ENTITY_(IMPORTANT:_MUST_KEY-IN)","STATUS_OF_ACCOUNT(IMPORTANT:_MUST_KEY-IN)","LIMIT_(RM_'MIL)","ACTUAL_OUTSTANDING_AS_AT_MONTH_END_(RM_'MIL)","STAGE_(IMPORTANT:_MUST_KEY-IN)","TYPE_OF_LIMIT_(1)(IMPORTANT:_MUST_KEY-IN)",'FACILITY_TYPE','GROUP_NAME']]

SME12['GROUP_NAME'] = ''
SME12_1=SME12[["COUNTRY_TYPE","COUNTRY/SECTOR","LOANS/FIS","TYPE_OF_MGSL","GCIF","NAME_OF_BORROWER/ISSUER","BRR(CURRENT)","ENTITY_(IMPORTANT:_MUST_KEY-IN)","STATUS_OF_ACCOUNT(IMPORTANT:_MUST_KEY-IN)","LIMIT_(RM_'MIL)","ACTUAL_OUTSTANDING_AS_AT_MONTH_END_(RM_'MIL)","STAGE_(IMPORTANT:_MUST_KEY-IN)","TYPE_OF_LIMIT_(1)(IMPORTANT:_MUST_KEY-IN)",'FACILITY_TYPE','GROUP_NAME']]

GB12_1=GB12[["COUNTRY_TYPE","COUNTRY/SECTOR","LOANS/FIS","TYPE_OF_MGSL","GCIF","NAME_OF_BORROWER/ISSUER","BRR(CURRENT)","ENTITY_(IMPORTANT:_MUST_KEY-IN)","STATUS_OF_ACCOUNT(CURRENT)","LIMIT_(RM_'MIL)","ACTUAL_OUTSTANDING_AS_AT_MONTH_END_(RM_'MIL)","STAGE_(IMPORTANT:_MUST_KEY-IN)","TYPE_OF_LIMIT_(1)(IMPORTANT:_MUST_KEY-IN)",'FACILITY_TYPE','GROUP_NAME']].rename(columns={'STATUS_OF_ACCOUNT_(CURRENT)':'STATUS_OF_ACCOUNT_(IMPORTANT:_MUST_KEY-IN)'})


DF12 = pd.concat([BB12_1,BBHP12_1,SME12_1,GB12_1], axis=0, ignore_index=True)

DF12_1 = DF12.iloc[np.where((DF12["COUNTRY_TYPE"]=='Malaysia')&\
                            (DF12['STAGE_(IMPORTANT:_MUST_KEY-IN)'].isin(['Completed / Emplaced','Approved by Sectoral Limit Controller','Facilities Pending Emplacement','Approved by Management & Pending Acceptance','Approved by Management / Amount Enforced','Partial Release','Pre-approved Line'])))]

DF12_1['STATUS_OF_ACCOUNT(CURRENT)'].fillna(DF12_1['STATUS_OF_ACCOUNT(IMPORTANT:_MUST_KEY-IN)'],inplace=True)

DF12_1.loc[(DF12_1['LOANS/FIS']=='FIS'),"ACTUAL_OUTSTANDING_AS_AT_MONTH_END_(RM_'MIL)"] = DF12_1["LIMIT_(RM_'MIL)"]



RPSIA1 = RPSIA.rename(columns={'CUSTOMER_ID':'GCIF'})#.fillna(0).groupby(['GCIF']).sum().reset_index() #[['Outstanding']]

RPSIA1.GCIF = RPSIA1.GCIF.astype(str)
RPSIA1.GCIF = RPSIA1.GCIF.str.strip()
RPSIA1.GCIF = RPSIA1.GCIF.str.upper()

DF12_1.GCIF = DF12_1.GCIF.astype(str)
DF12_1.GCIF = DF12_1.GCIF.str.strip()
DF12_1.GCIF = DF12_1.GCIF.str.upper()

merge_a = DF12_1.merge(RPSIA1[['GCIF']], on='GCIF', how='left', indicator=True)


merge_a.loc[merge_a['STATUS_OF_ACCOUNT(CURRENT)'].isin(['Good / Normal','EWS']), 'MFRS9'] = 'Stage 1'
merge_a.loc[merge_a['STATUS_OF_ACCOUNT(CURRENT)'].isin(['SMA','WL','Watchlist','NCWL']), 'MFRS9'] = 'Stage 2'
merge_a.loc[merge_a['STATUS_OF_ACCOUNT(CURRENT)'].isin(['Impaired Non-Performing Loans','Impaired Performing Loans','GIL']), 'MFRS9'] = 'Stage 3'
merge_a.loc[merge_a['MFRS9'].isna(), 'MFRS9'] = 'Unrated'


xRP = merge_a.iloc[np.where(merge_a._merge!='both')]





riskcatCBBB = xRP.iloc[np.where(xRP['COUNTRY/SECTOR'].isin(['GB','BB']))]

riskcatCBBB['BRR(CURRENT)'].fillna(-9999,inplace=True)
riskcatCBBB.loc[riskcatCBBB['BRR(CURRENT)']=="Unrated",'BRR(CURRENT)'] = -9999
riskcatCBBB.loc[riskcatCBBB['BRR(CURRENT)']=="NA",'BRR(CURRENT)'] = -9999
riskcatCBBB.loc[riskcatCBBB['BRR(CURRENT)']=="PF (2-GD)",'BRR(CURRENT)'] = -9999 #case jun 21

riskcatCBBB['BRR(CURRENT)'] = riskcatCBBB['BRR(CURRENT)'].astype(int)

riskcatCBBB.GCIF = riskcatCBBB.GCIF.astype(str)
riskcatCBBB.GCIF = riskcatCBBB.GCIF.str.strip()
riskcatCBBB.GCIF = riskcatCBBB.GCIF.str.upper()

CB.M_CUS_NO = CB.M_CUS_NO.astype(str)
CB.M_CUS_NO = CB.M_CUS_NO.str.strip()
CB.M_CUS_NO = CB.M_CUS_NO.str.upper()

CB1 = CB[['M_CUS_NO','FINAL_RATING']].rename(columns={'M_CUS_NO':'GCIF'})

riskcatCBBB = riskcatCBBB.merge(CB1, on='GCIF', how='left', indicator='exist')

riskcatCBBB.loc[(riskcatCBBB.exist=='both')&(riskcatCBBB['BRR(CURRENT)']==-9999),'BRR(CURRENT)'] = a.FINAL_RATING

riskcatCBBB['BRR(CURRENT)'] = riskcatCBBB['BRR(CURRENT)'].astype(int)

#a.iloc[np.where((a.exist=='both')&(a['BRR(CURRENT)']==-9999))] cek list yg wong xde tp kita ad rating


def RISKCD(x):
    if x >= 1 and x<= 5:
        return '01.Very Low Risk'
    elif x >= 6 and x <= 10:
        return '02.Low Risk'
    elif x >= 11 and x <= 15:
        return '03.Moderate Risk'
    elif x >= 16 and x <= 21:
        return '04.High Risk'
    elif x >= 22 and x <= 23:
        return '05.Sub Standard'
    else:
        return '06.Unrated'
    
riskcatCBBB['RISK_CATEGORY'] = riskcatCBBB['BRR(CURRENT)'].apply(RISKCD)

riskcatSME = xRP.iloc[np.where(xRP['COUNTRY/SECTOR']=='SME')]


def RATING(x):
    if x=='R1':
        return '01. R1'
    elif x=='R2':
        return '02. R2'
    elif x=='R3':
        return '03. R3'
    elif x=='R4':
        return '04. R4'
    elif x=='R5':
        return '05. R5'
    elif x=='R6':
        return '06. R6'
    elif x=='R7':
        return '07. R7'
    elif x=='R8':
        return '08. R8'
    elif x=='R9':
        return '09. R9'
    elif x=='R10':
        return '10. R10'
    elif x=='R11':
        return '11. R11'
    else: 
        return '13. Unrated'
    
def RCAT(x):
    if x == '01. R1':
        return '01. Very Low(1-2)'
    elif x == '02. R2':
        return '01. Very Low(1-2)'
    elif x == '03. R3':
        return '02. Low(3-4)'
    elif x == '04. R4':
        return '02. Low(3-4)'
    elif x == '05. R5':
        return '03. Moderate(5-8)'
    elif x == '06. R6':
        return '03. Moderate(5-8)' 
    elif x == '07. R7':
        return '03. Moderate(5-8)' 
    elif x == '08. R8':
        return '03. Moderate(5-8)'
    elif x == '09. R9':
        return '04. High(9-11)'
    elif x == '10. R10':
        return '04. High(9-11)'
    elif x == '11. R11':
        return '04. High(9-11)'
    elif x == 'IF':
        return '05. IF'
    else:
        return '06. Unrated'

riskcatSME['RATING'] = riskcatSME['BRR(CURRENT)'].apply(RATING)
riskcatSME['RISK_CATEGORY'] = riskcatSME['RATING'].apply(RCAT)



allmerge = pd.concat([riskcatCBBB.drop(['FINAL_RATING', 'exist'], axis=1) ,riskcatSME.drop(['RATING'], axis=1) ], axis=0, ignore_index=True)

writer2 = pd.ExcelWriter(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D12+"\MGSL_"+D12+"(python).xlsx", engine='xlsxwriter')

#merge_a.to_excel(writer2, sheet_name='MGS with RPSIA', index = False)
allmerge.to_excel(writer2, sheet_name='MGS no RPSIA', index = False)
riskcatCBBB.to_excel(writer2, sheet_name='rating CB BB no RPSIA', index = False)
riskcatSME.to_excel(writer2, sheet_name='rating sme no RPSIA', index = False)

writer2.save()

D:\anaconda3\lib\site-packages\pandas\core\generic.py:6245: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)
D:\anaconda3\lib\site-packages\pandas\core\indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s
D:\anaconda3\lib\site-packages\pandas\core\generic.py:5303: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [ ]:
riskcatSME.head(1)

In [ ]:
xRP_final1 = xRP.merge(riskcatSME[['GCIF','RISK_CATEGORY']].drop_duplicates('GCIF'),on='GCIF',how='left',suffixes=('', '_SME'))
xRP_final = xRP_final1.merge(riskcatCBBB[['GCIF','RISK_CATEGORY']].drop_duplicates('GCIF'),on='GCIF',how='left',suffixes=('', '_CBBB'))

In [ ]:
xRP.shape

In [ ]:
a= xRP_final.iloc[np.where(xRP_final['COUNTRY/SECTOR']=='SME')]
a.RISK_CATEGORY_CBBB.value_counts()

In [ ]:
a= xRP_final.iloc[np.where(xRP_final.RISK_CATEGORY_CBBB=='SME')]
a.RISK_CATEGORY_CBBB.value_counts()

In [ ]:
merge_a.to_excel(r"T:\MIB Risk Management\CRM\10.0_MGS Sectoral\Syahid\MGSL june - working.xlsx", index=False)

# GB

In [ ]:
c1 = DF12_1.iloc[np.where((DF12_1['ENTITY_(IMPORTANT:_MUST_KEY-IN)']!='Islamic')&(DF12_1["LOANS/FIS"]=='Loans')&(DF12_1["COUNTRY/SECTOR"]=='GB'))].fillna(0).groupby(['TYPE_OF_MGSL'])[["LIMIT_(RM_'MIL)","ACTUAL_OUTSTANDING_AS_AT_MONTH_END_(RM_'MIL)"]].sum().reset_index().sort_values(by='TYPE_OF_MGSL',ascending=False)
c1
#,'COUNTRY/SECTOR','LOANS/FIS'

In [ ]:
c2 = DF12_1.iloc[np.where((DF12_1['ENTITY_(IMPORTANT:_MUST_KEY-IN)']!='Islamic')&(DF12_1["LOANS/FIS"]!='Loans')&(DF12_1["COUNTRY/SECTOR"]=='GB'))].fillna(0).groupby(['TYPE_OF_MGSL'])[["LIMIT_(RM_'MIL)","ACTUAL_OUTSTANDING_AS_AT_MONTH_END_(RM_'MIL)"]].sum().reset_index().sort_values(by='TYPE_OF_MGSL',ascending=False)
c2
#,'COUNTRY/SECTOR','LOANS/FIS'

In [ ]:
i1 = DF12_1.iloc[np.where((DF12_1['ENTITY_(IMPORTANT:_MUST_KEY-IN)']=='Islamic')&(DF12_1["LOANS/FIS"]=='Loans')&(DF12_1["COUNTRY/SECTOR"]=='GB'))].fillna(0).groupby(['TYPE_OF_MGSL'])[["LIMIT_(RM_'MIL)","ACTUAL_OUTSTANDING_AS_AT_MONTH_END_(RM_'MIL)"]].sum().reset_index().sort_values(by='TYPE_OF_MGSL',ascending=False)
i1
#,'COUNTRY/SECTOR','LOANS/FIS'

In [ ]:
i2 = DF12_1.iloc[np.where((DF12_1['ENTITY_(IMPORTANT:_MUST_KEY-IN)']=='Islamic')&(DF12_1["LOANS/FIS"]!='Loans')&(DF12_1["COUNTRY/SECTOR"]=='GB'))].fillna(0).groupby(['TYPE_OF_MGSL'])[["LIMIT_(RM_'MIL)","ACTUAL_OUTSTANDING_AS_AT_MONTH_END_(RM_'MIL)"]].sum().reset_index().sort_values(by='TYPE_OF_MGSL',ascending=False)
i2
#,'COUNTRY/SECTOR','LOANS/FIS'

# SME

In [ ]:
sme_c1 = DF12_1.iloc[np.where((DF12_1['ENTITY_(IMPORTANT:_MUST_KEY-IN)']!='Islamic')&(DF12_1["LOANS/FIS"]=='Loans')&(DF12_1["COUNTRY/SECTOR"]=='SME'))].fillna(0).groupby(['TYPE_OF_MGSL'])[["LIMIT_(RM_'MIL)","ACTUAL_OUTSTANDING_AS_AT_MONTH_END_(RM_'MIL)"]].sum().reset_index().sort_values(by='TYPE_OF_MGSL',ascending=False)
sme_c1
#,'COUNTRY/SECTOR','LOANS/FIS'

In [ ]:
sme_c2 = DF12_1.iloc[np.where((DF12_1['ENTITY_(IMPORTANT:_MUST_KEY-IN)']!='Islamic')&(DF12_1["LOANS/FIS"]!='Loans')&(DF12_1["COUNTRY/SECTOR"]=='SME'))].fillna(0).groupby(['TYPE_OF_MGSL'])[["LIMIT_(RM_'MIL)","ACTUAL_OUTSTANDING_AS_AT_MONTH_END_(RM_'MIL)"]].sum().reset_index().sort_values(by='TYPE_OF_MGSL',ascending=False)
sme_c2
#,'COUNTRY/SECTOR','LOANS/FIS'

In [ ]:
sme_i1 = DF12_1.iloc[np.where((DF12_1['ENTITY_(IMPORTANT:_MUST_KEY-IN)']=='Islamic')&(DF12_1["LOANS/FIS"]=='Loans')&(DF12_1["COUNTRY/SECTOR"]=='SME'))].fillna(0).groupby(['TYPE_OF_MGSL'])[["LIMIT_(RM_'MIL)","ACTUAL_OUTSTANDING_AS_AT_MONTH_END_(RM_'MIL)"]].sum().reset_index().sort_values(by='TYPE_OF_MGSL',ascending=False)
sme_i1
#,'COUNTRY/SECTOR','LOANS/FIS'

In [ ]:
sme_i2 = DF12_1.iloc[np.where((DF12_1['ENTITY_(IMPORTANT:_MUST_KEY-IN)']=='Islamic')&(DF12_1["LOANS/FIS"]!='Loans')&(DF12_1["COUNTRY/SECTOR"]=='SME'))].fillna(0).groupby(['TYPE_OF_MGSL'])[["LIMIT_(RM_'MIL)","ACTUAL_OUTSTANDING_AS_AT_MONTH_END_(RM_'MIL)"]].sum().reset_index().sort_values(by='TYPE_OF_MGSL',ascending=False)
sme_i2
#,'COUNTRY/SECTOR','LOANS/FIS'

# BB

In [ ]:
bb = DF12_1.iloc[np.where((DF12_1["COUNTRY/SECTOR"]=='BB')&(DF12_1["LOANS/FIS"]=='Loans'))].fillna(0).groupby(['TYPE_OF_MGSL'])[["LIMIT_(RM_'MIL)","ACTUAL_OUTSTANDING_AS_AT_MONTH_END_(RM_'MIL)"]].sum().reset_index()#.sort_values(by='TYPE_OF_MGSL',ascending=False)
bb
#,'COUNTRY/SECTOR','LOANS/FIS'
#(DF12_1['ENTITY_(IMPORTANT:_MUST_KEY-IN)']=='Islamic')&

In [ ]:
merge_a["NAME_OF_BORROWER/ISSUER"].value_counts()

In [ ]:
GB12.GCIF.dtypes, RPSIA1.dtypes

In [ ]:
sum(a["ACTUAL_OUTSTANDING_AS_AT_MONTH_END__(RM_'MIL)"])

In [ ]:
a = GB12.iloc[np.where(GB12.GCIF==20924517)].fillna(0)
a

In [ ]:
a.BORROWER_NAME.value_counts()

In [ ]:
GB12.shape

In [ ]:
D = 'Jun 2021'
D1 = 'Jul 2021'
D2 = 'Aug 2021'
D3 = 'Sep 2021'
D4 = 'Oct 2021'
D5 = 'Nov 2021'
D6 = 'Dec 2021'
D7 = 'Jan 2022'
D8 = 'Feb 2022'
D9 = 'Mar 2022'
D10 = 'Apr 2022'
D11 = 'May 2022'

In [ ]:
BB = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D+"\MGS BB Template "+D+".xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
BBHP = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D+"\MGS Template "+D[:3]+"'"+D[-2:]+"_BBHP.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
SME = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D+"\MGS Template "+D[:3]+"'"+D[-2:]+"_SME.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
GB = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D+"\MGSL_Template_FINAL_GB_"+D[:3]+" "+D[-2:]+".xlsm",sheet_name='SUMMARY_MALAYSIA', header=43)

In [ ]:
BB1 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D1+"\MGS BB Template "+D1+".xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
BBHP1 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D1+"\MGS Template "+D1[:3]+"'"+D1[-2:]+"_BBHP.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
SME1 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D1+"\MGS Template "+D1[:3]+"'"+D1[-2:]+"_SME.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
GB1 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D1+"\MGSL_Template_FINAL_GB_"+D1[:3]+" "+D1[-2:]+".xlsm",sheet_name='SUMMARY_MALAYSIA', header=43)

In [ ]:
BB2 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D2+"\MGS BB Template "+D2+".xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
BBHP2 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D2+"\MGS Template "+D2[:3]+"'"+D2[-2:]+"_BBHP.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
SME2 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D2+"\MGS Template "+D2[:3]+"'"+D2[-2:]+"_SME.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
GB2 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D2+"\MGSL_Template_FINAL_GB_"+D2[:3]+" "+D2[-2:]+".xlsm",sheet_name='SUMMARY_MALAYSIA', header=43)

In [ ]:
BB3 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D3+"\MGS BB Template "+D3+".xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
BBHP3 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D3+"\MGS Template "+D3[:3]+"'"+D3[-2:]+"_BBHP.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
SME3 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D3+"\MGS Template "+D3[:3]+"'"+D3[-2:]+"_SME.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
GB3 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D3+"\MGSL_Template_FINAL_GB_"+D3[:3]+" "+D3[-2:]+".xlsm",sheet_name='SUMMARY_MALAYSIA', header=43)

In [ ]:
BB4 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D4+"\MGS BB Template "+D4+".xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
BBHP4 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D4+"\MGS Template "+D4[:3]+"'"+D4[-2:]+"_BBHP.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
SME4 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D4+"\MGS Template "+D4[:3]+"'"+D4[-2:]+"_SME.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
GB4 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D4+"\MGSL_Template_FINAL_GB_"+D4[:3]+" "+D4[-2:]+".xlsm",sheet_name='SUMMARY_MALAYSIA', header=43)

In [ ]:
BB5 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D5+"\MGS BB Template "+D5+".xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
BBHP5 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D5+"\MGS Template "+D5[:3]+"'"+D5[-2:]+"_BBHP.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
SME5 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D5+"\MGS Template "+D5[:3]+"'"+D5[-2:]+"_SME.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
GB5 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D5+"\MGSL_Template_FINAL_GB_"+D5[:3]+" "+D5[-2:]+".xlsm",sheet_name='SUMMARY_MALAYSIA', header=43)

In [ ]:
BB6 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D6+"\MGS BB Template "+D6+".xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
BBHP6 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D6+"\MGS Template "+D6[:3]+"'"+D6[-2:]+"_BBHP.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
SME6 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D6+"\MGS Template "+D6[:3]+"'"+D6[-2:]+"_SME.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
GB6 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D6+"\MGSL_Template_FINAL_GB_"+D6[:3]+" "+D6[-2:]+".xlsm",sheet_name='SUMMARY_MALAYSIA', header=43)

In [ ]:
BB7 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D7+"\MGS BB Template "+D7+".xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
BBHP7 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D7+"\MGS Template "+D7[:3]+"'"+D7[-2:]+"_BBHP.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
SME7 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D7+"\MGS Template "+D7[:3]+"'"+D7[-2:]+"_SME.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
GB7 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D7+"\MGSL_Template_FINAL_GB_"+D7[:3]+" "+D7[-2:]+".xlsm",sheet_name='SUMMARY_MALAYSIA', header=43)

In [ ]:
BB8 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D8+"\MGS BB Template "+D8+".xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
BBHP8 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D8+"\MGS Template "+D8[:3]+"'"+D8[-2:]+"_BBHP.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
SME8 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D8+"\MGS Template "+D8[:3]+"'"+D8[-2:]+"_SME.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
GB8 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D8+"\MGSL_Template_FINAL_GB_"+D8[:3]+" "+D8[-2:]+".xlsm",sheet_name='SUMMARY_MALAYSIA', header=43)

In [ ]:
BB9 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D9+"\MGS BB Template "+D9+".xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
BBHP9 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D9+"\MGS Template "+D9[:3]+"'"+D9[-2:]+"_BBHP.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
SME9 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D9+"\MGS Template "+D9[:3]+"'"+D9[-2:]+"_SME.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
GB9 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D9+"\MGSL_Template_FINAL_GB_"+D9[:3]+" "+D9[-2:]+".xlsm",sheet_name='SUMMARY_MALAYSIA', header=43)

In [ ]:
BB10 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D10+"\MGS BB Template "+D10+".xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
BBHP10 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D10+"\MGS Template "+D10[:3]+"'"+D10[-2:]+"_BBHP.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
SME10 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D10+"\MGS Template "+D10[:3]+"'"+D10[-2:]+"_SME.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
GB10 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D10+"\MGSL_Template_FINAL_GB_"+D10[:3]+" "+D10[-2:]+".xlsm",sheet_name='SUMMARY_MALAYSIA', header=43)

In [ ]:
BB11 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D11+"\MGS BB Template "+D11+".xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
BBHP11 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D11+"\MGS Template "+D11[:3]+"'"+D11[-2:]+"_BBHP.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
SME11 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D11+"\MGS Template "+D11[:3]+"'"+D11[-2:]+"_SME.xlsx",sheet_name='SUMMARY_MALAYSIA', header=43)
GB11 = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\19_Sectoral MGS\\"+D11+"\MGSL_Template_FINAL_GB_"+D11[:3]+" "+D11[-2:]+".xlsm",sheet_name='SUMMARY_MALAYSIA', header=43)

In [ ]:
t = ['Total', 'Bilateral Loan', 'Bilateral Loan', 'Bilateral Loan', 'Bilateral Loan','Total', 'Fixed Income Secrurities (FIS)', 'Fixed Income Secrurities (FIS)', 'Fixed Income Secrurities (FIS)', 'Fixed Income Secrurities (FIS)','Total']

In [ ]:
#_D

BB1_D = BB[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BB1_D.columns = BB1_D.columns.str.replace("\n", "_")
BB2_D = BB1_D.iloc[np.where(~(BB1_D.Entity.isnull()))]
BB2_D = BB2_D.assign(Entity1=t)
BB2_D['Class'] = 'BB'


BBHP1_D = BBHP[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BBHP1_D.columns = BBHP1_D.columns.str.replace("\n", "_")
BBHP2_D = BBHP1_D.iloc[np.where(~(BBHP1_D.Entity.isnull()))]
BBHP2_D = BBHP2_D.assign(Entity1=t)
BBHP2_D['Class'] = 'BB'


SME1_D = SME[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
SME1_D.columns = SME1_D.columns.str.replace("\n", "_")
SME2_D = SME1_D.iloc[np.where(~(SME1_D.Entity.isnull()))]
SME2_D = SME2_D.assign(Entity1=t)
SME2_D['Class'] = 'SME'


GB1_D = GB[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
GB1_D.columns = GB1_D.columns.str.replace("\n", "_")
GB2_D = GB1_D.iloc[np.where(~(GB1_D.Entity.isnull()))]
GB2_D = GB2_D.assign(Entity1=t)
GB2_D['Class'] = 'CB/GB'


frames_D = [ BB2_D, BBHP2_D, SME2_D, GB2_D] 
MGS_D = pd.concat(frames_D)

MGS1_D = MGS_D.groupby(['Class','Entity1','Entity']).sum().reset_index().sort_values(by=['Entity1'], ascending=[False])

MGS1_D['Total Exposures w/o Bookings'] = MGS1_D["Total Exposure_ (RM 'mil)"]-MGS1_D["Bookings _(RM 'mil)"]

MGS1_D['Date'] = D

MGS1_D.Entity = MGS1_D.Entity.str.strip()

def utilization(Entity):
    if Entity == 'Construction':
        return 31700 
    elif Entity == 'Oil & Gas':
        return 37490 
    elif Entity == 'Oil Palm':
        return 30700
    elif Entity == 'Shipping':
        return 10110
    else:
        return 31700+37490+30700+10110
        
MGS1_D['Limit/Threshold'] = MGS1_D['Entity'].apply(utilization)
MGS1_D['Utilization Exposures w/o bookings'] = MGS1_D['Total Exposures w/o Bookings']/MGS1_D['Limit/Threshold']
MGS1_D['Utilization Exposures'] = MGS1_D["Total Exposure_ (RM 'mil)"]/MGS1_D['Limit/Threshold']

MGS2_D = MGS1_D.iloc[np.where(MGS1_D.Entity1!='Total')].sort_values(by=['Class','Entity1','Entity'],ascending=[True,True,True])

In [ ]:
MGS2_D

In [ ]:
#_D1

BB1_D1 = BB1[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BB1_D1.columns = BB1_D1.columns.str.replace("\n", "_")
BB2_D1 = BB1_D1.iloc[np.where(~(BB1_D1.Entity.isnull()))]
BB2_D1 = BB2_D1.assign(Entity1=t)
BB2_D1['Class'] = 'BB'


BBHP1_D1 = BBHP1[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BBHP1_D1.columns = BBHP1_D1.columns.str.replace("\n", "_")
BBHP2_D1 = BBHP1_D1.iloc[np.where(~(BBHP1_D1.Entity.isnull()))]
BBHP2_D1 = BBHP2_D1.assign(Entity1=t)
BBHP2_D1['Class'] = 'BB'


SME1_D1 = SME1[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
SME1_D1.columns = SME1_D1.columns.str.replace("\n", "_")
SME2_D1 = SME1_D1.iloc[np.where(~(SME1_D1.Entity.isnull()))]
SME2_D1 = SME2_D1.assign(Entity1=t)
SME2_D1['Class'] = 'SME'


GB1_D1 = GB1[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
GB1_D1.columns = GB1_D1.columns.str.replace("\n", "_")
GB2_D1 = GB1_D1.iloc[np.where(~(GB1_D1.Entity.isnull()))]
GB2_D1 = GB2_D1.assign(Entity1=t)
GB2_D1['Class'] = 'CB/GB'


frames_D1 = [ BB2_D1, BBHP2_D1, SME2_D1, GB2_D1] 
MGS_D1 = pd.concat(frames_D1)

MGS1_D1 = MGS_D1.groupby(['Class','Entity1','Entity']).sum().reset_index().sort_values(by=['Entity1'], ascending=[False])

MGS1_D1['Total Exposures w/o Bookings'] = MGS1_D1["Total Exposure_ (RM 'mil)"]-MGS1_D1["Bookings _(RM 'mil)"]

MGS1_D1['D1ate'] = D1

MGS1_D1.Entity = MGS1_D1.Entity.str.strip()

def utilization(Entity):
    if Entity == 'Construction':
        return 31700 
    elif Entity == 'Oil & Gas':
        return 37490 
    elif Entity == 'Oil Palm':
        return 30700
    elif Entity == 'Shipping':
        return 10110
    else:
        return 31700+37490+30700+10110
        
MGS1_D1['Limit/ThresholD1'] = MGS1_D1['Entity'].apply(utilization)
MGS1_D1['Utilization Exposures w/o bookings'] = MGS1_D1['Total Exposures w/o Bookings']/MGS1_D1['Limit/ThresholD1']
MGS1_D1['Utilization Exposures'] = MGS1_D1["Total Exposure_ (RM 'mil)"]/MGS1_D1['Limit/ThresholD1']

MGS2_D1 = MGS1_D1.iloc[np.where(MGS1_D1.Entity1!='Total')].sort_values(by=['Class','Entity1','Entity'],ascending=[True,True,True])

In [ ]:
MGS2_D1

In [ ]:
#_D2

BB1_D2 = BB2[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BB1_D2.columns = BB1_D2.columns.str.replace("\n", "_")
BB2_D2 = BB1_D2.iloc[np.where(~(BB1_D2.Entity.isnull()))]
BB2_D2 = BB2_D2.assign(Entity1=t)
BB2_D2['Class'] = 'BB'


BBHP1_D2 = BBHP2[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BBHP1_D2.columns = BBHP1_D2.columns.str.replace("\n", "_")
BBHP2_D2 = BBHP1_D2.iloc[np.where(~(BBHP1_D2.Entity.isnull()))]
BBHP2_D2 = BBHP2_D2.assign(Entity1=t)
BBHP2_D2['Class'] = 'BB'


SME1_D2 = SME2[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
SME1_D2.columns = SME1_D2.columns.str.replace("\n", "_")
SME2_D2 = SME1_D2.iloc[np.where(~(SME1_D2.Entity.isnull()))]
SME2_D2 = SME2_D2.assign(Entity1=t)
SME2_D2['Class'] = 'SME'


GB1_D2 = GB2[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
GB1_D2.columns = GB1_D2.columns.str.replace("\n", "_")
GB2_D2 = GB1_D2.iloc[np.where(~(GB1_D2.Entity.isnull()))]
GB2_D2 = GB2_D2.assign(Entity1=t)
GB2_D2['Class'] = 'CB/GB'


frames_D2 = [ BB2_D2, BBHP2_D2, SME2_D2, GB2_D2] 
MGS_D2 = pd.concat(frames_D2)

MGS1_D2 = MGS_D2.groupby(['Class','Entity1','Entity']).sum().reset_index().sort_values(by=['Entity1'], ascending=[False])

MGS1_D2['Total Exposures w/o Bookings'] = MGS1_D2["Total Exposure_ (RM 'mil)"]-MGS1_D2["Bookings _(RM 'mil)"]

MGS1_D2['D2ate'] = D2

MGS1_D2.Entity = MGS1_D2.Entity.str.strip()

def utilization(Entity):
    if Entity == 'Construction':
        return 31700 
    elif Entity == 'Oil & Gas':
        return 37490 
    elif Entity == 'Oil Palm':
        return 30700
    elif Entity == 'Shipping':
        return 10110
    else:
        return 31700+37490+30700+10110
        
MGS1_D2['Limit/ThresholD2'] = MGS1_D2['Entity'].apply(utilization)
MGS1_D2['Utilization Exposures w/o bookings'] = MGS1_D2['Total Exposures w/o Bookings']/MGS1_D2['Limit/ThresholD2']
MGS1_D2['Utilization Exposures'] = MGS1_D2["Total Exposure_ (RM 'mil)"]/MGS1_D2['Limit/ThresholD2']

MGS2_D2 = MGS1_D2.iloc[np.where(MGS1_D2.Entity1!='Total')].sort_values(by=['Class','Entity1','Entity'],ascending=[True,True,True])

In [ ]:
MGS2_D2

In [ ]:
#_D3

BB1_D3 = BB3[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BB1_D3.columns = BB1_D3.columns.str.replace("\n", "_")
BB2_D3 = BB1_D3.iloc[np.where(~(BB1_D3.Entity.isnull()))]
BB2_D3 = BB2_D3.assign(Entity1=t)
BB2_D3['Class'] = 'BB'


BBHP1_D3 = BBHP3[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BBHP1_D3.columns = BBHP1_D3.columns.str.replace("\n", "_")
BBHP2_D3 = BBHP1_D3.iloc[np.where(~(BBHP1_D3.Entity.isnull()))]
BBHP2_D3 = BBHP2_D3.assign(Entity1=t)
BBHP2_D3['Class'] = 'BB'


SME1_D3 = SME3[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
SME1_D3.columns = SME1_D3.columns.str.replace("\n", "_")
SME2_D3 = SME1_D3.iloc[np.where(~(SME1_D3.Entity.isnull()))]
SME2_D3 = SME2_D3.assign(Entity1=t)
SME2_D3['Class'] = 'SME'


GB1_D3 = GB3[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
GB1_D3.columns = GB1_D3.columns.str.replace("\n", "_")
GB2_D3 = GB1_D3.iloc[np.where(~(GB1_D3.Entity.isnull()))]
GB2_D3 = GB2_D3.assign(Entity1=t)
GB2_D3['Class'] = 'CB/GB'


frames_D3 = [ BB2_D3, BBHP2_D3, SME2_D3, GB2_D3] 
MGS_D3 = pd.concat(frames_D3)

MGS1_D3 = MGS_D3.groupby(['Class','Entity1','Entity']).sum().reset_index().sort_values(by=['Entity1'], ascending=[False])

MGS1_D3['Total Exposures w/o Bookings'] = MGS1_D3["Total Exposure_ (RM 'mil)"]-MGS1_D3["Bookings _(RM 'mil)"]

MGS1_D3['D3ate'] = D3

MGS1_D3.Entity = MGS1_D3.Entity.str.strip()

def utilization(Entity):
    if Entity == 'Construction':
        return 31700 
    elif Entity == 'Oil & Gas':
        return 37490 
    elif Entity == 'Oil Palm':
        return 30700
    elif Entity == 'Shipping':
        return 10110
    else:
        return 31700+37490+30700+10110
        
MGS1_D3['Limit/ThresholD3'] = MGS1_D3['Entity'].apply(utilization)
MGS1_D3['Utilization Exposures w/o bookings'] = MGS1_D3['Total Exposures w/o Bookings']/MGS1_D3['Limit/ThresholD3']
MGS1_D3['Utilization Exposures'] = MGS1_D3["Total Exposure_ (RM 'mil)"]/MGS1_D3['Limit/ThresholD3']

MGS2_D3 = MGS1_D3.iloc[np.where(MGS1_D3.Entity1!='Total')].sort_values(by=['Class','Entity1','Entity'],ascending=[True,True,True])

In [ ]:
MGS2_D3

In [ ]:
#_D4

BB1_D4 = BB4[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BB1_D4.columns = BB1_D4.columns.str.replace("\n", "_")
BB2_D4 = BB1_D4.iloc[np.where(~(BB1_D4.Entity.isnull()))]
BB2_D4 = BB2_D4.assign(Entity1=t)
BB2_D4['Class'] = 'BB'


BBHP1_D4 = BBHP4[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BBHP1_D4.columns = BBHP1_D4.columns.str.replace("\n", "_")
BBHP2_D4 = BBHP1_D4.iloc[np.where(~(BBHP1_D4.Entity.isnull()))]
BBHP2_D4 = BBHP2_D4.assign(Entity1=t)
BBHP2_D4['Class'] = 'BB'


SME1_D4 = SME4[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
SME1_D4.columns = SME1_D4.columns.str.replace("\n", "_")
SME2_D4 = SME1_D4.iloc[np.where(~(SME1_D4.Entity.isnull()))]
SME2_D4 = SME2_D4.assign(Entity1=t)
SME2_D4['Class'] = 'SME'


GB1_D4 = GB4[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
GB1_D4.columns = GB1_D4.columns.str.replace("\n", "_")
GB2_D4 = GB1_D4.iloc[np.where(~(GB1_D4.Entity.isnull()))]
GB2_D4 = GB2_D4.assign(Entity1=t)
GB2_D4['Class'] = 'CB/GB'


frames_D4 = [ BB2_D4, BBHP2_D4, SME2_D4, GB2_D4] 
MGS_D4 = pd.concat(frames_D4)

MGS1_D4 = MGS_D4.groupby(['Class','Entity1','Entity']).sum().reset_index().sort_values(by=['Entity1'], ascending=[False])

MGS1_D4['Total Exposures w/o Bookings'] = MGS1_D4["Total Exposure_ (RM 'mil)"]-MGS1_D4["Bookings _(RM 'mil)"]

MGS1_D4['D4ate'] = D4

MGS1_D4.Entity = MGS1_D4.Entity.str.strip()

def utilization(Entity):
    if Entity == 'Construction':
        return 31700 
    elif Entity == 'Oil & Gas':
        return 37490 
    elif Entity == 'Oil Palm':
        return 30700
    elif Entity == 'Shipping':
        return 10110
    else:
        return 31700+37490+30700+10110
        
MGS1_D4['Limit/ThresholD4'] = MGS1_D4['Entity'].apply(utilization)
MGS1_D4['Utilization Exposures w/o bookings'] = MGS1_D4['Total Exposures w/o Bookings']/MGS1_D4['Limit/ThresholD4']
MGS1_D4['Utilization Exposures'] = MGS1_D4["Total Exposure_ (RM 'mil)"]/MGS1_D4['Limit/ThresholD4']

MGS2_D4 = MGS1_D4.iloc[np.where(MGS1_D4.Entity1!='Total')].sort_values(by=['Class','Entity1','Entity'],ascending=[True,True,True])

In [ ]:
MGS2_D4

In [ ]:
#_D5

BB1_D5 = BB5[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BB1_D5.columns = BB1_D5.columns.str.replace("\n", "_")
BB2_D5 = BB1_D5.iloc[np.where(~(BB1_D5.Entity.isnull()))]
BB2_D5 = BB2_D5.assign(Entity1=t)
BB2_D5['Class'] = 'BB'


BBHP1_D5 = BBHP5[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BBHP1_D5.columns = BBHP1_D5.columns.str.replace("\n", "_")
BBHP2_D5 = BBHP1_D5.iloc[np.where(~(BBHP1_D5.Entity.isnull()))]
BBHP2_D5 = BBHP2_D5.assign(Entity1=t)
BBHP2_D5['Class'] = 'BB'


SME1_D5 = SME5[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
SME1_D5.columns = SME1_D5.columns.str.replace("\n", "_")
SME2_D5 = SME1_D5.iloc[np.where(~(SME1_D5.Entity.isnull()))]
SME2_D5 = SME2_D5.assign(Entity1=t)
SME2_D5['Class'] = 'SME'


GB1_D5 = GB5[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
GB1_D5.columns = GB1_D5.columns.str.replace("\n", "_")
GB2_D5 = GB1_D5.iloc[np.where(~(GB1_D5.Entity.isnull()))]
GB2_D5 = GB2_D5.assign(Entity1=t)
GB2_D5['Class'] = 'CB/GB'


frames_D5 = [ BB2_D5, BBHP2_D5, SME2_D5, GB2_D5] 
MGS_D5 = pd.concat(frames_D5)

MGS1_D5 = MGS_D5.groupby(['Class','Entity1','Entity']).sum().reset_index().sort_values(by=['Entity1'], ascending=[False])

MGS1_D5['Total Exposures w/o Bookings'] = MGS1_D5["Total Exposure_ (RM 'mil)"]-MGS1_D5["Bookings _(RM 'mil)"]

MGS1_D5['D5ate'] = D5

MGS1_D5.Entity = MGS1_D5.Entity.str.strip()

def utilization(Entity):
    if Entity == 'Construction':
        return 31700 
    elif Entity == 'Oil & Gas':
        return 37490 
    elif Entity == 'Oil Palm':
        return 30700
    elif Entity == 'Shipping':
        return 10110
    else:
        return 31700+37490+30700+10110
        
MGS1_D5['Limit/ThresholD5'] = MGS1_D5['Entity'].apply(utilization)
MGS1_D5['Utilization Exposures w/o bookings'] = MGS1_D5['Total Exposures w/o Bookings']/MGS1_D5['Limit/ThresholD5']
MGS1_D5['Utilization Exposures'] = MGS1_D5["Total Exposure_ (RM 'mil)"]/MGS1_D5['Limit/ThresholD5']

MGS2_D5 = MGS1_D5.iloc[np.where(MGS1_D5.Entity1!='Total')].sort_values(by=['Class','Entity1','Entity'],ascending=[True,True,True])

In [ ]:
MGS2_D5

In [ ]:
#_D6

BB1_D6 = BB6[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BB1_D6.columns = BB1_D6.columns.str.replace("\n", "_")
BB2_D6 = BB1_D6.iloc[np.where(~(BB1_D6.Entity.isnull()))]
BB2_D6 = BB2_D6.assign(Entity1=t)
BB2_D6['Class'] = 'BB'


BBHP1_D6 = BBHP6[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BBHP1_D6.columns = BBHP1_D6.columns.str.replace("\n", "_")
BBHP2_D6 = BBHP1_D6.iloc[np.where(~(BBHP1_D6.Entity.isnull()))]
BBHP2_D6 = BBHP2_D6.assign(Entity1=t)
BBHP2_D6['Class'] = 'BB'


SME1_D6 = SME6[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
SME1_D6.columns = SME1_D6.columns.str.replace("\n", "_")
SME2_D6 = SME1_D6.iloc[np.where(~(SME1_D6.Entity.isnull()))]
SME2_D6 = SME2_D6.assign(Entity1=t)
SME2_D6['Class'] = 'SME'


GB1_D6 = GB6[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
GB1_D6.columns = GB1_D6.columns.str.replace("\n", "_")
GB2_D6 = GB1_D6.iloc[np.where(~(GB1_D6.Entity.isnull()))]
GB2_D6 = GB2_D6.assign(Entity1=t)
GB2_D6['Class'] = 'CB/GB'


frames_D6 = [ BB2_D6, BBHP2_D6, SME2_D6, GB2_D6] 
MGS_D6 = pd.concat(frames_D6)

MGS1_D6 = MGS_D6.groupby(['Class','Entity1','Entity']).sum().reset_index().sort_values(by=['Entity1'], ascending=[False])

MGS1_D6['Total Exposures w/o Bookings'] = MGS1_D6["Total Exposure_ (RM 'mil)"]-MGS1_D6["Bookings _(RM 'mil)"]

MGS1_D6['D6ate'] = D6

MGS1_D6.Entity = MGS1_D6.Entity.str.strip()

def utilization(Entity):
    if Entity == 'Construction':
        return 31700 
    elif Entity == 'Oil & Gas':
        return 37490 
    elif Entity == 'Oil Palm':
        return 30700
    elif Entity == 'Shipping':
        return 10110
    else:
        return 31700+37490+30700+10110
        
MGS1_D6['Limit/ThresholD6'] = MGS1_D6['Entity'].apply(utilization)
MGS1_D6['Utilization Exposures w/o bookings'] = MGS1_D6['Total Exposures w/o Bookings']/MGS1_D6['Limit/ThresholD6']
MGS1_D6['Utilization Exposures'] = MGS1_D6["Total Exposure_ (RM 'mil)"]/MGS1_D6['Limit/ThresholD6']

MGS2_D6 = MGS1_D6.iloc[np.where(MGS1_D6.Entity1!='Total')].sort_values(by=['Class','Entity1','Entity'],ascending=[True,True,True])

In [ ]:
MGS2_D6

In [ ]:
#_D7

BB1_D7 = BB7[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BB1_D7.columns = BB1_D7.columns.str.replace("\n", "_")
BB2_D7 = BB1_D7.iloc[np.where(~(BB1_D7.Entity.isnull()))]
BB2_D7 = BB2_D7.assign(Entity1=t)
BB2_D7['Class'] = 'BB'


BBHP1_D7 = BBHP7[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BBHP1_D7.columns = BBHP1_D7.columns.str.replace("\n", "_")
BBHP2_D7 = BBHP1_D7.iloc[np.where(~(BBHP1_D7.Entity.isnull()))]
BBHP2_D7 = BBHP2_D7.assign(Entity1=t)
BBHP2_D7['Class'] = 'BB'


SME1_D7 = SME7[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
SME1_D7.columns = SME1_D7.columns.str.replace("\n", "_")
SME2_D7 = SME1_D7.iloc[np.where(~(SME1_D7.Entity.isnull()))]
SME2_D7 = SME2_D7.assign(Entity1=t)
SME2_D7['Class'] = 'SME'


GB1_D7 = GB7[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
GB1_D7.columns = GB1_D7.columns.str.replace("\n", "_")
GB2_D7 = GB1_D7.iloc[np.where(~(GB1_D7.Entity.isnull()))]
GB2_D7 = GB2_D7.assign(Entity1=t)
GB2_D7['Class'] = 'CB/GB'


frames_D7 = [ BB2_D7, BBHP2_D7, SME2_D7, GB2_D7] 
MGS_D7 = pd.concat(frames_D7)

MGS1_D7 = MGS_D7.groupby(['Class','Entity1','Entity']).sum().reset_index().sort_values(by=['Entity1'], ascending=[False])

MGS1_D7['Total Exposures w/o Bookings'] = MGS1_D7["Total Exposure_ (RM 'mil)"]-MGS1_D7["Bookings _(RM 'mil)"]

MGS1_D7['D7ate'] = D7

MGS1_D7.Entity = MGS1_D7.Entity.str.strip()

def utilization(Entity):
    if Entity == 'Construction':
        return 31700 
    elif Entity == 'Oil & Gas':
        return 37490 
    elif Entity == 'Oil Palm':
        return 30700
    elif Entity == 'Shipping':
        return 10110
    else:
        return 31700+37490+30700+10110
        
MGS1_D7['Limit/ThresholD7'] = MGS1_D7['Entity'].apply(utilization)
MGS1_D7['Utilization Exposures w/o bookings'] = MGS1_D7['Total Exposures w/o Bookings']/MGS1_D7['Limit/ThresholD7']
MGS1_D7['Utilization Exposures'] = MGS1_D7["Total Exposure_ (RM 'mil)"]/MGS1_D7['Limit/ThresholD7']

MGS2_D7 = MGS1_D7.iloc[np.where(MGS1_D7.Entity1!='Total')].sort_values(by=['Class','Entity1','Entity'],ascending=[True,True,True])

In [ ]:
MGS2_D7

In [ ]:
#_D8

BB1_D8 = BB8[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BB1_D8.columns = BB1_D8.columns.str.replace("\n", "_")
BB2_D8 = BB1_D8.iloc[np.where(~(BB1_D8.Entity.isnull()))]
BB2_D8 = BB2_D8.assign(Entity1=t)
BB2_D8['Class'] = 'BB'


BBHP1_D8 = BBHP8[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BBHP1_D8.columns = BBHP1_D8.columns.str.replace("\n", "_")
BBHP2_D8 = BBHP1_D8.iloc[np.where(~(BBHP1_D8.Entity.isnull()))]
BBHP2_D8 = BBHP2_D8.assign(Entity1=t)
BBHP2_D8['Class'] = 'BB'


SME1_D8 = SME8[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
SME1_D8.columns = SME1_D8.columns.str.replace("\n", "_")
SME2_D8 = SME1_D8.iloc[np.where(~(SME1_D8.Entity.isnull()))]
SME2_D8 = SME2_D8.assign(Entity1=t)
SME2_D8['Class'] = 'SME'


GB1_D8 = GB8[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
GB1_D8.columns = GB1_D8.columns.str.replace("\n", "_")
GB2_D8 = GB1_D8.iloc[np.where(~(GB1_D8.Entity.isnull()))]
GB2_D8 = GB2_D8.assign(Entity1=t)
GB2_D8['Class'] = 'CB/GB'


frames_D8 = [ BB2_D8, BBHP2_D8, SME2_D8, GB2_D8] 
MGS_D8 = pd.concat(frames_D8)

MGS1_D8 = MGS_D8.groupby(['Class','Entity1','Entity']).sum().reset_index().sort_values(by=['Entity1'], ascending=[False])

MGS1_D8['Total Exposures w/o Bookings'] = MGS1_D8["Total Exposure_ (RM 'mil)"]-MGS1_D8["Bookings _(RM 'mil)"]

MGS1_D8['D8ate'] = D8

MGS1_D8.Entity = MGS1_D8.Entity.str.strip()

def utilization(Entity):
    if Entity == 'Construction':
        return 31700 
    elif Entity == 'Oil & Gas':
        return 37490 
    elif Entity == 'Oil Palm':
        return 30700
    elif Entity == 'Shipping':
        return 10110
    else:
        return 31700+37490+30700+10110
        
MGS1_D8['Limit/ThresholD8'] = MGS1_D8['Entity'].apply(utilization)
MGS1_D8['Utilization Exposures w/o bookings'] = MGS1_D8['Total Exposures w/o Bookings']/MGS1_D8['Limit/ThresholD8']
MGS1_D8['Utilization Exposures'] = MGS1_D8["Total Exposure_ (RM 'mil)"]/MGS1_D8['Limit/ThresholD8']

MGS2_D8 = MGS1_D8.iloc[np.where(MGS1_D8.Entity1!='Total')].sort_values(by=['Class','Entity1','Entity'],ascending=[True,True,True])

In [ ]:
MGS2_D8

In [ ]:
#_D9

BB1_D9 = BB9[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BB1_D9.columns = BB1_D9.columns.str.replace("\n", "_")
BB2_D9 = BB1_D9.iloc[np.where(~(BB1_D9.Entity.isnull()))]
BB2_D9 = BB2_D9.assign(Entity1=t)
BB2_D9['Class'] = 'BB'


BBHP1_D9 = BBHP9[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BBHP1_D9.columns = BBHP1_D9.columns.str.replace("\n", "_")
BBHP2_D9 = BBHP1_D9.iloc[np.where(~(BBHP1_D9.Entity.isnull()))]
BBHP2_D9 = BBHP2_D9.assign(Entity1=t)
BBHP2_D9['Class'] = 'BB'


SME1_D9 = SME9[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
SME1_D9.columns = SME1_D9.columns.str.replace("\n", "_")
SME2_D9 = SME1_D9.iloc[np.where(~(SME1_D9.Entity.isnull()))]
SME2_D9 = SME2_D9.assign(Entity1=t)
SME2_D9['Class'] = 'SME'


GB1_D9 = GB9[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
GB1_D9.columns = GB1_D9.columns.str.replace("\n", "_")
GB2_D9 = GB1_D9.iloc[np.where(~(GB1_D9.Entity.isnull()))]
GB2_D9 = GB2_D9.assign(Entity1=t)
GB2_D9['Class'] = 'CB/GB'


frames_D9 = [ BB2_D9, BBHP2_D9, SME2_D9, GB2_D9] 
MGS_D9 = pd.concat(frames_D9)

MGS1_D9 = MGS_D9.groupby(['Class','Entity1','Entity']).sum().reset_index().sort_values(by=['Entity1'], ascending=[False])

MGS1_D9['Total Exposures w/o Bookings'] = MGS1_D9["Total Exposure_ (RM 'mil)"]-MGS1_D9["Bookings _(RM 'mil)"]

MGS1_D9['D9ate'] = D9

MGS1_D9.Entity = MGS1_D9.Entity.str.strip()

def utilization(Entity):
    if Entity == 'Construction':
        return 31700 
    elif Entity == 'Oil & Gas':
        return 37490 
    elif Entity == 'Oil Palm':
        return 30700
    elif Entity == 'Shipping':
        return 10110
    else:
        return 31700+37490+30700+10110
        
MGS1_D9['Limit/ThresholD9'] = MGS1_D9['Entity'].apply(utilization)
MGS1_D9['Utilization Exposures w/o bookings'] = MGS1_D9['Total Exposures w/o Bookings']/MGS1_D9['Limit/ThresholD9']
MGS1_D9['Utilization Exposures'] = MGS1_D9["Total Exposure_ (RM 'mil)"]/MGS1_D9['Limit/ThresholD9']

MGS2_D9 = MGS1_D9.iloc[np.where(MGS1_D9.Entity1!='Total')].sort_values(by=['Class','Entity1','Entity'],ascending=[True,True,True])

In [ ]:
MGS2_D9

In [ ]:
#_D10

BB1_D10 = BB10[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BB1_D10.columns = BB1_D10.columns.str.replace("\n", "_")
BB2_D10 = BB1_D10.iloc[np.where(~(BB1_D10.Entity.isnull()))]
BB2_D10 = BB2_D10.assign(Entity1=t)
BB2_D10['Class'] = 'BB'


BBHP1_D10 = BBHP10[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BBHP1_D10.columns = BBHP1_D10.columns.str.replace("\n", "_")
BBHP2_D10 = BBHP1_D10.iloc[np.where(~(BBHP1_D10.Entity.isnull()))]
BBHP2_D10 = BBHP2_D10.assign(Entity1=t)
BBHP2_D10['Class'] = 'BB'


SME1_D10 = SME10[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
SME1_D10.columns = SME1_D10.columns.str.replace("\n", "_")
SME2_D10 = SME1_D10.iloc[np.where(~(SME1_D10.Entity.isnull()))]
SME2_D10 = SME2_D10.assign(Entity1=t)
SME2_D10['Class'] = 'SME'


GB1_D10 = GB10[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
GB1_D10.columns = GB1_D10.columns.str.replace("\n", "_")
GB2_D10 = GB1_D10.iloc[np.where(~(GB1_D10.Entity.isnull()))]
GB2_D10 = GB2_D10.assign(Entity1=t)
GB2_D10['Class'] = 'CB/GB'


frames_D10 = [ BB2_D10, BBHP2_D10, SME2_D10, GB2_D10] 
MGS_D10 = pd.concat(frames_D10)

MGS1_D10 = MGS_D10.groupby(['Class','Entity1','Entity']).sum().reset_index().sort_values(by=['Entity1'], ascending=[False])

MGS1_D10['Total Exposures w/o Bookings'] = MGS1_D10["Total Exposure_ (RM 'mil)"]-MGS1_D10["Bookings _(RM 'mil)"]

MGS1_D10['D10ate'] = D10

MGS1_D10.Entity = MGS1_D10.Entity.str.strip()

def utilization(Entity):
    if Entity == 'Construction':
        return 31700 
    elif Entity == 'Oil & Gas':
        return 37490 
    elif Entity == 'Oil Palm':
        return 30700
    elif Entity == 'Shipping':
        return 10110
    else:
        return 31700+37490+30700+10110
        
MGS1_D10['Limit/ThresholD10'] = MGS1_D10['Entity'].apply(utilization)
MGS1_D10['Utilization Exposures w/o bookings'] = MGS1_D10['Total Exposures w/o Bookings']/MGS1_D10['Limit/ThresholD10']
MGS1_D10['Utilization Exposures'] = MGS1_D10["Total Exposure_ (RM 'mil)"]/MGS1_D10['Limit/ThresholD10']

MGS2_D10 = MGS1_D10.iloc[np.where(MGS1_D10.Entity1!='Total')].sort_values(by=['Class','Entity1','Entity'],ascending=[True,True,True])

In [ ]:
MGS2_D10

In [ ]:
#_D11

BB1_D11 = BB11[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BB1_D11.columns = BB1_D11.columns.str.replace("\n", "_")
BB2_D11 = BB1_D11.iloc[np.where(~(BB1_D11.Entity.isnull()))]
BB2_D11 = BB2_D11.assign(Entity1=t)
BB2_D11['Class'] = 'BB'


BBHP1_D11 = BBHP11[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BBHP1_D11.columns = BBHP1_D11.columns.str.replace("\n", "_")
BBHP2_D11 = BBHP1_D11.iloc[np.where(~(BBHP1_D11.Entity.isnull()))]
BBHP2_D11 = BBHP2_D11.assign(Entity1=t)
BBHP2_D11['Class'] = 'BB'


SME1_D11 = SME11[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
SME1_D11.columns = SME1_D11.columns.str.replace("\n", "_")
SME2_D11 = SME1_D11.iloc[np.where(~(SME1_D11.Entity.isnull()))]
SME2_D11 = SME2_D11.assign(Entity1=t)
SME2_D11['Class'] = 'SME'


GB1_D11 = GB11[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
GB1_D11.columns = GB1_D11.columns.str.replace("\n", "_")
GB2_D11 = GB1_D11.iloc[np.where(~(GB1_D11.Entity.isnull()))]
GB2_D11 = GB2_D11.assign(Entity1=t)
GB2_D11['Class'] = 'CB/GB'


frames_D11 = [ BB2_D11, BBHP2_D11, SME2_D11, GB2_D11] 
MGS_D11 = pd.concat(frames_D11)

MGS1_D11 = MGS_D11.groupby(['Class','Entity1','Entity']).sum().reset_index().sort_values(by=['Entity1'], ascending=[False])

MGS1_D11['Total Exposures w/o Bookings'] = MGS1_D11["Total Exposure_ (RM 'mil)"]-MGS1_D11["Bookings _(RM 'mil)"]

MGS1_D11['D11ate'] = D11

MGS1_D11.Entity = MGS1_D11.Entity.str.strip()

def utilization(Entity):
    if Entity == 'Construction':
        return 31700 
    elif Entity == 'Oil & Gas':
        return 37490 
    elif Entity == 'Oil Palm':
        return 30700
    elif Entity == 'Shipping':
        return 10110
    else:
        return 31700+37490+30700+10110
        
MGS1_D11['Limit/ThresholD11'] = MGS1_D11['Entity'].apply(utilization)
MGS1_D11['Utilization Exposures w/o bookings'] = MGS1_D11['Total Exposures w/o Bookings']/MGS1_D11['Limit/ThresholD11']
MGS1_D11['Utilization Exposures'] = MGS1_D11["Total Exposure_ (RM 'mil)"]/MGS1_D11['Limit/ThresholD11']

MGS2_D11 = MGS1_D11.iloc[np.where(MGS1_D11.Entity1!='Total')].sort_values(by=['Class','Entity1','Entity'],ascending=[True,True,True])

In [ ]:
MGS2_D11

In [ ]:
#_D12

BB1_D12 = BB12[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BB1_D12.columns = BB1_D12.columns.str.replace("\n", "_")
BB2_D12 = BB1_D12.iloc[np.where(~(BB1_D12.Entity.isnull()))]
BB2_D12 = BB2_D12.assign(Entity1=t)
BB2_D12['Class'] = 'BB'


BBHP1_D12 = BBHP12[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
BBHP1_D12.columns = BBHP1_D12.columns.str.replace("\n", "_")
BBHP2_D12 = BBHP1_D12.iloc[np.where(~(BBHP1_D12.Entity.isnull()))]
BBHP2_D12 = BBHP2_D12.assign(Entity1=t)
BBHP2_D12['Class'] = 'BB'


SME1_D12 = SME12[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
SME1_D12.columns = SME1_D12.columns.str.replace("\n", "_")
SME2_D12 = SME1_D12.iloc[np.where(~(SME1_D12.Entity.isnull()))]
SME2_D12 = SME2_D12.assign(Entity1=t)
SME2_D12['Class'] = 'SME'


GB1_D12 = GB12[["Unnamed: 0","Bookings \n(RM 'mil)","Total Exposure\n (RM 'mil)","Outstanding \n(RM 'mil)"]].rename(columns={'Unnamed: 0':'Entity'})
GB1_D12.columns = GB1_D12.columns.str.replace("\n", "_")
GB2_D12 = GB1_D12.iloc[np.where(~(GB1_D12.Entity.isnull()))]
GB2_D12 = GB2_D12.assign(Entity1=t)
GB2_D12['Class'] = 'CB/GB'


frames_D12 = [ BB2_D12, BBHP2_D12, SME2_D12, GB2_D12] 
MGS_D12 = pd.concat(frames_D12)

MGS1_D12 = MGS_D12.groupby(['Class','Entity1','Entity']).sum().reset_index().sort_values(by=['Entity1'], ascending=[False])

MGS1_D12['Total Exposures w/o Bookings'] = MGS1_D12["Total Exposure_ (RM 'mil)"]-MGS1_D12["Bookings _(RM 'mil)"]

MGS1_D12['D12ate'] = D12

MGS1_D12.Entity = MGS1_D12.Entity.str.strip()

def utilization(Entity):
    if Entity == 'Construction':
        return 31700 
    elif Entity == 'Oil & Gas':
        return 37490 
    elif Entity == 'Oil Palm':
        return 30700
    elif Entity == 'Shipping':
        return 10110
    else:
        return 31700+37490+30700+10110
        
MGS1_D12['Limit/ThresholD12'] = MGS1_D12['Entity'].apply(utilization)
MGS1_D12['Utilization Exposures w/o bookings'] = MGS1_D12['Total Exposures w/o Bookings']/MGS1_D12['Limit/ThresholD12']
MGS1_D12['Utilization Exposures'] = MGS1_D12["Total Exposure_ (RM 'mil)"]/MGS1_D12['Limit/ThresholD12']

MGS2_D12 = MGS1_D12.iloc[np.where(MGS1_D12.Entity1!='Total')].sort_values(by=['Class','Entity1','Entity'],ascending=[True,True,True])

In [ ]:
MGS2_D12

In [ ]:
MGS2_D.columns = MGS2_D1.columns = MGS2_D2.columns = MGS2_D3.columns = MGS2_D4.columns = MGS2_D5.columns = MGS2_D6.columns = MGS2_D7.columns = MGS2_D8.columns = MGS2_D9.columns = MGS2_D10.columns = MGS2_D11.columns = MGS2_D12.columns

frames_yearly = [MGS2_D,MGS2_D1,MGS2_D2,MGS2_D3,MGS2_D4,MGS2_D5,MGS2_D6,MGS2_D7,MGS2_D8,MGS2_D9,MGS2_D10,MGS2_D11,MGS2_D12] 
MGS__yearly = pd.concat(frames_yearly)

In [ ]:
MGS__yearly.rename(columns= {'D12ate':'Date','Limit/ThresholD12':'Limit/Threshold'}, inplace=True)
MGS__yearly['date_time'] = pd.to_datetime(MGS__yearly['Date'], format='%b %Y')

In [ ]:
MGS__yearly.Entity = MGS__yearly.Entity.str.strip()

Construction = MGS__yearly.iloc[np.where((MGS__yearly.Entity=='Construction')&(MGS__yearly.Date==D12))].groupby(['Class'])[["Total Exposure_ (RM 'mil)","Outstanding _(RM 'mil)","Bookings _(RM 'mil)"]].sum().reset_index()
Construction1 = MGS__yearly.iloc[np.where((MGS__yearly.Entity=='Oil Palm')&(MGS__yearly.Date==D12))].groupby(['Class'])[["Total Exposure_ (RM 'mil)","Outstanding _(RM 'mil)","Bookings _(RM 'mil)"]].sum().reset_index()
Construction2 = MGS__yearly.iloc[np.where((MGS__yearly.Entity=='Oil & Gas')&(MGS__yearly.Date==D12))].groupby(['Class'])[["Total Exposure_ (RM 'mil)","Outstanding _(RM 'mil)","Bookings _(RM 'mil)"]].sum().reset_index()
Construction3 = MGS__yearly.iloc[np.where((MGS__yearly.Entity=='Shipping')&(MGS__yearly.Date==D12))].groupby(['Class'])[["Total Exposure_ (RM 'mil)","Outstanding _(RM 'mil)","Bookings _(RM 'mil)"]].sum().reset_index()
Total = MGS__yearly.groupby(['date_time'])[["Bookings _(RM 'mil)","Total Exposure_ (RM 'mil)","Outstanding _(RM 'mil)","Total Exposures w/o Bookings","Utilization Exposures w/o bookings","Utilization Exposures"]].sum().reset_index().sort_values(by=['date_time'], ascending=[True])

In [ ]:
Total1 = MGS__yearly.groupby(['date_time','Entity'])[["Bookings _(RM 'mil)","Total Exposure_ (RM 'mil)","Outstanding _(RM 'mil)","Total Exposures w/o Bookings","Utilization Exposures w/o bookings","Utilization Exposures"]].sum().reset_index().sort_values(by=['date_time'], ascending=[True])

In [ ]:
Exposure_EN = Total1.pivot(index='Entity', columns='date_time', values="Total Exposure_ (RM 'mil)")

In [ ]:
Exposure_EN

In [ ]:
Total2 = MGS__yearly.groupby(['date_time','Class'])[["Bookings _(RM 'mil)","Total Exposure_ (RM 'mil)","Outstanding _(RM 'mil)","Total Exposures w/o Bookings","Utilization Exposures w/o bookings","Utilization Exposures"]].sum().reset_index().sort_values(by=['date_time'], ascending=[True])

In [ ]:
Class_EN = Total2.pivot(index='Class', columns='date_time', values="Total Exposure_ (RM 'mil)")
Class_EN

In [ ]:
writer = pd.ExcelWriter(r'T:\MIB Risk Management\CRM\23.0_MGS Sectoral\MGS_yearly('+D+'-'+D12+').xlsx', engine='xlsxwriter')

MGS__yearly.to_excel(writer, sheet_name='MGS listing', index = False)
Construction.to_excel(writer, sheet_name='Construction', index = False)
Construction1.to_excel(writer, sheet_name='Oil Palm', index = False)
Construction2.to_excel(writer, sheet_name='Oil & Gas', index = False)
Construction3.to_excel(writer, sheet_name='Shipping', index = False) 
Total.to_excel(writer, sheet_name='Total', index = False)

writer.save()

In [ ]:
MGS__yearly.Entity = MGS__yearly.Entity.str.strip()

construction = MGS__yearly.iloc[np.where(MGS__yearly.Entity=='Total')].groupby(['Date']).sum().reset_index()
construction1 = MGS__yearly.iloc[np.where(MGS__yearly.Entity=='Bilateral Loan')].groupby(['Date']).sum().reset_index()
construction2 = MGS__yearly.iloc[np.where(MGS__yearly.Entity=='Fixed Income Secrurities (FIS)')].groupby(['Date']).sum().reset_index()
construction3 = MGS__yearly.iloc[np.where(MGS__yearly.Entity=='Oil & Gas')].groupby(['Date']).sum().reset_index()
construction4 = MGS__yearly.iloc[np.where(MGS__yearly.Entity=='Shipping')].groupby(['Date']).sum().reset_index()
construction5 = MGS__yearly.iloc[np.where(MGS__yearly.Entity=='Construction')].groupby(['Date']).sum().reset_index()
construction6 = MGS__yearly.iloc[np.where(MGS__yearly.Entity=='Oil Palm')].groupby(['Date']).sum().reset_index()

In [ ]:
# bar_chart_legend.py

import matplotlib.pyplot as plt

def bar_chart(numbers, labels, pos):
    plt.bar(pos, [4, 5, 6, 3], color='green')
    plt.bar(pos, numbers, color='blue')
    plt.xticks(ticks=pos, labels=labels)
    plt.xlabel('Vehicle Types')
    plt.ylabel('Number of Vehicles')
    plt.legend(['First Label', 'Second Label'], loc='upper left')
    plt.show()

if __name__ == '__main__':
    numbers = [2, 1, 4, 6]
    labels = ['Electric', 'Solar', 'Diesel', 'Unleaded']
    pos = list(range(4))
    bar_chart(numbers, labels, pos)