In [2]:
RDATEC = 202206 #/*current month*/
#RDATEP = 202206 #/*last month*/

RATE_1 = '30/06/2022'  #currentdate
#RATE_2 = '30/06/2022'  #lastdate
R_YEAR = '06/2022'     #currentdate

import numpy as np
import pandas as pd
import pandasql
import sqlite3

pd.set_option("display.max_columns", None) 
pd.set_option("display.max_colwidth", 1000) #huruf dlm column
pd.set_option("display.max_rows", 100)
pd.set_option("display.precision", 2) #2 titik perpuluhan

#/******************************* Home Financing (HOME_RDATE) *******************************/

HF_HOME = pd.read_csv(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\02_Data_Source\05_Home_Financing\04_Dataset\\"+str(RDATEC)+"\mortgage_"+str(RDATEC)+".txt", sep = "\t", header = 0,encoding='cp1252',low_memory=False)
#DSR_TL = pd.read_csv(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\04_Infocube\99_Data_Source\01_Datawarehouse\01_Credit_Risk_Reporting\18_FRAN_DSR\\"+str(RDATEC)+"\DSR_TL_"+str(RDATEC)+".txt", sep = "\t", header = 3,low_memory=False)
#DSR_OD = pd.read_csv(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\04_Infocube\99_Data_Source\01_Datawarehouse\01_Credit_Risk_Reporting\18_FRAN_DSR\\"+str(RDATEC)+"\DSR_OD_"+str(RDATEC)+".txt", sep = "\t", header = 3,low_memory=False)

HF_HOME.columns = HF_HOME.columns.str.replace(" ", "_").str.replace(".", "_")
#DSR_TL.columns = DSR_TL.columns.str.replace(" ", "_")
#DSR_OD.columns = DSR_OD.columns.str.replace(" ", "_")

#HF_HOME_P = pd.read_csv(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\02_Data_Source\05_Home_Financing\04_Dataset\\"+str(RDATEP)+"\mortgage_"+str(RDATEP)+".txt", sep = "\t", header = 0,encoding='cp1252',low_memory=False)
#DSR_TL_P = pd.read_csv(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\04_Infocube\99_Data_Source\01_Datawarehouse\01_Credit_Risk_Reporting\18_FRAN_DSR\\"+str(RDATEP)+"\DSR_TL_"+str(RDATEP)+".txt", sep = "\t", header = 3,low_memory=False)
#DSR_OD_P = pd.read_csv(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\04_Infocube\99_Data_Source\01_Datawarehouse\01_Credit_Risk_Reporting\18_FRAN_DSR\\"+str(RDATEP)+"\DSR_OD_"+str(RDATEP)+".txt", sep = "\t", header = 3,low_memory=False)

#HF_HOME_P.columns = HF_HOME_P.columns.str.replace(" ", "_").str.replace(".", "_")
#DSR_TL_P.columns = DSR_TL_P.columns.str.replace(" ", "_")
#DSR_OD_P.columns = DSR_OD_P.columns.str.replace(" ", "_")

In [4]:
#-------------------------------------------HF001-------------------------------------------

HF001 = HF_HOME.iloc[np.where((HF_HOME.FIN_TYPE == 'I')&(HF_HOME.LEVEL_6 == 'Housing'))]

HF001.rename(columns = {'RISK_GRADE_VAL':'RISK_GRADE_VAL1',\
                        'M_NPL_DATE':'M_NPL_DATE1',\
                        'GCIF_INCOME':'GCIF_INCOME1',\
                        'OCCUPATION_SECTOR':'OCCUPATION_SECTOR1',\
                        'GENDER':'GENDER1',\
                        'RACE':'RACE1',\
                        'AGE_RANGE':'AGE_RANGE1',\
                        'PROP_DESC':'PROP_DESC1',\
                        'P_USAGE':'P_USAGE1',\
                        'AMRT_TERM':'AMRT_TERM1',\
                        'M_DATE_AA_APPROVED':'M_DATE_AA_APPROVED1',\
                        'PUR_PRC':'PUR_PRC1',\
                        'SNP':'SNP1',\
                        'CMV':'CMV1',\
                        'STATE':'STATE1',\
                        'CUSTOMER_SEGMENT':'CUSTOMER_SEGMENT1',\
                        'DSR_RAT':'DSR_RAT1'}, inplace = True)

D:\anaconda3\lib\site-packages\pandas\core\frame.py:4133: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [8]:
def RATING(x):
    if x=='R1':
        return '01. R1'
    elif x=='R2':
        return '02. R2'
    elif x=='R3':
        return '03. R3'
    elif x=='R4':
        return '04. R4'
    elif x=='R5':
        return '05. R5'
    elif x=='R6':
        return '06. R6'
    elif x=='R7':
        return '07. R7'
    elif x=='R8':
        return '08. R8'
    elif x=='R9':
        return '09. R9'
    elif x=='R10':
        return '10. R10'
    elif x=='R11':
        return '11. R11'
    else: 
        return 'Unrated'
HF001['RISK_GRADE_VAL'] = HF001['RISK_GRADE_VAL1'].apply(RATING)

HF001.loc[HF001.M_NPL_FLG=='Y','RISK_GRADE_VAL']='IF'

def INCOM(x):
    if x=='Up to RM999':
        return '01. Up to RM3,000'
    elif x=='RM1,000 to RM1,999':
        return '01. Up to RM3,000'
    elif x=='RM2,000 to RM2,999':
        return '01. Up to RM3,000'
    elif x=='RM3,000 to RM3,999':
        return '02. Above RM3,000 to RM5,000'
    elif x=='RM4,000 to RM4,999':
        return '02. Above RM3,000 to RM5,000'
    elif x=='RM5,000 to RM5,999':
        return '03. Above RM5,000 to RM8,000'
    elif x=='RM6,000 to RM6,999':
        return '03. Above RM5,000 to RM8,000'
    elif x=='RM7,000 to RM7,999':
        return '03. Above RM5,000 to RM8,000'
    elif x=='RM8,000 to RM8,999':
        return '04. Above RM8,000 to RM15,000'
    elif x=='RM9,000 to RM9,999':
        return '04. Above RM8,000 to RM15,000'
    elif x=='RM10,000 to RM10,999':
        return '04. Above RM8,000 to RM15,000'
    elif x=='RM11,000 to RM14,999':
        return '04. Above RM8,000 to RM15,000'
    elif x=='RM15,000 to RM20,000':
        return '05. Above RM15,000 to RM20,000'
    elif x=='Above RM 20,000':
        return '06. Above RM20,000'
    else: 
        return 'Not Populated'
HF001['GCIF_INCOME'] = HF001['GCIF_INCOME1'].apply(INCOM)


HF001['OCCUPATION_SECTOR'] = HF001.OCCUPATION_SECTOR1
HF001.loc[HF001.OCCUPATION_SECTOR=='NOT APPLICABLE','OCCUPATION_SECTOR'] = 'ZA_OTHERS'
HF001.loc[HF001.OCCUPATION_SECTOR=='?','OCCUPATION_SECTOR'] = 'ZB_NOT POPULATED'

def GENDER(x):
    if x =='FEMALE':
        return 'Female'
    elif x == 'MALE':
        return 'Male'
    else:
        return 'Not Populated'
HF001['GENDER'] = HF001['GENDER1'].apply(GENDER)
    
def RACE(x):
    if x == 'CHINESE':
        return 'Chinese'
    elif x == 'INDIAN':
        return 'Indian'
    elif x == 'MALAY':
        return 'Malay'
    elif x == 'NATIVE':
        return 'Native'
    else:
        return 'Others'
HF001['RACE'] = HF001['RACE1'].apply(RACE)

def AGE_RANGE(x):
    if x == '<25 years':
        return '01. Up to 25 Years Old'
    elif x == '25 to 29  years':
        return '02. 25 to 29 Years Old'
    elif x == '30 to 34 years':
        return '03. 30 to 34 Years Old'
    elif x == '35 to 39  years':
        return '04. 35 to 39 Years Old'
    elif x == '40 to 44 years':
        return '05. 40 to 44 Years Old'
    elif x == '45 to 49 years':
        return '06. 45 to 49 Years Old'
    elif x == '50 to 54 years':
        return '07. 50 to 54 Years Old'
    elif x == '55 years and above':
        return '08. 55 Years & Above'
    else:
        return 'Not Populated'
HF001['RACE'] = HF001['RACE1'].apply(RACE)

def STATE(x):
    if x == 'LABUAN':
        return 'FED. TERRITORY'
    elif x == 'K.L MAIN':
        return 'FED. TERRITORY'
    else:
        return x
HF001['STATE'] = HF001['STATE1'].apply(STATE)

HF001['OSM'] = HF001.M_BNM_BALANCE/1000000   #/* OUTSTANDING IN MIL */
HF001['NOA'] = 1                             #/* NUMBER OF ACCOUNT  */

HF001.loc[HF001['M_MTHS_INSTALLMENT_IN_ARREARS'] == '?', "M_MTHS_INSTALLMENT_IN_ARREARS"] = -9999
HF001.M_MTHS_INSTALLMENT_IN_ARREARS.fillna(-9999, inplace=True)
HF001['M_MTHS_INSTALLMENT_IN_ARREARS'] = HF001['M_MTHS_INSTALLMENT_IN_ARREARS'].astype(int)

# /* 2 MIA */ 
HF001.loc[HF001.M_MTHS_INSTALLMENT_IN_ARREARS == 2,'OSM_MIA2'] = HF001.M_BNM_BALANCE/1000000
HF001.loc[HF001.M_MTHS_INSTALLMENT_IN_ARREARS == 2,'NOA_MIA2'] = 1

# /* 3 MIA */
HF001.loc[HF001.M_MTHS_INSTALLMENT_IN_ARREARS == 3,'OSM_MIA3'] = HF001.M_BNM_BALANCE/1000000
HF001.loc[HF001.M_MTHS_INSTALLMENT_IN_ARREARS == 3,'NOA_MIA3'] = 1

# /* IF */
HF001.loc[HF001.M_NPL_FLG == 'Y','OSM_IF'] = HF001.M_BNM_BALANCE/1000000
HF001.loc[HF001.M_NPL_FLG == 'Y','NOA_IF'] = 1

# /* NCIF */
HF001['R_YEAR1'] = HF001.M_NPL_DATE1.str[-7:]
HF001.loc[(HF001.M_NPL_FLG == 'Y')&(HF001.R_YEAR1 == R_YEAR),'OSM_NCIF'] = HF001.M_BNM_BALANCE/1000000 #&(HF001.M_NPL_DATE1 == RATE_1)
HF001.loc[(HF001.M_NPL_FLG == 'Y')&(HF001.R_YEAR1 == R_YEAR),'NOA_NCIF'] = 1                           #&(HF001.M_NPL_DATE1 == RATE_1)
HF001.drop('R_YEAR1', axis=1, inplace=True)

# /* TO DETERMINE WHICH VALUE TO BE TAKEN FOR CALCULATION OF MOF AND FTV */
HF001.loc[HF001.PUR_PRC1 == '?', "PUR_PRC1"] = 0
HF001.PUR_PRC1 = HF001.PUR_PRC1.map(float)
HF001['PUR_PRC'] = HF001.PUR_PRC1*1

# /*OMV_WOLOC=OMV_WOLOC1*1;*/
HF001['SNP'] = HF001.SNP1*1
HF001['CMV'] = HF001.CMV1*1

HF001.loc[HF001.SNP == '?', "SNP"] = 0
HF001.loc[HF001.CMV == '?', "CMV"] = 0
HF001.SNP = HF001.SNP.astype(float)
HF001.CMV = HF001.CMV.astype(float)

def PURCHASE_PRICE(PUR_PRC,SNP,CMV):
    if PUR_PRC>0:
        return PUR_PRC
    else:
        if SNP>0:
            return SNP
        else:
            return CMV
HF001['PURCHASE_PRICE'] = HF001.apply(lambda x: PURCHASE_PRICE(x['PUR_PRC'],x['SNP'],x['CMV']), axis=1)

# /* MARGIN OF FINANCE(MOF) & FINANCING TO VALUE(FTV) */
HF001['MOF1'] = HF001.M_APPROVED_LIMIT/HF001.PURCHASE_PRICE
HF001['FTV1'] = HF001.M_BNM_BALANCE/HF001.PURCHASE_PRICE

def PERCEN(x):
    if x == float('inf'):
        return 'Not Populated'
    elif x > 0 and x <= 0.3:
        return '01. Up to 30%'
    elif x > 0.3 and x <= 0.5:
        return '02. > 30% to 50%' 
    elif x > 0.5 and x <= 0.6:
        return '03. > 50% to 60%'
    elif x > 0.6 and x <= 0.7:
        return '04. > 60% to 70%'
    elif x > 0.7 and x <= 0.75:
        return '05. > 70% to 75%'
    elif x > 0.75 and x <= 0.8:
        return '06. > 75% to 80%'
    elif x > 0.8 and x <= 0.85:
        return '07. > 80% to 85%'
    elif x > 0.85 and x <= 0.9:
        return '08. > 85% to 90%'
    elif x > 0.9:
        return '09. >90%'
    else:
        return 'Not Populated'
HF001['MOF'] = HF001.MOF1.apply(PERCEN)
HF001['FTV'] = HF001.FTV1.apply(PERCEN)

# /* PROVERTY VALUE */  
def PURVAL(x):
    if x > 0 and x <= 25000:
        return '01. <=RM25k'
    elif x > 25000 and x <= 42000:
        return '02. <=RM42k'
    elif x > 42000 and x <= 60000:
        return '03. <=RM60k'
    elif x > 60001 and x <= 100000:
        return '04. <=RM100k'
    elif x > 100000 and x <= 150000:
        return '05. <=RM150k'
    elif x > 150000 and x <= 200000:
        return '06. <=RM200k'
    elif x > 200000 and x <= 250000:
        return '07. <=RM250k'
    elif x > 250000 and x <= 500000:
        return '08. <=RM500k'
    elif x > 500000 and x <= 1000000:
        return '09. <=RM1mil'
    elif x > 1000000:
        return '10. >RM1mil'
    else:
        return 'Not Populated'
HF001['PROPERTY_VALUE'] = HF001.PURCHASE_PRICE.apply(PERCEN)                

# /* TYPE OF RESIDENTIAL */
def TYPRES(x):
    if x == 'Terrace House':
        return '01. Terrace House'
    elif x == 'Semi-Detached House':
        return '02. Semi-Detached House'
    elif x == 'Detached House':
        return '03. Detached House'
    elif x == 'Flat/Apartment Unit':
        return '04. Flat/Apartment Unit'
    elif x == 'Condominium Unit':
        return '05. Condominium Unit'
    else:
        return 'Others'
HF001['PROP_DESC'] = HF001.PROP_DESC1.apply(TYPRES)
                
# /* PURPOSE */
def PURPO(x):
    if x == 'INV':
        return '01. Investment'
    elif x == 'OWN':
        return '02. Own'
    else:
        return 'Not Populated'
HF001['P_USAGE'] = HF001.P_USAGE1.apply(PURPO)
            
# /* FINANCING TENURE */
HF001.loc[HF001.AMRT_TERM1 == '?', "AMRT_TERM1"] = 99999
HF001.AMRT_TERM1 = HF001.AMRT_TERM1.astype(int)

def FTENRE(x):
    if x == 99999:
        return '.'
    elif x > 0 and x <= 5:
        return '01. Up to 5 Years'
    elif x > 5 and x <= 10:
        return '02. Up to 10 Years'
    elif x > 10 and x <= 15:
        return '03. Up to 15 Years'
    elif x > 15 and x <= 20:
        return '04. Up to 20 Years'
    elif x > 20 and x <= 25:
        return '05. Up to 25 Years'
    elif x > 25 and x <= 30:
        return '06. Up to 30 Years'
    elif x > 30:
        return '07. More than 30 Years';
HF001['AMRT_TERM'] = HF001.AMRT_TERM1.apply(FTENRE)

D:\anaconda3\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\pandas\core\indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:109: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:120: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:121: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\pandas\core\generic.py:6245: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:125: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\pandas\core\indexing.py:844: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:140: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
D:\anaconda3\lib\site-packages\pandas\core\generic.py:5303: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:148: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:151: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:152: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:167: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:196: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:197: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

D:\anaconda3\lib\site-packages\ipykernel_launcher.py:223: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:239: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:249: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:272: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [14]:
# /* YEAR APPROVED */
HF001['M_DATE_AA_APPROVED_TEMP'] = HF001.M_DATE_AA_APPROVED1.str[-4:]
HF001.loc[(HF001['M_DATE_AA_APPROVED_TEMP']=='?'),'M_DATE_AA_APPROVED_TEMP'] = -9999
HF001['M_DATE_AA_APPROVED_TEMP'] = HF001.M_DATE_AA_APPROVED_TEMP.astype(int)

def year(M_DATE_AA_APPROVED_TEMP):
    if M_DATE_AA_APPROVED_TEMP <= 2000:
        return '<=Year 2000'
    else:
        return 'Year '+str(M_DATE_AA_APPROVED_TEMP)
HF001['M_DATE_AA_APPROVED'] = HF001.M_DATE_AA_APPROVED_TEMP.apply(year)

#HF001['M_DATE_AA_APPROVED'] = 'Year ' + HF001.M_DATE_AA_APPROVED_TEMP

# /* LOAN SIZE */
def LOANSIZ(x):
    if x <= 150000:
        return '01. <=RM150K'
    elif x > 150000 and x <= 500000:
        return '02. RM150-500K'
    elif x > 500000 and x <= 1000000:
        return '03. RM500-1 mil'
    elif x > 1000000:
        return '>04. RM 1 mil'
HF001['LOAN_SIZE'] = HF001.M_APPROVED_LIMIT.apply(LOANSIZ)

# /* CUSTOMER SEGMENT */

def CUSTSEG(x):
    if x == 'HIGH NETWORTH':
        return '01. HNW'
    elif x == 'AFFLUENT':
        return '02. Affluent'
    elif x == 'EMERGING AFFLUENT':
        return '03. Emerging Affluent'
    elif x == 'MASS':
        return '04. Mass'
    else:
        return 'Not Populated'
HF001['CUSTOMER_SEGMENT'] = HF001.CUSTOMER_SEGMENT1.apply(CUSTSEG)

D:\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

D:\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [17]:
Unrated = HF001.iloc[np.where(HF001.RISK_GRADE_VAL == 'Unrated')]

#-------------------------------------------SORTBY(EXCEL)
#tarkih        2022-06
writer2 = pd.ExcelWriter(r'T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\05_Portfolio_Analysis\00_Credit_Risk_Profile\2022-06\Rating & Status migration\Retail\Unrated_Home'+str(RDATEC)+'(python).xlsx',engine='xlsxwriter')
    
Unrated.to_excel(writer2, sheet_name='Unrated', index = False)

writer2.save()

In [9]:
HF001.iloc[np.where(HF001.CUS_NO==11721124)]

,M_ACCOUNT_NO,FIN_TYPE,CONV_ISL,CUS_NO,M_SOURCE_PROD_TYPE_CD,PRODUCT_CODE,M_APPROVED_LIMIT,M_BNM_BALANCE,LEVEL_4,LEVEL_6,M_PRODUCT_HIERARCHY_CD,SOURCE_PROD_TYPE_DSC,M_ECONOMIC_SECTOR_CD,REGION,STATE1,BRANCH_ZONE,BRANCH_DESC,M_DATE_AA_APPROVED1,NAME,CUSTOMER_SEGMENT1,RACE1,GENDER1,MBB_Nationality_Desc,Age,BTH_DT,AMRT_TERM1,M_INSTALMENT_AMT,OCCUPATION,OCCUPATION_SECTOR1,GCIF_INCOME1,MARITAL_STATUS,Customer_Class_Desc,Customer_Type_Desc,MBB_Sub_Market_Segment_Desc,M_DATE_FIRST_RELEASED,M_DATE_FINAL_RELEASED,M_NPL_DATE1,M_NPL_FLG,M_MTHS_INSTALLMENT_IN_ARREARS,M_INSTALLMENT_IN_ARREARS,M_MTHS_INTEREST_IN_ARREARS,M_INTEREST_IN_ARREARS,LAST_PAYMENT_DATE,M_FIRST_INSTALLMENT_DUE_DATE,M_RESCHEDULE_FLG,M_RESTRUCTURE_FLG,DATE_REGULARISED,DATE_1ST_DOUBTFUL,PMT_FREQ,PMT_FREQ_MULT,MATURITY_DATE,CUR_GROSS_RATE,M_BASE_RATE,M_CAGAMAS_TAG,ADJUSTABLE_TYPE_CD,MARGIN_GROSS,WRITEOFF_FLG,M_REPAYMENT_OPTION,EAD,RWA,EXPECTED_LOSS,M_MTHS_IN_ARREARS,M_RELEASED_AMT,AS_OF_DATE,AGE_RANGE1,RELEASED_FLAG,MARGIN_GROSS_RANGE,REPAYMENT_OPTION_DESC,P_USAGE1,STATE_DESC,PROP_DESC1,SNP1,CMV1,AA_NUMBER_NEW,DSR_RATIO,MRGN_OF_ADVN,PUR_PRC1,SCORE_RATG,RISK_GRADE_VAL1,EMP_TYPE_CD,EMP_TYPE_DESC,CORONA_FLAG,CORONA_TAG_DATE,INDUL_STRT_DATE,INDUL_END_DATE,CORONA2_FLAG,CORONA2_TAG_DATE,RA1_FLAG,RA1_DATE,RA2_FLAG,RA2_DATE,RA3_FLAG,RA3_DATE,RA4_FLAG,RA4_DATE,RA5_FLAG,RA5_DATE,RA6_FLAG,RA6_DATE,RA7_FLAG,RA7_DATE,RA8_FLAG,RA8_DATE,RA9_FLAG,RA9_DATE,RA10_FLAG,RA10_DATE,RA11_FLAG,RA11_DATE,RA12_FLAG,RA12_DATE,RA13_FLAG,RA13_DATE,RA14_FLAG,RA14_DATE,RA15_FLAG,RA15_DATE,REM_RESCHEDULE_STRT_DT,REM_RESCHEDULE_STRT_DT_1,RESPANDA_STRT_DT,RSTPANDA_STRT_DT,RESCHN_STRT_DT,RESTRN_STRT_DT,RMVRESPA_STRT_DT,RMVRSTPA_STRT_DT,RMVRECHN_STRT_DT,RMVRESTN_STRT_DT,PEMULIH_FLAG,PEMULIH_DATE,PEMULIH_END_DATE,RAEXTEND_FLAG,RAEXTEND_DATE,RAEXTEND_DATE_1,NEW_IC_NUM,OTHER_ID,OTHER_ID_TYPE,STAGE_CLASSIFICATION,ECL_CLOSING_FY_MYR,EAD_MYR,RISK_GRADE_VAL,GCIF_INCOME,OCCUPATION_SECTOR,GENDER,RACE,STATE,OSM,NOA,OSM_MIA2,NOA_MIA2,OSM_MIA3,NOA_MIA3,OSM_IF,NOA_IF,OSM_NCIF,NOA_NCIF,PUR_PRC,SNP,CMV,PURCHASE_PRICE,MOF1,FTV1,MOF,FTV,PROPERTY_VALUE,PROP_DESC,P_USAGE,AMRT_TERM
10432,464016996405,I,?,11721124,H2,H2,469542.0,458460.30,Term Loans,Housing,H2,HOME FINANCING-I,0310RI01,FEDERAL TERRITORY,FED. TERRITORY,KL MAIN,IBS KUALA LUMPUR MAIN,13/12/2017,TAN KEWI YONG,HIGH NETWORTH,CHINESE,FEMALE,Malaysian,66,06/06/1956,9,5240.00000000,MANAGING DIRECTORS AND CHIEF EXECUTIVES,REAL ESTATE ACTIVITIES,"Above RM 20,000",MARRIED,PERSONAL,NON-BUMIPUTRA INDIVIDUAL,CFS-IND,12/01/2021,10/03/2022,?,N,0,0.00000000,0,0.00000000,?,01/04/2022,N,N,?,?,1,MONTHS,10/03/2031,3.250000000,2.000000000,Y,FLOATING,1.250000000,?,STD REPYMT,458460.30,63697.14,387.34000000,0,469542.0,30/06/2022,55 years and above,FULLY RELEASED,1.250000000,STD REPYMT,INV,Wilayah Persekutuan Kuala Lumpur,Flat/Apartment Unit,781570.06,740000.00,LOC1/64016/2017/31573,261.50,60.00000000,782570.06,6,R2,111,Employer,?,?,01/01/1900,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,N,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,31/12/9999,N,01/01/1900,31/12/9999,560606015668,4992458,IC,STAGE1,99.55,515659.88,02. R2,"06. Above RM20,000",REAL ESTATE ACTIVITIES,Female,Chinese,FED. TERRITORY,0.46,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,782570.06,781570.06,740000.00,782570.06,0.6,0.59,03. > 50% to 60%,03. > 50% to 60%,09. >90%,04. Flat/Apartment Unit,01. Investment,02. Up to 10 Years
36866,464016997341,I,?,11721124,H2,H2,380943.0,376059.41,Term Loans,Housing,H2,HOME FINANCING-I,0310RI01,FEDERAL TERRITORY,FED. TERRITORY,KL MAIN,IBS KUALA LUMPUR MAIN,13/12/2017,TAN KEWI YONG,HIGH NETWORTH,CHINESE,FEMALE,Malaysian,66,06/06/1956,9,4251.00000000,MANAGING DIRECTORS AND CHIEF EXECUTIVES,REAL ESTATE ACTIVITIES,"Above RM 20,000",MARRIED,PERSONAL,NON-BUMIPUTRA INDIVIDUAL,CFS-IND,07/09/2021,22/03/2022,?,N,0,0.00000000,0,0.00000000,?,01/05/2022,N,N,?,?,1,MONTHS,22/03/2031,3.250000000,2.000000000,Y,FLOATING,1.250000000,?,STD REPYMT,376059.41,148960.39,1340.68000000,0,380943.0,30/06/2022,55 years and above,FULLY RELEASED,1.250000000,STD REPYMT,INV,Wilayah Persekutuan Kuala Lumpur,Flat/Apartment Unit,634905.21,634905.21,LOC1/64016/2017/31577,261.50,60.00000000,634905.21,6,R4,111,Employer,?,?,01/01/1900,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,N,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,31/12/9999,N,01/01/1900,31/12/9999,560606015668,4992458,IC,STAGE1,363.64,423677.50,04. R4,"06. Above RM20,000",REAL ESTATE ACTIVITIES,Female,Chinese,FED. TERRITORY,0.38,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,634905.21,634905.21,634905.21,634905.21,0.6,0.59,03. > 50% to 60%,03. > 50% to 60%,09. >90%,04. Flat/Apartment Unit,01. Investment,02. Up to 10 Years
42547,464016301192,I,?,11721124,H2,H2,320983.0,313407.94,Term Loans,Housing,H2,HOME FINANCING-I,0310IN01,FEDERAL TERRITORY,FED. TERRITORY,KL MAIN,IBS KUALA LUMPUR MAIN,13/12/2017,TAN KEWI YONG,HIGH NETWORTH,CHINESE,FEMALE,Malaysian,66,06/06/1956,9,3582.00000000,MANAGING DIRECTORS AND CHIEF EXECUTIVES,REAL ESTATE ACTIVITIES,"Above RM 20,000",MARRIED,PERSONAL,NON-BUMIPUTRA INDIVIDUAL,CFS-IND,20/01/2022,10/03/2022,?,N,0,0.00000000,0,0.00000000,?,01/04/2022,N,N,?,?,1,MONTHS,10/03/2031,3.250000000,2.000000000,Y,FLOATING,1.250000000,?,STD REPYMT,313407.94,124143.60,1117.32000000,0,320983.0,30/06/2022,55 years and above,FULLY RELEASED,1.250000000,STD REPYMT,OWN,Wilayah Persekutuan Kuala Lumpur,Flat/Apartment Unit,534972.22,534972.22,LOC1/64016/2017/31570,261.50,60.00000000,534972.22,6,R4,111,Employer,?,?,01/01/1900,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,N,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,31/12/9999,N,01/01/1900,31/12/9999,560606015668,4992458,IC,STAGE1,302.56,352511.79,04. R4,"06. Above RM20,000",REAL ESTATE ACTIVITIES,Female,Chinese,FED. TERRITORY,0.31,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,534972.22,534972.22,534972.22,534972.22,0.6,0.59,03. > 50% to 60%,03. > 50% to 60%,09. >90%,04. Flat/Apartment Unit,02. Own,02. Up to 10 Years
72305,464016996442,I,?,11721124,H2,H2,219405.0,218215.10,Term Loans,Housing,H2,HOME FINANCING-I,0310RI01,FEDERAL TERRITORY,FED. TERRITORY,KL MAIN,IBS KUALA LUMPUR MAIN,13/12/2017,TAN KEWI YONG,HIGH NETWORTH,CHINESE,FEMALE,Malaysian,66,06/06/1956,9,2449.00000000,MANAGING DIRECTORS AND CHIEF EXECUTIVES,REAL ESTATE ACTIVITIES,"Above RM 20,000",MARRIED,PERSONAL,NON-BUMIPUTRA INDIVIDUAL,CFS-IND,26/04/2022,26/04/2022,?,N,0,0.00000000,0,0.00000000,?,01/06/2022,N,N,?,?,1,MONTHS,26/04/2031,3.250000000,2.000000000,Y,FLOATING,1.250000000,?,STD REPYMT,218215.10,146942.48,1914.12000000,0,219405.0,30/06/2022,55 years and above,FULLY RELEASED,1.250000000,STD REPYMT,INV,Wilayah Persekutuan Kuala Lumpur,Flat/Apartment Unit,365676.08,365676.08,LOC1/64016/2017/31580,261.50,60.00000000,365676.08,6,R6,111,Employer,?,?,01/01/1900,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,N,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,31/12/9999,N,01/01/1900,31/12/9999,560606015668,4992458,IC,STAGE1,667.97,246113.89,06. R6,"06. Above RM20,000",REAL ESTATE ACTIVITIES,Female,Chinese,FED. TERRITORY,0.22,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,365676.08,365676.08,365676.08,365676.08,0.6,0.60,03. > 50% to 60%,03. > 50% to 60%,09. >90%,04. Flat/Apartment Unit,01. Investment,02. Up to 10 Years
108640,464016300955,I,?,11721124,H2,H2,310257.0,306325.79,Term Loans,Housing,H2,HOME FINANCING-I,0310RI01,FEDERAL TERRITORY,FED. TERRITORY,KL MAIN,IBS KUALA LUMPUR MAIN,13/12/2017,TAN KEWI YONG,HIGH NETWORTH,CHINESE,FEMALE,Malaysian,66,06/06/1956,9,3463.00000000,MANAGING DIRECTORS AND CHIEF EXECUTIVES,REAL ESTATE ACTIVITIES,"Above RM 20,000",MARRIED,PERSONAL,NON-BUMIPUTRA INDIVIDUAL,CFS-IND,12/01/2022,18/03/2022,?,N,0,0.00000000,0,0.00000000,?,01/05/2022,N,N,?,?,1,MONTHS,18/03/2031,3.250000000,2.000000000,Y,FLOATING,1.250000000,?,STD REPYMT,306325.79,121338.30,1092.07000000,0,310257.0,30/06/2022,55 years and above,FULLY RELEASED,1.250000000,STD REPYMT,INV,Wilayah Persekutuan Kuala Lumpur,Flat/Apartment Unit,517095.12,517095.12,LOC1/64016/2017/31559,261.50,?,517095.12,6,R4,111,Employer,?,?,01/01/1900,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,N,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,31/12/9999,N,01/01/1900,31/12/9999,560606015668,4992458,IC,STAGE1,296.21,345109.82,04. R4,"06. Above RM20,000",REAL ESTATE ACTIVITIES,Female,Chinese,FED. TERRITORY,0.31,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,517095.12,517095.12,517095.12,517095.12,0.6,0.59,03. > 50% to 60%,03. > 50% to 60%,09. >90%,04. Flat/Apartment Unit,01. Investment,02. Up to 10 Years
137999,464016996719,I,?,11721124,H2,H2,377349.0,368443.58,Term Loans,Housing,H2,HOME FINANCING-I,0310RI01,FEDERAL TERRITORY,FED. TERRITORY,KL MAIN,IBS KUALA LUMPUR MAIN,13/12/2017,TAN KEWI YONG,HIGH NETWORTH,CHINESE,FEMALE,Malaysian,66,06/06/1956,9,4211.00000000,MANAGING DIRECTORS AND CHIEF EXECUTIVES,REAL ESTATE ACTIVITIES,"Above RM 20,000",MARRIED,PERSONAL,NON-BUMIPUTRA INDIVIDUAL,CFS-IND,29/01/2021,10/03/2022,?,N,0,0.00000000,0,0.00000000,?,01/04/2022,N,N,?,?,1,MONTHS,10/03/2031,3.250000000,2.000000000,Y,FLOATING,1.250000000,?,STD REPYMT,368443.58,46733.92,284.19000000,0,377349.0,30/06/2022,55 years and above,FULLY RELEASED,1.250000000,STD REPYMT,INV,Wilayah Persekutuan Kuala Lumpur,Flat/Apartment Unit,628916.38,628916.38,LOC1/64016/2017/31574,261.50,60.00000000,628916.38,6,R2,111,Employer,?,?,01/01/1900,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,N,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,31/12/9999,N,01/01/1900,31/12/9999,560606015668,4992458,IC,STAGE1,70.65,414411.91,02. R2,"06. Above RM20,000",REAL ESTATE ACTIVITIES,Female,Chinese,FED. TERRITORY,0.37,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,628916.38,628916.38,628916.38,628916.38,0.6,0.59,03. > 50% to 60%,03. > 50% to 60%,09. >90%,04. Flat/Apartment Unit,01. Investment,02. Up to 10 Years
181643,464016301920,I,?,11721124,H2,H2,219137.0,216311.75,Term Loans,Housing,H2,HOME FINANCING-I,0310RI01,FEDERAL TERRITORY,FED. TERRITORY,KL MAIN,IBS KUALA LUMPUR MAIN,13/12/2017,TAN KEWI YONG,HIGH NETWORTH,CHINESE,FEMALE,Malaysian,66,06/06/1956,9,2446.00000000,MANAGING DIRECTORS AND CHIEF EXECUTIVES,REAL ESTATE ACTIVITIES,"Above RM 20,000",MARRIED,PERSONAL,NON-BUMIPUTRA INDIVIDUAL,CFS-IND,11/03/2022,11/03/2022,?,N,0,0.00000000,0,0.00000000,?,01/05/2022,N,N,?,?,1,MONTHS,11/03/2031,3.250000000,2.000000000,Y,FLOATING,1.250000000,?,STD REPYMT,216311.75,145660.79,1897.43000000,0,219137.0,30/06/2022,55 years and above,FULLY RELEASED,1.250000000,STD REPYMT,INV,Wilayah Persekutuan Kuala Lumpur,Flat/Apartment Unit,365229.16,365229.16,LOC1/64016/2017/31583,261.50,60.00000000,365229.16,6,R6,111,Employer,?,?,01/01/1900,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,N,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,31/12/9999,N,01/01/1900,31/12/9999,560606015668,4992458,IC,STAGE1,661.39,243689.96,06. R6,"06. Above RM20,000",REAL ESTATE ACTIVITIES,Female,Chinese,FED. TERRITORY,0.22,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,365229.16,365229.16,365229.16,365229.16,0.6,0.59,03. > 50% to 60%,03. > 50% to 60%,09. >90%,04. Flat/Apartment Unit,01. Investment,02. Up to 10 Years
223437,464016999490,I,?,11721124,H2,H2,220317.0,217491.69,Term Loans,Housing,H2,HOME FINANCING-I,0310RI01,FEDERAL TERRITORY,FED. TERRITORY,KL MAIN,IBS KUALA LUMPUR MAIN,13/12/2017,TAN KEWI YONG,HIGH NETWORTH,CHINESE,FEMALE,Malaysian,66,06/06/1956,9,2459.00000000,MANAGING DIRECTORS AND CHIEF EXECUTIVES,REAL ESTATE ACTIVITIES,"Above RM 20,000",MARRIED,PERSONAL,NON-BUMIPUTRA INDIVIDUAL,CFS-IND,11/10/2021,22/03/2022,?,N,0,0.00000000,0,0.00000000,?,01/05/2022,N,N,?,?,1,MONTHS,22/03/2031,3.250000000,2.000000000,Y,FLOATING,1.250000000,?,STD REPYMT,217491.69,86150.34,775.37000000,0,220317.0,30/06/2022,55 years and above,FULLY RELEASED,1.250000000,STD REPYMT,INV,Wilayah Persekutuan Kuala Lumpur,Flat/Apartment Unit,367195.64,367195.64,LOC1/64016/2017/31589,261.50,60.00000000,367195.64,6,R4,111,Employer,?,?,01/01/1900,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,N,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,31/12/9999,N,01/01/1900,31/12/9999,560606015668,4992458,IC,STAGE1,210.30,245024.40,04. R4,"06. Above RM20,000",REAL ESTATE ACTIVITIES,Female,Chinese,FED. TERRITORY,0.22,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,367195.64,367195.64,367195.64,367195.64,0.6,0.59,03. > 50% to 60%,03. > 50% to 60%,09. >90%,04. Flat/Apartment Unit,01. Investment,02. Up to 10 Years
259402,464016999453,I,?,11721124,H2,H2,219405.0,216624.83,Term Loans,Housing,H2,HOME FINANCING-I,0310RI01,FEDERAL TERRITORY,FED. TERRITORY,KL MAIN,IBS KUALA LUMPUR MAIN,13/12/2017,TAN KEWI YONG,HIGH NETWORTH,CHINESE,FEMALE,Malaysian,66,06/06/1956,9,2449.00000000,MANAGING DIRECTORS AND CHIEF EXECUTIVES,REAL ESTATE ACTIVITIES,"Above RM 20,000",MARRIED,PERSONAL,NON-BUMIPUTRA INDIVIDUAL,CFS-IND,15/10/2021,18/03/2022,?,N,0,0.00000000,0,0.00000000,?,01/05/2022,N,N,?,?,1,MONTHS,18/03/2031,3.250000000,2.000000000,Y,FLOATING,1.250000000,?,STD REPYMT,216624.83,85806.97,772.28000000,0,219405.0,30/06/2022,55 years and above,FULLY RELEASED,1.250000000,STD REPYMT,INV,Wilayah Persekutuan Kuala Lumpur,Flat/Apartment Unit,365676.08,365676.08,LOC1/64016/2017/31578,261.50,60.00000000,365676.08,6,R4,111,Employer,?,?,01/01/1900,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,N,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,31/12/9999,N,01/01/1900,31/12/9999,560606015668,4992458,IC,STAGE1,209.47,244050.80,04. R4,"06. Above RM20,000",REAL ESTATE ACTIVITIES,Female,Chinese,FED. TERRITORY,0.22,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,365676.08,365676.08,365676.08,365676.08,0.6,0.59,03. > 50% to 60%,03. > 50% to 60%,09. >90%,04. Flat/Apartment Unit,01. Investment,02. Up to 10 Years
261327,464016300962,I,?,11721124,H2,H2,220585.0,217755.99,Term Loans,Housing,H2,HOME FINANCING-I,0310RI01,FEDERAL TERRITORY,FED. TERRITORY,KL MAIN,IBS KUALA LUMPUR MAIN,13/12/2017,TAN KEWI YONG,HIGH NETWORTH,CHINESE,FEMALE,Malaysian,66,06/06/1956,9,2462.00000000,MANAGING DIRECTORS AND CHIEF EXECUTIVES,REAL ESTATE ACTIVITIES,"Above RM 20,000",MARRIED,PERSONAL,NON-BUMIPUTRA INDIVIDUAL,CFS-IND,12/01/2022,22/03/2022,?,N,0,0.00000000,0,0.00000000,?,01/05/2022,N,N,?,?,1,MONTHS,22/03/2031,3.250000000,2.000000000,Y,FLOATING,1.250000000,?,STD REPYMT,217755.99,86255.04,776.31000000,0,220585.0,30/06/2022,55 years and above,FULLY RELEASED,1.250000000,STD REPYMT,INV,Wilayah Persekutuan Kuala Lumpur,Flat/Apartment Unit,367642.57,367642.57,LOC1/64016/2017/31567,261.50,60.00000000,367642.57,6,R4,111,Employer,?,?,01/01/1900,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,N,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,31/12/9999,N,01/01/1900,31/12/9999,560606015668,4992458,IC,STAGE1,210.56,245321.98,04. R4,"06. Above RM20,000",REAL ESTATE ACTIVITIES,Female,Chinese,FED. TERRITORY,0.22,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,367642.57,367642.57,367642.57,367642.57,0.6,0.59,03. > 50% to 60%,03. > 50% to 60%,09. >90%,04. Flat/Apartment Unit,01. Investment,02. Up to 10 Years
326047,464016999430,I,?,11721124,H2,H2,219995.0,217174.63,Term Loans,Housing,H2,HOME FINANCING-I,0310RI01,FEDERAL TERRITORY,FED. TERRITORY,KL MAIN,IBS KUALA LUMPUR MAIN,13/12/2017,TAN KEWI YONG,HIGH NETWORTH,CHINESE,FEMALE,Malaysian,66,06/06/1956,9,2455.00000000,MANAGING DIRECTORS AND CHIEF EXECUTIVES,REAL ESTATE ACTIVITIES,"Above RM 20,000",MARRIED,PERSONAL,NON-BUMIPUTRA INDIVIDUAL,CFS-IND,08/10/2021,22/03/2022,?,N,0,0.00000000,0,0.00000000,?,01/05/2022,N,N,?,?,1,MONTHS,22/03/2031,3.250000000,2.000000000,Y,FLOATING,1.250000000,?,STD REPYMT,217174.63,86024.75,774.24000000,0,219995.0,30/06/2022,55 years and above,FULLY RELEASED,1.250000000,STD REPYMT,INV,Wilayah Persekutuan Kuala Lumpur,Flat/Apartment Unit,366659.33,366659.33,LOC1/64016/2017/31585,261.50,60.00000000,366659.33,6,R4,111,Employer,?,?,01/01/1900,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,N,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,31/12/9999,N,01/01/1900,31/12/9999,560606015668,4992458,IC,STAGE1,210.00,244673.45,04. R4,"06. Above RM20,000",REAL ESTATE ACTIVITIES,Female,Chinese,FED. TERRITORY,0.22,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,366659.33,366659.33,366659.33,366659.33,0.6,0.59,03. > 50% to 60%,03. > 50% to 60%,09. >90%,04. Flat/Apartment Unit,01. Investment,02. Up to 10 Years
341575,464016999446,I,?,11721124,H2,H2,220317.0,217491.69,Term Loans,Housing,H2,HOME FINANCING-I,0310IN01,FEDERAL TERRITORY,FED. TERRITORY,KL MAIN,IBS KUALA LUMPUR MAIN,13/12/2017,TAN KEWI YONG,HIGH NETWORTH,CHINESE,FEMALE,Malaysian,66,06/06/1956,9,2459.00000000,MANAGING DIRECTORS AND CHIEF EXECUTIVES,REAL ESTATE ACTIVITIES,"Above RM 20,000",MARRIED,PERSONAL,NON-BUMIPUTRA INDIVIDUAL,CFS-IND,08/10/2021,22/03/2022,?,N,0,0.00000000,0,0.00000000,?,01/05/2022,N,N,?,?,1,MONTHS,22/03/2031,3.250000000,2.000000000,Y,FLOATING,1.250000000,?,STD REPYMT,217491.69,86150.34,775.37000000,0,220317.0,30/06/2022,55 years and above,FULLY RELEASED,1.250000000,STD REPYMT,OWN,Wilayah Persekutuan Kuala Lumpur,Flat/Apartment Unit,367195.64,367195.64,LOC1/64016/2017/31587,261.50,60.00000000,367195.64,6,R4,111,Employer,?,?,01/01/1900,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,N,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,31/12/9999,N,01/01/1900,31/12/9999,560606015668,4992458,IC,STAGE1,210.30,245024.40,04. R4,"06. Above RM20,000",REAL ESTATE ACTIVITIES,Female,Chinese,FED. TERRITORY,0.22,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,367195.64,367195.64,367195.64,367195.64,0.6,0.59,03. > 50% to 60%,03. > 50% to 60%,09. >90%,04. Flat/Apartment Unit,02. Own,02. Up to 10 Years
346814,464016994501,I,?,11721124,H2,H2,219995.0,217207.88,Term Loans,Housing,H2,HOME FINANCING-I,0310RI01,FEDERAL TERRITORY,FED. TERRITORY,KL MAIN,IBS KUALA LUMPUR MAIN,13/12/2017,TAN KEWI YONG,HIGH NETWORTH,CHINESE,FEMALE,Malaysian,66,06/06/1956,9,2455.00000000,MANAGING DIRECTORS AND CHIEF EXECUTIVES,REAL ESTATE ACTIVITIES,"Above RM 20,000",MARRIED,PERSONAL,NON-BUMIPUTRA INDIVIDUAL,CFS-IND,05/01/2021,18/03/2022,?,N,0,0.00000000,0,0.00000000,?,01/05/2022,N,N,?,?,1,MONTHS,18/03/2031,3.250000000,2.000000000,Y,FLOATING,1.250000000,?,STD REPYMT,217207.88,27550.97,167.54000000,0,219995.0,30/06/2022,55 years and above,FULLY RELEASED,1.250000000,STD REPYMT,INV,Wilayah Persekutuan Kuala Lumpur,Flat/Apartment Unit,366659.33,366659.33,LOC1/64016/2017/31584,261.50,60.00000000,366659.33,6,R2,111,Employer,?,?,01/01/1900,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,N,01/01/1900,?,?,?,?,?,?,?,?,?,?,?,?,N,01/01/1900,31/12/9999,N,01/01/1900,31/12/9999,560606015668,4992458,IC,STAGE1,41.72,244716.57,02. R2,"06. Above RM20,000",REAL ESTATE ACTIVITIES,Female,Chinese,FED. TERRITORY,0.22,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,366659.33,366659.33,366659.33,366659.33,0.6,0.59,03. > 50% to 60%,03. > 50% to 60%,09. >90%,04. Flat/Apartment Unit,01. Investment,02. Up to 10 Years