In [1]:
import pandas as pd
import numpy as np

#warnings.filterwarnings('ignore')
pd.set_option("display.max_columns", None) 
pd.set_option("display.max_colwidth", 1000) #huruf dlm column
pd.set_option("display.max_rows", 100)
pd.set_option("display.precision", 2) #2 titik perpuluhan

Location = r"C:\Users\syahidhalid\Syahid_PC\Analytics - SPD\Loan Database"
ECR1 = "ECR 2023"
ECR2 = "ECR 2024"

#df_ori = pd.read_excel(r"C:\Users\syahidhalid\OneDrive - Export-Import Bank of Malaysia (EXIM Bank)\Exim _ Syahid\Analytics\Loan Growth Model\2024\Above SLA Criteria\TAT - working.xlsx", sheet_name='working')
ECR_2304 = pd.read_excel(str(Location)+"\\"+str(ECR1)+".xlsx", sheet_name='Apr23', header=0)
ECR_2305 = pd.read_excel(str(Location)+"\\"+str(ECR1)+".xlsx", sheet_name='May23', header=0)
ECR_2306 = pd.read_excel(str(Location)+"\\"+str(ECR1)+".xlsx", sheet_name='Jun23', header=0)
ECR_2307 = pd.read_excel(str(Location)+"\\"+str(ECR1)+".xlsx", sheet_name='Jul23', header=0)
ECR_2308 = pd.read_excel(str(Location)+"\\"+str(ECR1)+".xlsx", sheet_name='Aug23', header=0)
ECR_2309 = pd.read_excel(str(Location)+"\\"+str(ECR1)+".xlsx", sheet_name='Sep23', header=0)
ECR_2310 = pd.read_excel(str(Location)+"\\"+str(ECR1)+".xlsx", sheet_name='Oct23', header=0)
ECR_2311 = pd.read_excel(str(Location)+"\\"+str(ECR1)+".xlsx", sheet_name='Nov23', header=0)
ECR_2312 = pd.read_excel(str(Location)+"\\"+str(ECR1)+".xlsx", sheet_name='Dec23', header=0)
ECR_2401 = pd.read_excel(str(Location)+"\\"+str(ECR2)+".xlsx", sheet_name='Jan24', header=0)
ECR_2402 = pd.read_excel(str(Location)+"\\"+str(ECR2)+".xlsx", sheet_name='Feb24', header=0)
ECR_2403 = pd.read_excel(str(Location)+"\\"+str(ECR2)+".xlsx", sheet_name='Mar24', header=0)
ECR_2404 = pd.read_excel(str(Location)+"\\"+str(ECR2)+".xlsx", sheet_name='Apr24', header=0)

In [9]:

ECR_2404['OS_%'] = ECR_2404['Total Outstanding (MYR)']/sum(ECR_2404['Total Outstanding (MYR)'])
ECR_2404['INT_%'] = ECR_2404['Interest Outstanding (MYR)']/sum(ECR_2404['Interest Outstanding (MYR)'])
ECR_2404['CHARGES_%'] = ECR_2404['Other Charges (MYR)']/sum(ECR_2404['Other Charges (MYR)'])
ECR_2404['DISBURSE_%'] = ECR_2404['Disbursement/Drawdown (MYR)']/(ECR_2404['Total Outstanding (MYR)'])
ECR_2404['REPAYMENT_%'] = ECR_2404['Repayment \n(MYR)']/(ECR_2404['Total Outstanding (MYR)'])

In [11]:

ECR_2403['OS_%'] = ECR_2403['Total Outstanding (MYR)']/sum(ECR_2403['Total Outstanding (MYR)'])
ECR_2403['INT_%'] = ECR_2403['Interest Outstanding (MYR)']/sum(ECR_2403['Interest Outstanding (MYR)'])
ECR_2403['CHARGES_%'] = ECR_2403['Other Charges (MYR)']/sum(ECR_2403['Other Charges (MYR)'])
ECR_2403['DISBURSE_%'] = ECR_2403['Disbursement/Drawdown (MYR)']/(ECR_2403['Total Outstanding (MYR)'])
ECR_2403['REPAYMENT_%'] = ECR_2403['Repayment \n(MYR)']/(ECR_2403['Total Outstanding (MYR)'])

In [12]:

ECR_2402['OS_%'] = ECR_2402['Total Outstanding (MYR)']/sum(ECR_2402['Total Outstanding (MYR)'])
ECR_2402['INT_%'] = ECR_2402['Interest Outstanding (MYR)']/sum(ECR_2402['Interest Outstanding (MYR)'])
ECR_2402['CHARGES_%'] = ECR_2402['Other Charges (MYR)']/sum(ECR_2402['Other Charges (MYR)'])
ECR_2402['DISBURSE_%'] = ECR_2402['Disbursement/Drawdown (MYR)']/(ECR_2402['Total Outstanding (MYR)'])
ECR_2402['REPAYMENT_%'] = ECR_2402['Repayment \n(MYR)']/(ECR_2402['Total Outstanding (MYR)'])

In [13]:

ECR_2401['OS_%'] = ECR_2401['Total Outstanding (MYR)']/sum(ECR_2401['Total Outstanding (MYR)'])
ECR_2401['INT_%'] = ECR_2401['Interest Outstanding (MYR)']/sum(ECR_2401['Interest Outstanding (MYR)'])
ECR_2401['CHARGES_%'] = ECR_2401['Other Charges (MYR)']/sum(ECR_2401['Other Charges (MYR)'])
ECR_2401['DISBURSE_%'] = ECR_2401['Disbursement/Drawdown (MYR)']/(ECR_2401['Total Outstanding (MYR)'])
ECR_2401['REPAYMENT_%'] = ECR_2401['Repayment \n(MYR)']/(ECR_2401['Total Outstanding (MYR)'])

In [14]:

ECR_2312['OS_%'] = ECR_2312['Total Outstanding (MYR)']/sum(ECR_2312['Total Outstanding (MYR)'])
ECR_2312['INT_%'] = ECR_2312['Interest Outstanding (MYR)']/sum(ECR_2312['Interest Outstanding (MYR)'])
ECR_2312['CHARGES_%'] = ECR_2312['Other Charges (MYR)']/sum(ECR_2312['Other Charges (MYR)'])
ECR_2312['DISBURSE_%'] = ECR_2312['Disbursement/Drawdown (MYR)']/(ECR_2312['Total Outstanding (MYR)'])
ECR_2312['REPAYMENT_%'] = ECR_2312['Repayment \n(MYR)']/(ECR_2312['Total Outstanding (MYR)'])

In [15]:

ECR_2311['OS_%'] = ECR_2311['Total Outstanding (MYR)']/sum(ECR_2311['Total Outstanding (MYR)'])
ECR_2311['INT_%'] = ECR_2311['Interest Outstanding (MYR)']/sum(ECR_2311['Interest Outstanding (MYR)'])
ECR_2311['CHARGES_%'] = ECR_2311['Other Charges (MYR)']/sum(ECR_2311['Other Charges (MYR)'])
ECR_2311['DISBURSE_%'] = ECR_2311['Disbursement/Drawdown (MYR)']/(ECR_2311['Total Outstanding (MYR)'])
ECR_2311['REPAYMENT_%'] = ECR_2311['Repayment \n(MYR)']/(ECR_2311['Total Outstanding (MYR)'])

In [16]:

ECR_2310['OS_%'] = ECR_2310['Total Outstanding (MYR)']/sum(ECR_2310['Total Outstanding (MYR)'])
ECR_2310['INT_%'] = ECR_2310['Interest Outstanding (MYR)']/sum(ECR_2310['Interest Outstanding (MYR)'])
ECR_2310['CHARGES_%'] = ECR_2310['Other Charges (MYR)']/sum(ECR_2310['Other Charges (MYR)'])
ECR_2310['DISBURSE_%'] = ECR_2310['Disbursement/Drawdown (MYR)']/(ECR_2310['Total Outstanding (MYR)'])
ECR_2310['REPAYMENT_%'] = ECR_2310['Repayment \n(MYR)']/(ECR_2310['Total Outstanding (MYR)'])

In [17]:

ECR_2309['OS_%'] = ECR_2309['Total Outstanding (MYR)']/sum(ECR_2309['Total Outstanding (MYR)'])
ECR_2309['INT_%'] = ECR_2309['Interest Outstanding (MYR)']/sum(ECR_2309['Interest Outstanding (MYR)'])
ECR_2309['CHARGES_%'] = ECR_2309['Other Charges (MYR)']/sum(ECR_2309['Other Charges (MYR)'])
ECR_2309['DISBURSE_%'] = ECR_2309['Disbursement/Drawdown (MYR)']/(ECR_2309['Total Outstanding (MYR)'])
ECR_2309['REPAYMENT_%'] = ECR_2309['Repayment \n(MYR)']/(ECR_2309['Total Outstanding (MYR)'])

In [18]:

ECR_2308['OS_%'] = ECR_2308['Total Outstanding (MYR)']/sum(ECR_2308['Total Outstanding (MYR)'])
ECR_2308['INT_%'] = ECR_2308['Interest Outstanding (MYR)']/sum(ECR_2308['Interest Outstanding (MYR)'])
ECR_2308['CHARGES_%'] = ECR_2308['Other Charges (MYR)']/sum(ECR_2308['Other Charges (MYR)'])
ECR_2308['DISBURSE_%'] = ECR_2308['Disbursement/Drawdown (MYR)']/(ECR_2308['Total Outstanding (MYR)'])
ECR_2308['REPAYMENT_%'] = ECR_2308['Repayment \n(MYR)']/(ECR_2308['Total Outstanding (MYR)'])

In [19]:

ECR_2307['OS_%'] = ECR_2307['Total Outstanding (MYR)']/sum(ECR_2307['Total Outstanding (MYR)'])
ECR_2307['INT_%'] = ECR_2307['Interest Outstanding (MYR)']/sum(ECR_2307['Interest Outstanding (MYR)'])
ECR_2307['CHARGES_%'] = ECR_2307['Other Charges (MYR)']/sum(ECR_2307['Other Charges (MYR)'])
ECR_2307['DISBURSE_%'] = ECR_2307['Disbursement/Drawdown (MYR)']/(ECR_2307['Total Outstanding (MYR)'])
ECR_2307['REPAYMENT_%'] = ECR_2307['Repayment \n(MYR)']/(ECR_2307['Total Outstanding (MYR)'])

In [20]:

ECR_2306['OS_%'] = ECR_2306['Total Outstanding (MYR)']/sum(ECR_2306['Total Outstanding (MYR)'])
ECR_2306['INT_%'] = ECR_2306['Interest Outstanding (MYR)']/sum(ECR_2306['Interest Outstanding (MYR)'])
ECR_2306['CHARGES_%'] = ECR_2306['Other Charges (MYR)']/sum(ECR_2306['Other Charges (MYR)'])
ECR_2306['DISBURSE_%'] = ECR_2306['Disbursement/Drawdown (MYR)']/(ECR_2306['Total Outstanding (MYR)'])
ECR_2306['REPAYMENT_%'] = ECR_2306['Repayment \n(MYR)']/(ECR_2306['Total Outstanding (MYR)'])

In [21]:

ECR_2305['OS_%'] = ECR_2305['Total Outstanding (MYR)']/sum(ECR_2305['Total Outstanding (MYR)'])
ECR_2305['INT_%'] = ECR_2305['Interest Outstanding (MYR)']/sum(ECR_2305['Interest Outstanding (MYR)'])
ECR_2305['CHARGES_%'] = ECR_2305['Other Charges (MYR)']/sum(ECR_2305['Other Charges (MYR)'])
ECR_2305['DISBURSE_%'] = ECR_2305['Disbursement/Drawdown (MYR)']/(ECR_2305['Total Outstanding (MYR)'])
ECR_2305['REPAYMENT_%'] = ECR_2305['Repayment \n(MYR)']/(ECR_2305['Total Outstanding (MYR)'])

In [22]:

ECR_2304['OS_%'] = ECR_2304['Total Outstanding (MYR)']/sum(ECR_2304['Total Outstanding (MYR)'])
ECR_2304['INT_%'] = ECR_2304['Interest Outstanding (MYR)']/sum(ECR_2304['Interest Outstanding (MYR)'])
ECR_2304['CHARGES_%'] = ECR_2304['Other Charges (MYR)']/sum(ECR_2304['Other Charges (MYR)'])
ECR_2304['DISBURSE_%'] = ECR_2304['Disbursement/Drawdown (MYR)']/(ECR_2304['Total Outstanding (MYR)'])
ECR_2304['REPAYMENT_%'] = ECR_2304['Repayment \n(MYR)']/(ECR_2304['Total Outstanding (MYR)'])

In [24]:

ECR_2304['Position'] = '2023-04'
ECR_2305['Position'] = '2023-05'
ECR_2306['Position'] = '2023-06'
ECR_2307['Position'] = '2023-07'
ECR_2308['Position'] = '2023-08'
ECR_2309['Position'] = '2023-09'
ECR_2310['Position'] = '2023-10'
ECR_2311['Position'] = '2023-11'
ECR_2312['Position'] = '2023-12'
ECR_2401['Position'] = '2024-01'
ECR_2402['Position'] = '2024-02'
ECR_2403['Position'] = '2024-03'
ECR_2404['Position'] = '2024-04'

In [25]:
ECR_2304.columns = ECR_2305.columns = ECR_2306.columns = ECR_2307.columns = ECR_2308.columns = ECR_2309.columns = ECR_2310.columns = ECR_2311.columns = ECR_2312.columns = ECR_2401.columns = ECR_2402.columns = ECR_2403.columns = ECR_2404.columns

ECRFIN = pd.concat([ECR_2304,
                    ECR_2305,
                    ECR_2306,
                    ECR_2307,
                    ECR_2308,
                    ECR_2309,
                    ECR_2310,
                    ECR_2311,
                    ECR_2312,
                    ECR_2401,
                    ECR_2402,
                    ECR_2403,
                    ECR_2404])

ECRFIN.to_csv(r"C:\Users\syahidhalid\Syahid_PC\Analytics - FAD\Dashboard ECR & LDB\Dataset\\ECR_POWERBI.txt", index = False)

In [12]:
sum(ECR_2304['OS_%'])

1.0

In [23]:
ECR_2304.sort_values(by=['INT_%'],ascending=False).head(3)

,No.,Company ID,Group,Company,Application System Code,Master Account No,Sub Account No,Nature of Account,Facility,Facility Currency,Type of Financing,Status,Corporate Status,Country Exposure,Profit/Interest Margin,Cost/Principal Outstanding (MYR),Interest Outstanding (MYR),Other Charges (MYR),Total Outstanding (MYR),Disbursement/Drawdown (MYR),Cumulative Disbursement/\nDrawdown \n(MYR),Repayment \n(MYR),Cumulative Repayment \n(MYR),OS_%,INT_%,CHARGES_%,DISBURSE_%,REPAYMENT_%
38,39,ECR 020_1,Public Bank Berhad,Public Bank Berhad (Conv),EFD,PUBLIC BANK,PUBLIC BANK,Trade,ECR,MYR,Conventional,Active,SME,Malaysia,3.35,9.15e+06,127020.65,95,9.28e+06,1.66e+06,6.83e+06,4.00e+06,1.16e+07,0.17,0.61,0.15,0.18,0.43
34,35,ECR 018_1,Maybank Berhad,Maybank Berhad (Conv),EFD,MALAYAN,MALAYAN,Trade,ECR,MYR,Conventional,Active,SME,Malaysia,3.35,2.33e+07,65686.61,80,2.33e+07,1.11e+06,1.07e+07,2.35e+06,2.87e+07,0.43,0.32,0.12,0.05,0.10
40,41,ECR 021_1,RHB Bank Berhad,RHB Bank Berhad (Conv),EFD,RHB BANK,RHB BANK,Trade,ECR,MYR,Conventional,Active,SME,Malaysia,3.35,2.00e+06,4859.10,35,2.01e+06,5.51e+05,2.00e+06,4.46e+05,2.71e+06,0.04,0.02,0.05,0.27,0.22

In [ ]:
#old

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import matplotlib.pyplot as plt


LDB1 = "LBD 202312 - 202301 (CSP Sector)"
LDB2 = "LBD 202412 - 202401 (CSP Sector)"

Location = r"C:\\Users\\syahidhalid\\Syahid PC\\Analytics\\Loan Database"
ECR1 = "ECR 2023"
ECR2 = "ECR 2024"
LDB1 = "LBD 202312 - 202301 (CSP Sector)"
LDB2 = "LBD 202412 - 202401 (CSP Sector)"

#df_ori = pd.read_excel(r"C:\Users\syahidhalid\OneDrive - Export-Import Bank of Malaysia (EXIM Bank)\Exim _ Syahid\Analytics\Loan Growth Model\2024\Above SLA Criteria\TAT - working.xlsx", sheet_name='working')
ECR_1 = pd.read_excel(str(Location)+"\\"+str(ECR1)+".xlsx", sheet_name='Oct23', header=0)
ECR_2 = pd.read_excel(str(Location)+"\\"+str(ECR1)+".xlsx", sheet_name='Nov23', header=0)
ECR_3 = pd.read_excel(str(Location)+"\\"+str(ECR1)+".xlsx", sheet_name='Dec23', header=0)
ECR_4 = pd.read_excel(str(Location)+"\\"+str(ECR2)+".xlsx", sheet_name='Jan24', header=0)
ECR_5 = pd.read_excel(str(Location)+"\\"+str(ECR2)+".xlsx", sheet_name='Feb24', header=0)
ECR_6 = pd.read_excel(str(Location)+"\\"+str(ECR2)+".xlsx", sheet_name='Mar24', header=0)

ECR_1.shape
ECR_2.shape
ECR_3.shape
ECR_4.shape
ECR_5.shape
ECR_6.shape

ECR_1['Position'] = '31/10/2023'
ECR_2['Position'] = '30/11/2023'
ECR_3['Position'] = '31/12/2023'
ECR_4['Position'] = '31/01/2024'
ECR_5['Position'] = '29/02/2024'
ECR_6['Position'] = '31/03/2024'


LDB_1 = pd.read_excel(str(Location)+"\\"+str(LDB1)+".xlsx", sheet_name='Oct23', header=0)
LDB_2 = pd.read_excel(str(Location)+"\\"+str(LDB1)+".xlsx", sheet_name='Nov23', header=0)
LDB_3 = pd.read_excel(str(Location)+"\\"+str(LDB1)+".xlsx", sheet_name='Dec23', header=0)
LDB_4 = pd.read_excel(str(Location)+"\\"+str(LDB2)+".xlsx", sheet_name='Jan24', header=0)
LDB_5 = pd.read_excel(str(Location)+"\\"+str(LDB2)+".xlsx", sheet_name='Feb24', header=0)
LDB_6 = pd.read_excel(str(Location)+"\\"+str(LDB2)+".xlsx", sheet_name='Mar24', header=0)

LDB_1.shape
LDB_2.shape
LDB_3.shape
LDB_4.shape
LDB_5.shape
LDB_6.shape

#df_ori.head()

ECR_1.columns=ECR_2.columns=ECR_3.columns=ECR_4.columns=ECR_5.columns=ECR_6.columns
LDB_1.columns=LDB_2.columns=LDB_3.columns=LDB_4.columns=LDB_5.columns=LDB_6.columns


ECRFIN = pd.concat([ECR_1,ECR_2,ECR_3,ECR_4,ECR_5,ECR_6])

LDBFIN = pd.concat([LDB_1,LDB_2,LDB_3,LDB_4,LDB_5,LDB_6])

ECRFIN.to_csv(r"C:\Users\syahidhalid\Syahid PC\FAD - Analytics\\ECR_POWERBI.txt", index = False)
LDBFIN.to_csv(r"C:\Users\syahidhalid\Syahid PC\FAD - Analytics\\LDB_POWERBI.txt", index = False)