In [1]:
import numpy as np
import pandas as pd
import pandasql
import sqlite3

pd.set_option("display.max_columns", None) 
pd.set_option("display.max_colwidth", 1000) #huruf dlm column
pd.set_option("display.max_rows", 100)
pd.set_option("display.precision", 2) #2 titik perpuluhan

In [2]:
date = '20210930'

In [3]:
GB = pd.read_excel(r'T:\MIB Risk Management\Credit Risk Analytics - Historical\02_Data_Source\01_Corporate_Financing\01_Portfolio\\'+date+'\GB Monthly Loan Outstanding as at 30-Sep-2021 v3.xlsx', sheet_name='cb os by mkt seg 2') 
#sheet_name='cb os by mkt seg 2'
#sheet_name='cb os by mkt seg'
#sheet_name='SourceCM'
                   
description = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\Python\User defined\description.xlsx", sheet_name='description')


Report_Corp_CRDM = pd.read_excel(r'T:\MIB Risk Management\Credit Risk Analytics - Historical\02_Data_Source\11_CRRS\\'+date[:4]+'\\'+date+'\Report_Corp_CRDM_'+date+'.xlsx')

In [5]:
CRWA = pd.read_excel(r'T:\MIB Risk Management\Credit Risk Analytics - Historical\02_Data_Source\12_RDMS\\'+date+'\Working\CRWA Sep 2021 Final (Domestic - All except Retail).xlsx', sheet_name='Context Id=162')

In [6]:
List = pd.read_excel(r'T:\MIB Risk Management\Credit Risk Analytics - Historical\02_Data_Source\12_RDMS\\'+date+'\Working\List Master Listing '+date+'-working.xlsx')
#, sheet_name='Sheet2'

In [8]:
GB.columns = GB.columns.str.strip()
GB.columns = GB.columns.str.upper()
GB.columns = GB.columns.str.replace(" ","_")

GB.M_FINANCING_TYPE_CD = GB.M_FINANCING_TYPE_CD.str.strip()
GB.M_FINANCING_TYPE_CD = GB.M_FINANCING_TYPE_CD.str.upper()

In [10]:
GB['M_CUS_NO'] = GB['M_CUS_NO'].astype('Int64').astype('str')

In [30]:
GB.head(1)

,AS_OF_DATE,M_CUS_NO,NAME,DESCRIPTION,STATE_DESC,BRANCH_CODE,CUST_CLASS_CD,NATURE_OF_BUSINESS,ECONOMIC_SECTOR_CD,M_NPL_DATE,M_SUB_MARKET_SEGMENT_CD,M_MARKET_SEGMENT_CD,NPL_FLG,M_PARTIAL_WOFF_FLG,DESCRIPTION.1,M_CUSTOMER_TYPE,M_FULL_WRITEOFF_FLG,M_FINANCING_TYPE_CD,ISO_CURRENCY_CD,M_ACCOUNT_NO,M_NEW_NPL_FLG,M_INTEREST_CODE,M_SOURCE_PROD_TYPE_CD,FACILITY,FACILITY_2,M_BNM_BALANCE_SUM_1,AUTHORISED_LIMIT_SUM,M_APPROVED_LIMIT_SUM,CUR_BOOK_BAL_SUM,MATURITY_DATE,ORIGINATION_DATE,M_MSIC_CODE,INDUSTRY_SECTORIAL_CLASSFICATION,INDUSTRY_SECTORIAL_CLASSFICATION_DESCRIPTION,AVG_BOOK_BAL_SUM,COMMON_COA_ID,ISSUE_DATE,M_STOCK_CODE,M_FOLDER_NAME,M_NEW_ID_NUMBER,CB_GROUP_NAME,AO/AM,AD,DIR,SD,BIZ_SEG,M_BNM_BALANCE_SUM
0,2021-09-30,20686,MOHD RADZI BIN HARUN,KUALA LUMPUR MAIN,FED. TERRITORY,1401.0,500.0,NaN,0310,NaT,3.0,1.0,N,N,Consumer Loans,101.0,N,I,MYR,630010000919,N,46.0,HZK03,RTO,RTO,342624.0,0.0,836640.0,342624.0,2028-03-22,2021-08-12,97000,Household,Household,342624.0,12000.0,2021-08-12,NaN,NaN,650113086395,TBD,TBD,TBD,TBD,TBD,TBD,342624.0

In [31]:
#case 20210630 xde facility
GB.FACILITY = GB.FACILITY.str.strip()
GB.FACILITY = GB.FACILITY.str.upper()

#case 20211231,20220331 nme M_BNM_BALANCE_SUM_1
GB['M_BNM_BALANCE_SUM']=GB['M_BNM_BALANCE_SUM_1']

GB.M_BNM_BALANCE_SUM.fillna(0, inplace=True)

GB1 = GB.iloc[np.where((GB.M_FINANCING_TYPE_CD=='I')&(GB.FACILITY!='RTO'))] #&(GB.FACILITY!='RTO') case 20210630

In [32]:
#case 20211231
#check M_MSIC_CODE kat excel n let type as general sbb klau x dia jd time value

GB1=GB1[['M_CUS_NO','NAME','M_MSIC_CODE','M_BNM_BALANCE_SUM']]

GB1 = GB1.fillna(0).groupby(['M_CUS_NO','NAME','M_MSIC_CODE'])[['M_BNM_BALANCE_SUM']].sum().reset_index().sort_values(by='M_BNM_BALANCE_SUM', ascending=False)


description.columns = description.columns.str.strip()
description.columns = description.columns.str.replace(" ", "_")
description.columns = description.columns.str.upper()

description.ISC_NOB = description.ISC_NOB.map(str)
description.ISC_NOB = description.ISC_NOB.str.strip()
description.ISC_NOB = description.ISC_NOB.str.upper()

GB1.M_MSIC_CODE = GB1.M_MSIC_CODE.map(str)
GB1.M_MSIC_CODE = GB1.M_MSIC_CODE.str.strip()
GB1.M_MSIC_CODE = GB1.M_MSIC_CODE.str.upper()

join_A = GB1.merge(description[['ISC_NOB','INDUSTRIAL_SECTOR_CODE_(ISC_DESC)2','ISC_PARENT']].drop_duplicates().rename(columns = {'ISC_NOB':'M_MSIC_CODE'}), on='M_MSIC_CODE', how='left').drop('M_BNM_BALANCE_SUM', axis=1)

In [33]:
Report_Corp_CRDM.columns = Report_Corp_CRDM.columns.str.strip()
Report_Corp_CRDM.columns = Report_Corp_CRDM.columns.str.upper()
Report_Corp_CRDM.columns = Report_Corp_CRDM.columns.str.replace(" ","_")

Report_Corp_CRDM1 = Report_Corp_CRDM[['GCIF_NUM','RDMS_ADJ_BRR']]

Report_Corp_CRDM1.GCIF_NUM = Report_Corp_CRDM1.GCIF_NUM.map(str)
Report_Corp_CRDM1.GCIF_NUM = Report_Corp_CRDM1.GCIF_NUM.str.strip()
Report_Corp_CRDM1.GCIF_NUM = Report_Corp_CRDM1.GCIF_NUM.str.upper()

join_A.M_CUS_NO = join_A.M_CUS_NO.map(str)
join_A.M_CUS_NO = join_A.M_CUS_NO.str.strip()
join_A.M_CUS_NO = join_A.M_CUS_NO.str.upper()

#case 20210630
#join_A['M_CUS_NO'] = join_A['M_CUS_NO'].str[:-2]
join_B = join_A.merge(Report_Corp_CRDM1.rename(columns = {'GCIF_NUM':'M_CUS_NO'}).drop_duplicates(), on='M_CUS_NO', how='left')

D:\anaconda3\lib\site-packages\pandas\core\generic.py:5303: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [35]:
CRWA.columns = CRWA.columns.str.strip()
CRWA.columns = CRWA.columns.str.upper()
CRWA.columns = CRWA.columns.str.replace(" ","_")

CRWA1 = CRWA[['COUNTERPARTY_ORIGINAL','CUSTOMER_FIELD19','INTERNAL_RATING_ORIGINAL']]

CRWA1.COUNTERPARTY_ORIGINAL = CRWA1.COUNTERPARTY_ORIGINAL.map(str)
CRWA1.COUNTERPARTY_ORIGINAL = CRWA1.COUNTERPARTY_ORIGINAL.str.strip()
CRWA1.COUNTERPARTY_ORIGINAL = CRWA1.COUNTERPARTY_ORIGINAL.str.upper()

join_C = join_B.merge(CRWA1.rename(columns = {'COUNTERPARTY_ORIGINAL':'M_CUS_NO'}).drop_duplicates('M_CUS_NO'), on='M_CUS_NO', how='left').drop_duplicates()

D:\anaconda3\lib\site-packages\pandas\core\generic.py:5303: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [36]:
def PSE_SOV(CUSTOMER_FIELD19):
    if CUSTOMER_FIELD19 == 'PSE(SA)':
        return "PSE"
    elif CUSTOMER_FIELD19 == 'SOV(SA)':
        return "SOV"
#    else:
#        return "Unrated"
join_C['PSE/SOV'] = join_C.CUSTOMER_FIELD19.apply(PSE_SOV)

List.columns = List.columns.str.strip()
List.columns = List.columns.str.upper()
List.columns = List.columns.str.replace(" ","_")

List.GCIF_CHILD = List.GCIF_CHILD.map(str)
List.GCIF_CHILD = List.GCIF_CHILD.str.strip()
List.GCIF_CHILD = List.GCIF_CHILD.str.upper()

join_D = join_C.merge(List.rename(columns={"GCIF_CHILD":"M_CUS_NO"}).drop_duplicates(), on='M_CUS_NO', how='left').drop_duplicates()


#join_D.GCIF_PARENTS = join_D.GCIF_PARENTS.apply(lambda x: f'{x:.0f}')
join_D.GCIF_PARENTS = join_D.GCIF_PARENTS.astype(str)
join_D.GCIF_PARENTS = join_D.GCIF_PARENTS.str.strip()
join_D.GCIF_PARENTS = join_D.GCIF_PARENTS.str.upper()

join_D['GCIF_PARENTS1'] = join_D.GCIF_PARENTS.str[:-2]


join_E = join_D.merge(join_D[['M_CUS_NO','INTERNAL_RATING_ORIGINAL']].rename(columns={'M_CUS_NO':'GCIF_PARENTS1','INTERNAL_RATING_ORIGINAL':'3RD_PARTY'}), on='GCIF_PARENTS1', how='left')


join_E1 = join_E.merge(CRWA1.rename(columns = {'COUNTERPARTY_ORIGINAL':'GCIF_PARENTS1'}).drop_duplicates('GCIF_PARENTS1'), on='GCIF_PARENTS1', how='left',suffixes=('', '_y')).drop_duplicates()

join_E1['CUSTOMER_FIELD19'] = join_E1.CUSTOMER_FIELD19
join_E1.loc[join_E1['CUSTOMER_FIELD19'].isnull(),'CUSTOMER_FIELD19'] = join_E1.CUSTOMER_FIELD19_y


join_E1['3RD_PARTY'] = join_E1['3RD_PARTY']
join_E1.loc[join_E1['3RD_PARTY'].isnull(),'3RD_PARTY'] = join_E1.INTERNAL_RATING_ORIGINAL_y


join_E2 = join_E1.merge(Report_Corp_CRDM1.rename(columns = {'GCIF_NUM':'GCIF_PARENTS1'}).drop_duplicates('GCIF_PARENTS1'), on='GCIF_PARENTS1', how='left',suffixes=('', '_y')).drop_duplicates()

join_E2['3RD_PARTY'] = join_E2['3RD_PARTY']
join_E2.loc[join_E2['3RD_PARTY'].isnull(),'3RD_PARTY'] = join_E2.RDMS_ADJ_BRR_y


join_E2['FINAL_RATING'] = join_E2['INTERNAL_RATING_ORIGINAL']
join_E2.loc[join_E2['FINAL_RATING'].isnull(),'FINAL_RATING'] = join_E2.RDMS_ADJ_BRR
join_E2.loc[join_E2['FINAL_RATING'].isnull(),'FINAL_RATING'] = join_E2['3RD_PARTY']
join_E2.loc[join_E2['FINAL_RATING'].isnull(),'FINAL_RATING'] = join_E2['PSE/SOV']
join_E2.loc[join_E2['FINAL_RATING'].isnull(),'FINAL_RATING'] = "Unrated"


join_E2.rename(columns={'M_MSIC_CODE':'BNM_SECTOR_CD',\
                       'INDUSTRIAL_SECTOR_CODE_(ISC_DESC)2':'SECTOR_DESC',\
                      'ISC_PARENT':'SECTOR_PARENT',\
                      'RDMS_ADJ_BRR':'CRRS',\
                      'INTERNAL_RATING_ORIGINAL':'RDMS',\
                      'GCIF_PARENTS1':'3RD_PARTY_PARENT'},inplace=True)

join_E2['SEGMENT'] = '01. CB'

join_E2 = join_E2[['M_CUS_NO',\
                'NAME',\
                'BNM_SECTOR_CD',\
                'SECTOR_DESC',\
                'SECTOR_PARENT',\
                'SEGMENT',\
                'RDMS',\
                'CUSTOMER_FIELD19',\
                'PSE/SOV',\
                'CRRS',\
                '3RD_PARTY_PARENT',\
                '3RD_PARTY',\
                'FINAL_RATING']]

In [39]:
writer2 = pd.ExcelWriter(r'T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\18_Rating_CBBBRSME\BRR_CBBBRSME_'+date[:6]+'(python).xlsx',engine='xlsxwriter')

join_E2.to_excel(writer2, index = False)

writer2.save()

In [ ]:
=='Unrated'  !='N'

In [38]:
a = join_E2.iloc[np.where(join_E2['FINAL_RATING']=='Unrated')]
a

,M_CUS_NO,NAME,BNM_SECTOR_CD,SECTOR_DESC,SECTOR_PARENT,SEGMENT,RDMS,CUSTOMER_FIELD19,PSE/SOV,CRRS,3RD_PARTY_PARENT,3RD_PARTY,FINAL_RATING
13,23034947,FGV TRADING SDN BHD,10401A,INTEGRATED PLAYER FOR MANUFACTURE OF CRUDE PALM OIL,03. MANUFACTURING,01. CB,NaN,NaN,None,NaN,N,NaN,Unrated
77,27282547,SHARJAH ELECTRICITY WATER AND GAS AUTHOR,3510XB,ELECTRICITY POWER GENERATION - NATURAL GAS FIRED POWER PLANT,"04. ELECTRICITY, GAS, STEAM AND AIR CONDITIONING SUPPLY",01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
92,18902204,JCORP CAPITAL EXCELLENCE SDN. BHD.,72105,RESEARCH AND DEVELOPMENT ON AGRICULTURAL SCIENCES,"13. PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES",01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
117,7051644,TNB FUEL SERVICES SDN BHD,72199,OTHER RESEARCH AND EXPERIMENTAL DEVELOPMENT ON NATURAL SCIENCES AND ENGINEERING,"13. PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES",01. CB,NaN,NaN,None,NaN,N,NaN,Unrated
198,21855848,PT FELDA INDO RUBBER,22XXXF,MANUFACTURE OF OTHER RUBBER PRODUCTS N.E.C,03. MANUFACTURING,01. CB,NaN,NaN,None,NaN,N,NaN,Unrated
209,21729247,FGV BIOTECHNOLOGIES SDN. BHD.,3520XA,"MANUFACTURE OF GASEOUS FUELS WITH A SPECIFIED CALORIFIC VALUE, BY PURIFICATION, BLENDING AND OTHER PROCESSES FROM GASES OF VARIOUS TYPES INCLUDING NATURAL GAS","04. ELECTRICITY, GAS, STEAM AND AIR CONDITIONING SUPPLY",01. CB,NaN,NaN,None,NaN,N,NaN,Unrated
242,26235964,SIME DARBY SWEDISH AUTO SDN. BHD.,451XXB,RETAILER OF NEW PASSENGER MOTOR VEHICLES (EXCLUDE COMMERCIAL VEHICLES),07. WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VEHICLES AND MOTORCYCLES,01. CB,NaN,NaN,None,NaN,N,NaN,Unrated
245,24165522,MSM SUGAR REFINERY (JOHOR) SDN BHD,107XX,MANUFACTURE OF OTHER FOOD PRODUCTS,03. MANUFACTURING,01. CB,NaN,NaN,None,NaN,N,NaN,Unrated
332,7768664,AMANAH SAHAM NASIONAL BERHAD,64999,"OTHER FINANCIAL SERVICE ACTIVITIES, EXCEPT INSURANCE/TAKAFUL AND PENSION FUNDING N.E.C.",11. FINANCIAL AND INSURANCE/ TAKAFUL ACTIVITIES,01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
352,13291327,ETIQA FAMILY TAKAFUL BERHAD,651XX,INSURANCE/TAKAFUL,11. FINANCIAL AND INSURANCE/ TAKAFUL ACTIVITIES,01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
384,19561386,PHD DELIVERY SDN BHD,56103,FAST-FOOD RESTAURANTS,09. ACCOMMODATION AND FOOD SERVICE ACTIVITIES,01. CB,NaN,NaN,None,NaN,N,NaN,Unrated
399,1527498,KNUSFORD EQUIPMENT SDN BHD,77307,RENTAL AND OPERATIONAL LEASING OF OFFICE MACHINERY AND EQUIPMENT WITHOUT OPERATOR,14. ADMINISTRATIVE AND SUPPORT SERVICE ACTIVITIES,01. CB,NaN,NaN,None,NaN,N,NaN,Unrated
400,26284121,SIME DARBY AUTO STUTTGART SDN. BHD.,29XXXA,"MANUFACTURE OF MOTOR VEHICLES, INCLUDE ENGINES",03. MANUFACTURING,01. CB,NaN,NaN,None,NaN,N,NaN,Unrated
404,16163111,SIME DARBY AUTO ENGINEERING SDN BHD,29XXXA,"MANUFACTURE OF MOTOR VEHICLES, INCLUDE ENGINES",03. MANUFACTURING,01. CB,NaN,NaN,None,NaN,N,NaN,Unrated
406,27073105,SWM GREENTECH SDN BHD,382XXC,OTHER WASTE TREATMENT AND DISPOSAL N.E.C.,"05. WATER SUPPLY; SEWERAGE, WASTE MANAGEMENT AND REMEDIATION ACTIVITIES",01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
413,5151161,REGION FOOD INDUSTRIES SDN BHD,107XX,MANUFACTURE OF OTHER FOOD PRODUCTS,03. MANUFACTURING,01. CB,NaN,NaN,None,NaN,N,NaN,Unrated
416,19479342,GREAT EASTERN TAKAFUL BHD,651XX,INSURANCE/TAKAFUL,11. FINANCIAL AND INSURANCE/ TAKAFUL ACTIVITIES,01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
422,25197224,ETIQA GENERAL TAKAFUL BERHAD,651XX,INSURANCE/TAKAFUL,11. FINANCIAL AND INSURANCE/ TAKAFUL ACTIVITIES,01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
423,27467500,MYTEAM PROPERTIES SDN. BHD.,68109,REAL ESTATE ACTIVITIES WITH OWN OR LEASED PROPERTY N.E.C.,12. REAL ESTATE ACTIVITIES,01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
425,21725108,LANGSAT OSC SDN BHD,429XXC,CONSTRUCTION OF OTHER ENGINEERING PROJECTS N.E.C.,06. CONSTRUCTION,01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
436,22356725,BOARDROOM OUTSOURCE SERVICES SDN. BHD.,70209,OTHER MANAGEMENT CONSULTANCY ACTIVITIES N.E.C.,"13. PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES",01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
440,27582571,WASCO ENGINEERING INTERNATIONAL LIMITED,19XXXB,MANUFACTURE OF REFINED PETROLEUM PRODUCTS,03. MANUFACTURING,01. CB,NaN,NaN,None,NaN,N,NaN,Unrated
456,7888346,ZECON LAND SDN BHD,41001C,DEVELOPER - AFFORDABLE HOUSING SCHEME (AS APPROVED BY GOVERNMENT) FOR SALE,06. CONSTRUCTION,01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
460,1484158,SPM RESTAURANTS SDN BHD,56101,RESTAURANTS AND RESTAURANT CUM NIGHT CLUBS,09. ACCOMMODATION AND FOOD SERVICE ACTIVITIES,01. CB,NaN,NaN,None,NaN,N,NaN,Unrated
463,21516161,FGV R&D SDN BHD,72105,RESEARCH AND DEVELOPMENT ON AGRICULTURAL SCIENCES,"13. PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES",01. CB,NaN,NaN,None,NaN,N,NaN,Unrated
481,25432296,MAJLIS BANDARAYA KUALA TERENGGANU,841XX,ADMINISTRATION OF THE STATE AND THE ECONOMIC AND SOCIAL POLICY OF THE COMMUNITY,15. PUBLIC ADMINISTRATION AND DEFENCE; COMPULSORY SOCIAL SECURITY,01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
482,7185822,PJB CAPITAL SDN BHD,74XXX,"OTHER PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES","13. PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES",01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
489,19068406,TIRAM FRESH SDN BHD,0113X,"GROWING OF VEGETABLES AND MELONS, ROOTS AND TUBERS","01. AGRICULTURE, FORESTRY AND FISHING",01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
490,4540342,KAA TRAVEL & TOURS SDN BHD,7210,MINING OF URANIUM AND THORIUM ORES,02. MINING AND QUARRYING,01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
493,27400167,DIAN INTERIOR DESIGN SDN BHD,41001H,CONTRACTOR - OTHER RESIDENTIAL BUILDINGS,06. CONSTRUCTION,01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
498,24493291,DEMAK CONCESSIONAIRES SDN BHD,429XXC,CONSTRUCTION OF OTHER ENGINEERING PROJECTS N.E.C.,06. CONSTRUCTION,01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
499,25941900,SIME DARBY PROPERTY (SELANGOR) SDN.BHD.,41001D,DEVELOPER - OTHER RESIDENTIAL BUILDINGS FOR SALE,06. CONSTRUCTION,01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
501,19438995,MY PREMIER TRUSTEE (MALAYSIA) BERHAD,64309,"TRUSTS, FUNDS AND SIMILAR FINANCIAL ENTITIES N.E.C.",11. FINANCIAL AND INSURANCE/ TAKAFUL ACTIVITIES,01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
502,22329461,PR1MA DEVELOPMENT SDN BHD,41009,CONSTRUCTION OF BUILDINGS N.E.C.,06. CONSTRUCTION,01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
503,21870124,MAYBANK ISLAMIC ASSET MANAGEMENT SDN BHD,66199,ACTIVITIES AUXILIARY TO FINANCE N.E.C.,11. FINANCIAL AND INSURANCE/ TAKAFUL ACTIVITIES,01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
504,25276847,JBIOTECH SAINTIFIK SDN BHD,72105,RESEARCH AND DEVELOPMENT ON AGRICULTURAL SCIENCES,"13. PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES",01. CB,NaN,CORP(SA),None,NaN,N,NaN,Unrated
513,10042966,QSR TRADING SDN BHD,107XX,MANUFACTURE OF OTHER FOOD PRODUCTS,03. MANUFACTURING,01. CB,NaN,NaN,None,NaN,N,NaN,Unrated

# FIX SECTION

In [40]:
Nisa = pd.read_excel(r'T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\18_Rating_CBBBRSME\BRR_CBBBRSME_202109.xlsx', sheet_name='Sheet1', header=0)

Nisa.columns = Nisa.columns.str.replace(" ","_").str.upper()
Nisa1 = Nisa.iloc[np.where(Nisa.SEGMENT=='01. CB')][['M_CUS_NO','FINAL_RATING']]

In [46]:
Nisa1.shape, join_E2.shape

((514, 2), (514, 13))

In [45]:
Syahid1 = join_E2[['M_CUS_NO','FINAL_RATING']]

In [54]:
Nisa1.M_CUS_NO = Nisa1.M_CUS_NO.astype(str)
a = Nisa1.merge(Syahid1,on='M_CUS_NO',how='left',indicator=True)

In [48]:
a._merge.value_counts()

both          514
right_only      0
left_only       0
Name: _merge, dtype: int64

In [55]:
#a.FINAL_RATING_x = a.FINAL_RATING_x.str.strip()
#a.FINAL_RATING_y = a.FINAL_RATING_y.str.strip()

a.iloc[np.where(a.FINAL_RATING_x!=a.FINAL_RATING_y)]

     M_CUS_NO FINAL_RATING_x FINAL_RATING_y _merge
0    23549043              2              2   both
1    20924517             16             16   both
2     6903241              5              5   both
3    17997345             11             11   both
4    11852516              9              9   both
..        ...            ...            ...    ...
500   1484816             19             19   both
506  18673802             23             23   both
508   3953976             13             13   both
511   4541869             23             23   both
513   6601059             10             10   both

[432 rows x 4 columns]