In [ ]:
RDATE = 20220930
DATE2 = "Sep'22"

import numpy as np
import pandas as pd
import pandasql
import sqlite3

pd.set_option("display.max_columns", None) 
pd.set_option("display.max_colwidth", 1000) #huruf dlm column
pd.set_option("display.max_rows", 100)
pd.set_option("display.precision", 2) #2 titik perpuluhan

#/*TO IMPORT CRRS FILE*/
CRRS = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\02_Data_Source\11_CRRS\\"+str(RDATE)[:4]+"\\"+str(RDATE)+"\Report_Corp_CRDM_"+str(RDATE)+".xlsx")


#/*TO IMPORT FRS FILE*/
FRS = pd.read_excel(r"T:\\MIB Risk Management\\Credit Risk Analytics - Historical\\02_Data_Source\\01_Corporate_Financing\\01_Portfolio\\"+str(RDATE)+"\\GB Monthly Loan Outstanding "+str(DATE2)+".xlsx")



#/*User Defined*/
RATING_CATEGORY = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\03_Data_Warehouse\01_Data_Dictionary\Rating_Category.xls")


SUB_MARKET_SEGMENT = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\03_Data_Warehouse\01_Data_Dictionary\Sub Market Segment Code.xls")

In [7]:
FRS

,As_of_Date,M_Cus_No,Name,Description,State_Desc,Branch_Code,Cust_Class_Cd,Nature_Of_Business,Economic_Sector_Cd,M_Npl_Date,M_Sub_Market_Segment_Cd,M_Market_Segment_Cd,Npl_Flg,M_Partial_Woff_Flg,Description.1,M_Customer_Type,M_Full_Writeoff_Flg,M_Financing_Type_Cd,Iso_Currency_Cd,M_Account_No,M_New_Npl_Flg,M_Interest_Code,M_Source_Prod_Type_Cd,Facility,Facility_2,M_Bnm_Balance_SUM,Authorised_Limit_SUM,M_Approved_Limit_SUM,Cur_Book_Bal_SUM,Maturity_Date,Origination_Date,M_Msic_Code,Description.2,ISC,Avg_Book_Bal_SUM,Common_Coa_Id,Issue_Date,M_Stock_Code,M_Folder_Name,M_New_Id_Number,CB_GROUP_NAME,AO/AM,AD,DIR,SD,BIZ_SEG
0,2022-09-30,16793,YOONG LI FAH,KUALA LUMPUR MAIN,FED. TERRITORY,1401.0,500,NaN,0310,01/01/1900,3,1,N,NaN,Consumer Loans,102,N,I,MYR,640010001826,N,46.0,HZK04,RTO,RTO,159535.09,0.0,360578.68,159535.09,2029-06-01,2021-10-31,97000,Household,Household,159190.06,12000,2022-05-05,NaN,NaN,650226045004,TBD,TBD,TBD,TBD,TBD,TBD
1,2022-09-30,20686,MOHD RADZI BIN HARUN,KUALA LUMPUR MAIN,FED. TERRITORY,1401.0,500,NaN,0310,01/01/1900,3,1,N,NaN,Consumer Loans,101,N,I,MYR,630010000919,N,46.0,HZK03,RTO,RTO,350175.51,0.0,661344.00,350175.51,2028-03-01,2021-08-12,97000,Household,Household,349500.83,12000,2021-08-12,NaN,NaN,650113086395,TBD,TBD,TBD,TBD,TBD,TBD
2,2022-09-30,67199,WONG TOH SING,KUALA LUMPUR MAIN,FED. TERRITORY,1401.0,500,NaN,0310,01/01/1900,3,1,N,NaN,Consumer Loans,102,N,I,MYR,620010000355,N,46.0,HZK03,RTO,RTO,552850.88,0.0,676091.86,552850.88,2028-02-01,2021-04-26,97000,Household,Household,505150.92,12000,2022-05-20,NaN,NaN,650714106339,TBD,TBD,TBD,TBD,TBD,TBD
3,2022-09-30,74417,NOOR AZAH BINTI ABU MANSOR,KUALA LUMPUR MAIN,FED. TERRITORY,1401.0,500,NaN,0310,01/01/1900,3,1,N,NaN,Consumer Loans,101,N,I,MYR,640010002027,N,46.0,HZK04,RTO,RTO,135846.00,0.0,645268.50,135846.00,2027-06-01,2021-12-17,97000,Household,Household,135846.00,12000,2022-04-28,NaN,NaN,650927015844,TBD,TBD,TBD,TBD,TBD,TBD
4,2022-09-30,92090,GARY CHIAM WEI HAN,KUALA LUMPUR MAIN,FED. TERRITORY,1401.0,500,NaN,0310,01/01/1900,3,1,N,NaN,Consumer Loans,102,N,I,MYR,820010000069,N,46.0,HZK01,RTO,RTO,914926.44,0.0,881736.65,914926.44,2024-08-16,2019-01-02,97000,Household,Household,913002.54,12000,2019-01-30,NaN,NaN,820120136011,TBD,TBD,TBD,TBD,TBD,TBD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25736,2022-09-30,28187557,PULLMAN WONG POO YEE,KUALA LUMPUR MAIN,FED. TERRITORY,1401.0,500,NaN,0310,01/01/1900,3,1,N,NaN,Consumer Loans,101,N,I,MYR,620010005887,N,46.0,HZK04,RTO,RTO,0.00,0.0,457900.00,0.00,2030-01-01,2022-09-27,97000,Household,Household,0.00,12000,2029-02-22,NaN,NaN,900811125389,TBD,TBD,TBD,TBD,TBD,TBD
25737,2022-09-30,28187565,BEH HONG JING,KUALA LUMPUR MAIN,FED. TERRITORY,1401.0,500,NaN,0310,01/01/1900,3,1,N,NaN,Consumer Loans,102,N,I,MYR,620010005818,N,46.0,HZK04,RTO,RTO,0.00,0.0,462650.00,0.00,2030-01-01,2022-09-12,97000,Household,Household,0.00,12000,2029-02-22,NaN,NaN,990622075644,TBD,TBD,TBD,TBD,TBD,TBD
25738,2022-09-30,28215068,PRADEEP MENON A/L VIJAYA KUMAR,KUALA LUMPUR MAIN,FED. TERRITORY,1401.0,500,NaN,0310,01/01/1900,3,1,N,NaN,Consumer Loans,102,N,I,MYR,620010005798,N,46.0,HZK04,RTO,RTO,0.00,0.0,822250.00,0.00,2026-12-31,2022-09-09,97000,Household,Household,0.00,12000,2029-02-22,NaN,NaN,920401055187,TBD,TBD,TBD,TBD,TBD,TBD
25739,2022-09-30,28237466,KWAN JIAN CHENG,KUALA LUMPUR MAIN,FED. TERRITORY,1401.0,500,NaN,0310,01/01/1900,3,1,N,NaN,Consumer Loans,102,N,I,MYR,620010005718,N,46.0,HZK04,RTO,RTO,0.00,0.0,563243.60,0.00,2028-06-01,2022-08-19,97000,Household,Household,0.00,12000,2029-02-22,NaN,NaN,900530125913,TBD,TBD,TBD,TBD,TBD,TBD
25740,2022-09-30,28257369,PRIYANGAPILLAY A/P JNANASUNDRAM,KUALA LUMPUR MAIN,FED. TERRITORY,1401.0,500,NaN,0310,01/01/1900,3,1,N,NaN,Consumer Loans,102,N,I,MYR,620010005864,N,46.0,HZK04,RTO,RTO,0.00,0.0,439495.90,0.00,2027-12-31,2022-09-21,97000,Household,Household,0.00,12000,2029-02-22,NaN,NaN,970420105034,TBD,TBD,TBD,TBD,TBD,TBD

In [6]:
FRS.columns = FRS.columns.str.replace(" ", "_")
B001 = FRS.sort_values(by=['M_Financing_Type_Cd','M_Cus_No'],ascending=[True,True])

In [ ]:

B001['CUS_NO'] = B001.M_Cus_No.astype(str).str.strip()

B001_1 = B001.sort_values(by=['M_Account_No'],ascending=[True])

B001_2 = B001_1.merge(S002[['ACCOUNT_NUMBER','O_S__RM_MILLION_']].rename(columns = {'O_S__RM_MILLION_':'SMA_CUS_BAL','ACCOUNT_NUMBER':'M_Account_No'}),on = 'M_Account_No' , how='left').sort_values(by=['CUS_NO'],ascending=[True])

B001_2.CUS_NO = B001_2.CUS_NO.astype(str)
W001.CUS_NO = W001.CUS_NO.astype(str)
S001.CUS_NO = S001.CUS_NO.astype(str)
EWS001.CUS_NO = EWS001.CUS_NO.astype(str)
I002.CUS_NO = I002.CUS_NO.astype(str)
RR001.CUS_NO = RR001.CUS_NO.astype(str)
C001.CUS_NO = C001.CUS_NO.astype(str)
RDMS003.CUS_NO = RDMS003.CUS_NO.astype(str)

W001['WATCHLIST_FLAG'] = 1
S001['SMA_FLAG'] = 1
I002['IMPAIRED_FLAG'] = 1
EWS001['EWS_FLAG'] = 1

W001.ACCOUNT_DETAILS__RM_MILLION__O_S.fillna(0, inplace=True)

B002 = B001_2.merge(W001[['CUS_NO','ACCOUNT_DETAILS__RM_MILLION__O_S','WATCHLIST_FLAG']].rename(columns = {'ACCOUNT_DETAILS__RM_MILLION__O_S':'WATCHL_BAL'}),on='CUS_NO',how='left').merge(S001[['CUS_NO','SMA_FLAG']],on='CUS_NO',how='left').merge(EWS001[['CUS_NO','EWS_FLAG']],on='CUS_NO',how='left').merge(I002[['CUS_NO','NCNPL_Flag','IMPAIRED_FLAG']],on='CUS_NO',how='left').merge(RR001[['CUS_NO','AQ_Quality_Status']].rename(columns = {'AQ_Quality_Status':'RR_TYPE'}),on='CUS_NO',how='left').merge(C001[['CUS_NO','RDMS_ADJ_BRR','FIN_FRR']],on='CUS_NO',how='left').merge(RDMS003[['CUS_NO','RATING']].rename(columns = {'RATING':'RDMS_RATING'}),on='CUS_NO',how='left')

B002.WATCHLIST_FLAG.fillna(0, inplace=True)
B002.SMA_FLAG.fillna(0, inplace=True)
B002.IMPAIRED_FLAG.fillna(0, inplace=True)
B002.EWS_FLAG.fillna(0, inplace=True)


def NEWLY_IF_FLAG(x):
    if x == 'Y':
        return 1
    else:
        return 0
    
B002['NEWLY_IF_FLAG'] = B002.NCNPL_Flag.apply(NEWLY_IF_FLAG)

B002.loc[B002.RR_TYPE == 'Rescheduled','RESCHEDULED_FLAG'] = 1
B002.loc[B002.RR_TYPE == 'Restructured','RESTRUCTURED_FLAG'] = 1
B002.loc[B002.RR_TYPE.isin(['Rescheduled','Restructured']),'R_N_R_FLAG'] = 1


B002.loc[B002.RDMS_ADJ_BRR.isna(), 'CRRS_RATING'] = "NA"
B002.loc[~(B002.RDMS_ADJ_BRR.isna()), 'CRRS_RATING'] = B002.RDMS_ADJ_BRR.str.strip()

B002['RATING'] = B002.RDMS_RATING.str.strip()
B002.loc[B002.RATING.isna(),'RATING'] = B002.CRRS_RATING.str.strip()
B002.loc[(B002.RATING.isna())|(B002.RATING=='NA'),'RATING'] = 'UNRATED'
B002.loc[B002.RATING == "DEFAULTED",'RATING'] = B002.CRRS_RATING.str.strip()

B002['COMBINED_RATING'] = B002.RATING

#/*JUST ADDED 14 AUG 2018. STARTING JUNE 2018, WE USE MISC CODE*/
#/*FORMAT ISC $170.;   JUST ADDED 14 AUG 2018. STARTING JUNE 2018, WE USE MISC CODE*/

B002.M_Msic_Code = B002.M_Msic_Code.str.upper()
B002.M_Msic_Code = B002.M_Msic_Code.str.strip()

B002.loc[B002.M_Msic_Code.isin(['01120','0113X','01140','0119XA','0119XB','01261A','01261B','01262A','01262B','01263','01269','01273','01279','01291','01299','0130X','0141X','0144X','0145X','0146XA','0146XB','0146XC','0149X','01500','016XX','0170X','0210X','0220X','0230X','0240X','031XXA','031XXB','031XXC','031XXD','032XXA','032XXB','032XXC', '1120','113X','1140','119XA','119XB','1261A','1261B','1262A','1262B','1263','1269','1273','1279','1291','1299','130X','141X','144X','145X','146XA','146XB','146XC','149X','1500','16XX','170X','210X','220X','230X','240X','31XXA','31XXB','31XXC','31XXD','32XXA','32XXB','32XXC']),'ISC_PARENT'] = "01. Agriculture, Forestry and Fishing"
B002.loc[B002.M_Msic_Code.isin(['05XXX','0610X','0620X','0710X','07210','07291','07299','08XXX','0910XA','0910XB','0910XC','0910XD','0910XE','0910XF','0910XG','09900', '5XXX','610X','620X','710X','7210','7291','7299','8XXX','910XA','910XB','910XC','910XD','910XE','910XF','910XG','9900']),'ISC_PARENT'] = "02. Mining and Quarrying"
B002.loc[B002.M_Msic_Code.isin(['1010X','1020X','1030X','10401A','10401B','10402A','10402B','10499','1050X','106XX','107XX','10800','110XXA','110XXB','12000','13XXX','14XXX','151XX','1520X','16XXX','1701X','181XX','18200','19XXXA','19XXXB','20XXX','21XXX','22XXXA','22XXXB','22XXXC','22XXXD','22XXXE','22XXXF','22XXXG','23XXXA','23XXXB','23XXXC','2410XA','2410XB','24201','24202','24209A','24209B','2431XA','2431XB','24320','251XX','25200','25910','25920','25930','2599X','26300','265XX','2670X','26999','27500','27999','28170','2819XA','2819XB','2819XC','2819XD','2819XE','28220','28299A','28299B','28299C','28299D','28299E','29XXXA','29XXXB','29XXXC','301XXA','301XXB','301XXC','301XXD','30200','30999A','30999B','30999C','3100X','32500','3290X','33XXXA','33XXXB','33XXXC','33XXXD','33XXXE','33XXXF','33XXXG','33XXXH']),'ISC_PARENT'] = "03. Manufacturing"
B002.loc[B002.M_Msic_Code.isin(['3510XA','3510XB','3510XC','3510XD','3510XE','3510XF','3510XG','3520XA','3520XB','3530X']),'ISC_PARENT'] = "04. Electricity, Gas, Steam and Air Conditioning Supply"
B002.loc[B002.M_Msic_Code.isin(['360XX','3700X','38112','38199','382XXA','382XXB','382XXC','3830X','39000']),'ISC_PARENT'] = "05. Water Supply; Sewerage, Waste Management and Remediation Activities"
B002.loc[B002.M_Msic_Code.isin(['41001A','41001B','41001C','41001D','41001E','41001F','41001G','41001H','41002A','41002B','41002C','41002D','41002E','41002F','41002G','41002H','41002I','41002J','41003','41009','4210XA','4210XB','4210XC','4210XD','4210XE','4210XF','4210XG','4220XA','4220XB','4220XC','4220XD','429XXA','429XXB','429XXC','431XX','432XX','4330X','4390X']),'ISC_PARENT'] = "06. Construction"
B002.loc[B002.M_Msic_Code.isin(['451XXA','451XXB','451XXC','451XXD','451XXE','4520X','4530XA','4530XB','4540X','462XXA','462XXB','462XXC','463XXA','463XXB','463XXC','463XXD','4641X','46496','46499','46510','46595','46599A','46599B','46599C','46999','4711X','4719X','472XXA','472XXB','472XXC','472XXD','478XX','479XX','40799A','40799B','40799C','40799D','40799E']),'ISC_PARENT'] = "07. Wholesale and Retail Trade; Repair of Motor Vehicles and Motorcycles"
B002.loc[B002.M_Msic_Code.isin(['4911X','4912X','4921X','4922X','49230','49300','5011X','50121','50122','5021X','5022X','51101A','51101B','51102','51103','51201','51202','51203','5210XA','5210XB','5221X','5222X','5223X','52241','52249','52291','52292','52299','53XXX']),'ISC_PARENT'] = "08. Transportation and Storage"
B002.loc[B002.M_Msic_Code.isin(['55101A','55101B','55101C','55101D','55104','55105','55108','55199','5520X','55900','56101','56102','56103','56104','56105','56106','56107','562XX','56302','56303','56399A','56399B']),'ISC_PARENT'] = "09. Accommodation and Food Service Activities"
B002.loc[B002.M_Msic_Code.isin(['58110','5812X','5813X','5819X','582XX','59XXX','60XXX','6110X','6120X','6130X','6190X','620XX','631XX','6391X','63990']),'ISC_PARENT'] = "10. Information and Communication"
B002.loc[B002.M_Msic_Code.isin(['64110','64191','64192','64193','64194','64195','64199','64200','64301','64302','64303','64304','64309','64910','64921','64922','64923','64924','64925','64929','64991','64992','64993','64999','651XX','6520X','65301','65302','66111','66112','66113','66114','66119','66121','66122','66123','66124','66125','66129','66191','66192','66199','66211','66212','66221','66222','66223','66224','66290','66301','66302','66303']),'ISC_PARENT'] = "11. Financial and Insurance/ Takaful Activities"
B002.loc[B002.M_Msic_Code.isin(['68101A','68101B','68101C','68102A','68102B','68102C','68102D','68102E','68103A','68103B','68104A','68104B','68104C','68104D','68104E','68104F','68104G','68109','68201','68202','68203','68209']),'ISC_PARENT'] =  "12. Real Estate Activities"
B002.loc[B002.M_Msic_Code.isin(['69XXX','70100','70201','70202','70203','70209','7110X','71200','72102','72103','72105','72106','72199','7220X','73100','73200','74XXX','75000']),'ISC_PARENT'] = "13. Professional, Scientific and Technical Activities"
B002.loc[B002.M_Msic_Code.isin(['7710X','772XX','77301','77307','77399','77400','78XXX','79XXX','80XXX','81XXX','821XX','82200','8230X','82910','8292XA','8292XB','8292XC','82990']),'ISC_PARENT'] = "14. Administrative and Support Service Activities"
B002.loc[B002.M_Msic_Code.isin(['841XX','842XX','8430X']),'ISC_PARENT'] = "15. Public Administration and Defence; Compulsory Social Security"
B002.loc[B002.M_Msic_Code.isin(['8510X','852XX','8530X','854XX','8550X']),'ISC_PARENT'] = "16. Education"
B002.loc[B002.M_Msic_Code.isin(['861XX','8620X','8690X','87XXX','88XXX']),'ISC_PARENT'] = "17. Human Health and Social Work Activities"
B002.loc[B002.M_Msic_Code.isin(['9000X','910XX','92000','93XXX']),'ISC_PARENT'] = "18. Arts, Entertainment and Recreation"
B002.loc[B002.M_Msic_Code.isin(['94XXXA','94XXXB','95XXX','960XX']),'ISC_PARENT'] = "19. Other Service Activities"
B002.loc[B002.M_Msic_Code.isin(['TXXXX']),'ISC_PARENT'] = "20. Activities of Households as Employers; Undifferentiated Goods and Services Producing Activities of Households for Own Use";
B002.loc[B002.M_Msic_Code.isin(['99000']),'ISC_PARENT'] = "21. Activities of Extraterritorial Organisations and Bodies"
B002.loc[B002.M_Msic_Code.isin(['97000']),'ISC_PARENT'] = "22. Household"
B002.loc[B002.ISC_PARENT.isna(),'ISC_PARENT'] = "23. Not Populated"


B002.Nature_Of_Business = B002.Nature_Of_Business.astype(str)

def SECTOR_GROUP(Nature_Of_Business):
    if Nature_Of_Business=='9999':
        return '9999'
    elif Nature_Of_Business[0] == '1': 
        return '1000'
    elif Nature_Of_Business[0] == '2': 
        return '2000'
    elif Nature_Of_Business[0] == '3': 
        return '3000'
    elif Nature_Of_Business[0] == '4': 
        return '4000'
    elif Nature_Of_Business[0] == '5': 
        return '5000'
    elif Nature_Of_Business[0] == '6': 
        return '6000'
    elif Nature_Of_Business[0] == '7': 
        return '7000'
    elif Nature_Of_Business[0] == '8': 
        return '8000'
    elif Nature_Of_Business[0] == '9': 
        return '9000' 
    else: 
        return '9999'
B002['SECTOR_GROUP'] = B002.apply(lambda x: SECTOR_GROUP(x['Nature_Of_Business']), axis=1)

def SECTOR_GROUP_DESC(Nature_Of_Business):
    if Nature_Of_Business=='9999':
        return 'SECTOR N.E.C'
    elif Nature_Of_Business[0] == '1': 
        return 'PRIMARY AGRICULTURE'
    elif Nature_Of_Business[0] == '2': 
        return 'MINING AND QUARRYING'
    elif Nature_Of_Business[0] == '3': 
        return 'MANUFACTURING (INCLUDING AGRO-BASED)'
    elif Nature_Of_Business[0] == '4': 
        return 'ELECTRICITY, GAS AND WATER SUPPLY'
    elif Nature_Of_Business[0] == '5': 
        return 'CONSTRUCTION'
    elif Nature_Of_Business[0] == '6': 
        return 'WHOLESALE AND RETAIL TRADE, AND RESTAURANT AND HOTELS'
    elif Nature_Of_Business[0] == '7': 
        return 'TRANSPORT, STORAGE AND COMMUNICATION'
    elif Nature_Of_Business[0] == '8': 
        return 'FINANCE, REAL ESTATE AND BUSINESS ACTIVITIES'
    elif Nature_Of_Business[0] == '9': 
        return 'EDUCATION, HEALTH AND OTHERS'
    else: 
        return 'SECTOR N.E.C'
B002['SECTOR_GROUP_DESC'] = B002.apply(lambda x: SECTOR_GROUP_DESC(x['Nature_Of_Business']), axis=1)

B003 = B002.merge(RATING_CATEGORY[['Combined_Rating','Risk_Category']].rename(columns = {'Combined_Rating':'COMBINED_RATING'}), on='COMBINED_RATING', how='left')

B000 = B003.sort_values(by=['M_Account_No'],ascending=[True])
B000['ACCOUNT_NO'] = B000.M_Account_No.str.strip()

#/*REFERENCE MARKET SEGMENT & GROUP*/
B004A = B003.merge(SUB_MARKET_SEGMENT.rename(columns = {'Code':'M_Sub_Market_Segment_Cd','Description':'M_Sub_Market_Segment_DESC'}), on='M_Sub_Market_Segment_Cd', how='left')

#/*REFERENCE CORP LIST & SCORECARD*/
B004 = B004A.merge(CRRS[['GCIF_NUM','SCORECARDS']].rename(columns = {'GCIF_NUM':'M_Cus_No'}), on='M_Cus_No', how='left')

MIB_CF = B004

MIB_CF.COMBINED_RATING= MIB_CF.COMBINED_RATING.str.upper()

MIB_CF.loc[MIB_CF.COMBINED_RATING.isin(["UNRATED"]), 'Risk_Category']="UNRATED"
MIB_CF.loc[MIB_CF.COMBINED_RATING.isin(["DEFAULTED"]), 'Risk_Category']="Sub-standard"
#/*  MANUAL ADJUSTMENT*/
MIB_CF.loc[MIB_CF.COMBINED_RATING.isin(["BKNM1"]), 'Risk_Category']="UNRATED"

MIB_CF.loc[MIB_CF.FIN_FRR.isin(["A+","A"]), 'COLLATERAL_TYPE'] ="01.SECURED"
MIB_CF.loc[MIB_CF.FIN_FRR.isin(["B","C","D","E","F"]), 'COLLATERAL_TYPE'] ="02.PARTIALLY SECURED"
MIB_CF.loc[MIB_CF.FIN_FRR.isin(["G","NA","?",""]), 'COLLATERAL_TYPE'] ="03.CLEAN"
MIB_CF.loc[MIB_CF.FIN_FRR.isna(), 'COLLATERAL_TYPE']="04.NOT POPULATED"

MIB_CF.loc[MIB_CF.Risk_Category.isin(["Very Low"]), 'RISK_CAT']="01.VERY LOW RISK"
MIB_CF.loc[MIB_CF.Risk_Category.isin(["Low"]), 'RISK_CAT']="02.LOW RISK"
MIB_CF.loc[MIB_CF.Risk_Category.isin(["Moderate"]), 'RISK_CAT']="03.MODERATE RISK"
MIB_CF.loc[MIB_CF.Risk_Category.isin(["High"]), 'RISK_CAT']="04.HIGH RISK"
MIB_CF.loc[MIB_CF.Risk_Category.isin(["Sub-standard"]), 'RISK_CAT']="05.SUB-STANDARD"
MIB_CF.loc[MIB_CF.Risk_Category.isin(["UNRATED"]), 'RISK_CAT']="06.UNRATED"
MIB_CF.loc[MIB_CF.Risk_Category.isin(["SOVEREIGN"]), 'RISK_CAT']="07.SOVEREIGN"
MIB_CF.loc[MIB_CF.Risk_Category.isin(["PSE"]), 'RISK_CAT']="08.PSE"
MIB_CF.loc[MIB_CF.RISK_CAT.isna(), 'RISK_CAT']="09.NOT POPULATED"

MIB_CF.loc[MIB_CF.M_Sub_Market_Segment_DESC.isin(["GWB-CORP GLC"]) , 'SEGMENT_TYPE']="01.GLC"
MIB_CF.loc[MIB_CF.M_Sub_Market_Segment_DESC.isin(["GWB-CORP MNC"]) , 'SEGMENT_TYPE']="02.MNC"
MIB_CF.loc[MIB_CF.M_Sub_Market_Segment_DESC.isin(["GWB-CORP MC"]) , 'SEGMENT_TYPE']="03.MC"
MIB_CF.loc[MIB_CF.M_Sub_Market_Segment_DESC.isin(["GWB-INTERNATIONAL"]) , 'SEGMENT_TYPE']="04.INTERNATIONAL"
MIB_CF.loc[MIB_CF.SEGMENT_TYPE.isna(),'SEGMENT_TYPE'] = "05.NOT POPULATED"


#/*TO CREATE BORROWER LEVEL DATASET*/
MIB_CF.M_Bnm_Balance_SUM_1.fillna(0,inplace=True)
CUS_BAL_TL = MIB_CF.iloc[np.where(MIB_CF.Facility.isin(["TL","TL_USD","TL_FC"]))][['CUS_NO','M_Bnm_Balance_SUM_1']].rename( columns = {'M_Bnm_Balance_SUM_1':'CUS_BAL_TL'}).groupby(['CUS_NO'])[['CUS_BAL_TL']].sum().reset_index()

CUS_BAL_TB = MIB_CF.iloc[np.where(MIB_CF.Facility.isin(["TB"]))][['CUS_NO','M_Bnm_Balance_SUM_1']].rename( columns = {'M_Bnm_Balance_SUM_1':'CUS_BAL_TB'}).groupby(['CUS_NO'])[['CUS_BAL_TB']].sum().reset_index()

CUS_BAL_OD = MIB_CF.iloc[np.where(MIB_CF.Facility.isin(["OD"]))][['CUS_NO','M_Bnm_Balance_SUM_1']].rename( columns = {'M_Bnm_Balance_SUM_1':'CUS_BAL_OD'}).groupby(['CUS_NO'])[['CUS_BAL_OD']].sum().reset_index()

CUS_BAL_STRC = MIB_CF.iloc[np.where(MIB_CF.Facility.isin(["STRC","STRC_USD","STRC_FC"]))][['CUS_NO','M_Bnm_Balance_SUM_1']].rename( columns = {'M_Bnm_Balance_SUM_1':'CUS_BAL_STRC'}).groupby(['CUS_NO'])[['CUS_BAL_STRC']].sum().reset_index()

#/*JUST ADDED AS AT 14 AUG 2018. ADDITIONAL INFO SINCE JUNE 2018 REPORT FOR RTO*/
CUS_BAL_RTO = MIB_CF.iloc[np.where(MIB_CF.Facility.isin(["RTO"]))][['CUS_NO','M_Bnm_Balance_SUM_1']].rename( columns = {'M_Bnm_Balance_SUM_1':'CUS_BAL_RTO'}).groupby(['CUS_NO'])[['CUS_BAL_RTO']].sum().reset_index()

row = ['M_Financing_Type_Cd','CUS_NO','Name','EWS_FLAG','WATCHLIST_FLAG','SMA_FLAG','IMPAIRED_FLAG','NEWLY_IF_FLAG','RESCHEDULED_FLAG','RESTRUCTURED_FLAG','R_N_R_FLAG','Nature_Of_Business','SECTOR_GROUP','SECTOR_GROUP_DESC','M_Msic_Code','ISC_PARENT','COMBINED_RATING','Risk_Category','RISK_CAT','SEGMENT_TYPE','FIN_FRR','COLLATERAL_TYPE','CUST_GROUP','SCORECARDS']

column = ['SMA_CUS_BAL','Authorised_Limit_SUM','M_Approved_Limit_SUM','M_Bnm_Balance_SUM_1']

MIB_CF.fillna(0,inplace=True)

MIB_CF_CUS_001 = MIB_CF.iloc[np.where(MIB_CF.M_Financing_Type_Cd=='I')].groupby(row)[column].sum().reset_index().rename( columns = {'SMA_CUS_BAL':'SMA_CUS_BAL','Authorised_Limit_SUM':'CUS_AUTHOR_LIMIT','M_Approved_Limit_SUM':'CUS_APPROV_LIMIT','M_Bnm_Balance_SUM_1':'CUS_BAL'})

MIB_CF_CUS_002 = MIB_CF_CUS_001.merge(CUS_BAL_TL, on='CUS_NO', how='left').merge(CUS_BAL_OD, on='CUS_NO', how='left').merge(CUS_BAL_TB, on='CUS_NO', how='left').merge(CUS_BAL_STRC, on='CUS_NO', how='left').merge(CUS_BAL_RTO, on='CUS_NO', how='left')


MIB_CF_CUS_002['CUS_LIMIT'] = MIB_CF_CUS_002.CUS_AUTHOR_LIMIT + MIB_CF_CUS_002.CUS_APPROV_LIMIT

MIB_CF_CUS_002.loc[MIB_CF_CUS_002.IMPAIRED_FLAG == 1,'CUS_STATUS'] = "IMPAIRED"
MIB_CF_CUS_002.loc[MIB_CF_CUS_002.SMA_FLAG == 1,'CUS_STATUS'] = "SMA"
MIB_CF_CUS_002.loc[MIB_CF_CUS_002.WATCHLIST_FLAG == 1,'CUS_STATUS'] = "WATCHLIST"
MIB_CF_CUS_002.loc[MIB_CF_CUS_002.EWS_FLAG == 1,'CUS_STATUS'] = "EWS"
MIB_CF_CUS_002.loc[MIB_CF_CUS_002.CUS_STATUS.isna(),'CUS_STATUS'] = "PERFORMING"

MIB_CF_CUS_002.loc[MIB_CF_CUS_002.RESCHEDULED_FLAG == 1,'RR_STATUS'] = "RESCHEDULED"
MIB_CF_CUS_002.loc[MIB_CF_CUS_002.RESTRUCTURED_FLAG == 1,'RR_STATUS'] = "RESTRUCTURED"
MIB_CF_CUS_002.loc[MIB_CF_CUS_002.RR_STATUS.isna(),'RR_STATUS'] = "N"

In [ ]:


#/*TO IMPORT ASSET QUALITY FILE*/
#/*TO IMPORT IMPAIRED ACCOUNTS*/
IMPAIRED = pd.read_excel(r"T:\\MIB Risk Management\\Credit Risk Analytics - Historical\\02_Data_Source\\01_Corporate_Financing\\02_Asset_Quality\\"+str(RDATE)+"\\Asset_Quality_Master_List_"+str(RDATE)+".xlsx", sheet_name="Impaired_Accounts")


#/*TO IMPORT SMA*/
SMA = pd.read_excel(r"T:\\MIB Risk Management\\Credit Risk Analytics - Historical\\02_Data_Source\\01_Corporate_Financing\\02_Asset_Quality\\"+str(RDATE)+"\\Asset_Quality_Master_List_"+str(RDATE)+".xlsx", sheet_name="SMA")


#/*TO IMPORT WATCHLIST*/
WATCHLIST = pd.read_excel(r"T:\\MIB Risk Management\\Credit Risk Analytics - Historical\\02_Data_Source\\01_Corporate_Financing\\02_Asset_Quality\\"+str(RDATE)+"\\Asset_Quality_Master_List_"+str(RDATE)+".xlsx", sheet_name="Watchlist")


#/*TO IMPORT EWS*/
EWS = pd.read_excel(r"T:\\MIB Risk Management\\Credit Risk Analytics - Historical\\02_Data_Source\\01_Corporate_Financing\\02_Asset_Quality\\"+str(RDATE)+"\\Asset_Quality_Master_List_"+str(RDATE)+".xlsx", sheet_name="EWS")


#/*TO IMPORT R&R*/
RR = pd.read_excel(r"T:\\MIB Risk Management\\Credit Risk Analytics - Historical\\02_Data_Source\\01_Corporate_Financing\\02_Asset_Quality\\"+str(RDATE)+"\\Asset_Quality_Master_List_"+str(RDATE)+".xlsx", sheet_name="R&R")

#/*TO IMPORT RDMS*/ /*new format of RDMS dataset 26 Nov 2019*/
RDMS = pd.read_excel(r"T:\\MIB Risk Management\\Credit Risk Analytics - Historical\\02_Data_Source\\12_RDMS\\"+str(RDATE)+"\\RDMS_CB_"+str(RDATE)+".xlsx")