In [2]:
date = '20220930'  #current date

import numpy as np
import pandas as pd
import pandasql
import sqlite3

pd.set_option("display.max_columns", None) 
pd.set_option("display.max_colwidth", 1000) #huruf dlm column
pd.set_option("display.max_rows", 100)
pd.set_option("display.precision", 2) #2 titik perpuluhan

SAS = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\12_Investment_Account\\"+date+"\IA_"+str(date)+".xlsx", sheet_name='IA'+date)

Python = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\01_Reporting\01_Monthly_Reporting\12_Investment_Account\\"+date+"\IA_"+str(date)+"(python).xlsx", sheet_name='IA'+date)

In [7]:
SAS1 = SAS.iloc[np.where(SAS.DATA_SOURCE=='02. OD')]

In [8]:
Python1 = Python.iloc[np.where(Python.DATA_SOURCE=='02. OD')]

In [10]:
sum(SAS1.M_BNM_BALANCE_MIL)

6656.367308050003

In [11]:
sum(Python1.M_BNM_BALANCE_MIL)

6656.321301180002

In [12]:
date = 20220930
nYear = 365

location_OD = r"T:\MIB Risk Management\Credit Risk Analytics - Historical\04_Infocube\99_Data_Source\01_Datawarehouse\01_Credit_Risk_Reporting\05_MIB_OD\\"+str(date)+"\\MIB_OD"+str(date)+".txt"
OD = pd.read_csv(location_OD, sep = "\t", header = 0)
OD.columns = OD.columns.str.replace(" ", "_")
OD.Account_No = OD.Account_No.astype(str)
OD['Account_No'] = OD.Account_No.str[:20]

In [14]:
sum(OD.M_Bnm_Balance)

6656321301.180026

In [15]:
OD_info  = pd.read_excel(r"T:\MIB Risk Management\Credit Risk Analytics - Historical\04_Infocube\02_OD\\"+str(date)+"\\OD"+str(date)+".xlsx")
OD_info.columns = OD_info.columns.str.replace(" ", "_")
OD_info.Account_No = OD_info.Account_No.astype(str)

In [17]:
sum(OD_info.M_Bnm_Balance)

6656367308.050018

In [21]:
OD_info.iloc[np.where(OD_info.Account_No=='501600003891')]

,Account_No,Cus_No,Amrt_Term,Amrt_Term_Mult,As_Of_Date,Branch_Code,Common_Coa_Id,Record_Count,Acct_Status_Cd,Account_Open_Date,Date_Aa_Approved,Authorised_Limit,Drawing_Limit,Source_Prod_Type_Cd,Special_Mention_Acct_Flg,Interest_Income,Interest_Income_Myr,Non_Interest_Income,Interest_In_Suspense,Specific_Provision,Economic_Sector_Cd,Full_Writeoff_Flg,Reschedule_Flg,Restructure_Flg,Npl_Flg,New_Npl_Flg,Total_Activity_Cost,Maintenance_Cost,Entity_Cd,M_Bnm_Balance,M_Sub_Market_Segment_Cd,Product_Hierarchy_Cd,M_Financing_Concept,M_Mths_In_Arrears,Avg_Book_Bal,Net_Int_Income,Net_Int_Income_Myr,Cur_Gross_Rate,Aa_Number,Gl_Account_Id,First_Release_Date,Final_Release_Date,Reschedule_Date,Restructure_Date,Npl_Date,Security_Type_Cd,Ead_PROPORTIONAL_MYR,EXPECTED_LOSS_MYR,RWA_AFTER_RISK_MIT_MYR,Approach,Sector_Category,Rsme_Inclusion_Indicator,Rs_Inclusion_Indicator,Report_Indicator,PD_SEGMENT,Level_4,Level_5,Level_6,Source_Prod_Type_Dsc,Econ_Sector,Region_Desc,State_Desc,Branch_Desc,NAME,CUSTOMER_SEGMENT,M_MARKET_SEGMENT_CD,M_SUB_SUB_MARKET_SEGMENT,M_CUSTOMER_TYPE,INDUSTRIAL_SECTOR,M_RACE_CD,SEX,M_NATIONALITY_CD,BTH_DT,M_OCC_SECTOR_CD,M_INCOME_GRP_CD,MARRIED,MBB_Nationality_Desc,Occ_Sector,Income_Grp,M_SUB_MARKET_SEGMENT_DESC,NOB_Cd,RACE,GENDER,AGE,AGE_RANGE,MARITAL_STATUS,Funds_Charge,Funds_Charge_Myr
12,501600003891,25091830,60,M,2022-09-30,160,12000,1,1,2017-10-02,2021-07-12,262500.0,262500.0,PMA,N,642.33,642.33,233.53,0.0,0.0,6250,N,N,N,N,N,57.59,10.5,MIB,46006.87,1,PMA_66_12000,NUL,0,97169.93,414.47,414.47,8.04,2021JG1127,120101212119,2021-08-04,2021-08-04,1900-01-01,1900-01-01,1900-01-01,59,58134.37,18.9,925.72,6.0,7.0,MS03,NaN,NaN,R2 - B,OD,Government Aided Schemes,Others,PREMIER MUDHARABAH CA,"Miscellaneous Retail Trade, n.e.c",JOHOR/MELAKA,JOHOR,"GELANG PATAH, JB",I BATH STUDIO,6.0,1,1.0,202,40799E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CFS-SME,NaN,Not Populated,Not Populated,NaN,I. Not Populated,Not Populated,119.8,119.8
13,501600003891,25091830,60,M,2022-09-30,160,12000,1,1,2017-10-02,2021-07-12,262500.0,262500.0,PMA,N,642.33,642.33,233.53,0.0,0.0,6250,N,N,N,N,N,57.59,10.5,MIB,46006.87,1,PMA_66_12000,NUL,0,97169.93,414.47,414.47,8.04,2021JG1127,120101212119,2021-08-04,2021-08-04,1900-01-01,1900-01-01,1900-01-01,59,58134.37,18.9,925.72,6.0,7.0,MS03,NaN,NaN,R2 - B,OD,Government Aided Schemes,Others,PREMIER MUDHARABAH CA,"Miscellaneous Retail Trade, n.e.c",NaN,NaN,NaN,I BATH STUDIO,6.0,1,1.0,202,40799E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CFS-SME,NaN,Not Populated,Not Populated,NaN,I. Not Populated,Not Populated,119.8,119.8